### ISSUE TITLE
Emprowr,Metamask/eth phishing detect

### ISSUE THREAD

**Issue by gordanazivkovic25** [MetaMask/eth-phishing-detect#2670] opened 2018-11-28 15:24 UTC
Please,can you tell me why i cant open Emprowr site;its sign:-Attention,Metamask/eth phishing detect?

**Comment by 409H** [comment] 2018-11-28 23:18
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2663

**Closed by 409H** 2018-11-28 23:18 UTC

**Comment by gordanazivkovic25** [comment] 2018-11-29 10:00
What i need to do?
