### ISSUE TITLE
333eth.io Scam

### ISSUE THREAD

**Issue by Slavikys13** [MetaMask/eth-phishing-detect#2380] opened 2018-09-11 20:01 UTC
333ETH.IO - IS NOT A SCAM AND NOT A FISHING SITE.
This is the machinations of competitors. Unlock this site, please

**Comment by 409H** [comment] 2018-09-12 00:56
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2374

**Closed by 409H** 2018-09-12 00:56 UTC
