### ISSUE TITLE
[Legitimate Site Blocked] zksync.crew3.xyz

### ISSUE THREAD

**Issue by alexsubbota** [MetaMask/eth-phishing-detect#9219] opened 2022-11-01 11:43 UTC
https://zksync.crew3.xyz/invite/7OdKpZrNbXtqcWdFjPnnI

**Comment by 409H** [comment] 2022-11-07 21:09
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/9291

**Closed by 409H** 2022-11-07 21:09 UTC
Labels: duplicate, allowlist request
