### ISSUE TITLE
[Legitimate Site Blocked] wallet.elrond.com

### ISSUE THREAD

**Issue by KrisCanCrypto** [MetaMask/eth-phishing-detect#8934] opened 2022-10-17 15:42 UTC
This is the Elrond official wallet site. You have it marked wrongly. 

https://wallet.elrond.com/unlock/ledger

All the best,
Kris Can

**Comment by 409H** [comment] 2022-11-07 22:48
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8870

**Closed by 409H** 2022-11-07 22:48 UTC
Labels: duplicate, allowlist request
