### ISSUE TITLE
empowr

### ISSUE THREAD

**Issue by alnasim** [MetaMask/eth-phishing-detect#2666] opened 2018-11-27 07:05 UTC
my empowr site showing ethereum scam kindly secure my empowr login user id sadiqtahira23718@gmail.com

**Comment by jeckoz** [comment] 2018-11-27 11:39
scam. 
keep it that way

**Comment by 409H** [comment] 2018-11-27 14:40
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2663

**Closed by 409H** 2018-11-27 14:40 UTC

**Comment by imrantaabu** [comment] 2018-12-07 04:53
my empowr site is showing red page warning please fix my issue

**Comment by imrantaabu** [comment] 2018-12-07 04:55
my wallet account not active please help me to active my account
