### ISSUE TITLE
not phising site : auctor.me

### ISSUE THREAD

**Issue by jahoy** [MetaMask/eth-phishing-detect#2610] opened 2018-10-28 05:46 UTC
Hello admin,

My website is not phsing site
www.auctor.me
Could you solve the problem??

**Comment by 409H** [comment] 2018-11-06 02:14
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2608

**Closed by 409H** 2018-11-06 02:14 UTC
