### ISSUE TITLE
[Legitimate Site Blocked] www.metabase.art

### ISSUE THREAD

**Issue by hypergraphdev** [MetaMask/eth-phishing-detect#6057] opened 2021-12-01 01:56 UTC
https://www.metabase.art is a new domain. why in this list

**Comment by devenblake** [comment] 2021-12-01 02:22
Duplicate of #6003, fixed in #6035, please wait for caches to clear and it'll be unblocked.

**Closed** 2021-12-03 06:06 UTC
Labels: duplicate
