### ISSUE TITLE
[Legitimate Site Blocked] app.cryptoblades.io

### ISSUE THREAD

**Issue by pdoteter** [MetaMask/eth-phishing-detect#7019] opened 2022-03-31 07:19 UTC
https://app.cryptoblades.io/#/raid

It's in my bookmarks to return to the Cryptoblades app, it's a legit site

**Comment by devenblake** [comment] 2022-04-08 02:42
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/7010.

**Closed by devenblake** 2022-04-08 02:42 UTC
Labels: duplicate, allowlist request
