### ISSUE TITLE
[Legitimate Site Blocked] binances.club

### ISSUE THREAD

**Issue by nikiKolya** [MetaMask/eth-phishing-detect#7416] opened 2022-05-18 20:54 UTC
https://binances.club
![b08b37d33c](https://user-images.githubusercontent.com/105822555/169154062-6f4d502c-5142-4516-94c1-49d28c6ec689.jpg)
/

**Comment by devenblake** [comment] 2022-05-18 21:01
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/6696.

**Closed by devenblake** 2022-05-18 21:01 UTC
