### ISSUE TITLE
[Legitimate Site Blocked] wallet.elrond.com

### ISSUE THREAD

**Issue by Art879** [MetaMask/eth-phishing-detect#8954] opened 2022-10-18 05:04 UTC
https://wallet.elrond.com/hook/login?token=ba9262928f6b8c8a3d3a5f231c31ed59&callbackUrl=https%3A%2F%2Fmaiarlaunchpad.com%2F

**Comment by 409H** [comment] 2022-11-07 22:49
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8870

**Closed by 409H** 2022-11-07 22:49 UTC
Labels: duplicate, allowlist request
