### ISSUE TITLE
[Legitimate Site Blocked] www.meta-musk.com

### ISSUE THREAD

**Issue by colopelo17** [MetaMask/eth-phishing-detect#5910] opened 2021-11-12 09:44 UTC
https://www.meta-musk.com/

I do not understand this blacklist because meta-musk has absolutely nothing to do with metamask no payment has to ask on the site it is only a token on the theme elon musk please remove the blacklist by meta-musk

**Comment by devenblake** [comment] 2021-11-12 15:11
Duplicate of #5908.

**Closed** 2021-11-16 01:58 UTC
