### ISSUE TITLE
extension://ejbalbakoplchlghecdalmeeeajnimhm/phishing.html#hostname=www.free-ethereum.io&href=https%3A%2F%2Fwww.free-ethereum.io%2Ffree%2F

### ISSUE THREAD

**Issue by giostema** [MetaMask/eth-phishing-detect#5332] opened 2021-08-27 00:32 UTC

**Comment by davidwgrossman** [comment] 2021-08-30 19:26
duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/5342

**Closed by davidwgrossman** 2021-08-30 19:26 UTC
