### ISSUE TITLE
[Legitimate Site Blocked] opensky.blue

### ISSUE THREAD

**Issue by CROSSTECHx20090104** [MetaMask/eth-phishing-detect#5911] opened 2021-11-12 15:57 UTC
Dear MetaMask support,

Would like to inform you this site is being unnecessarily flagged as "Ethereum Phishing Detection."

Although Opensky.blue is a fairly new NFT sales website, I can assure you the website is a Japanese based NFT sales website that is not fraudulent or performing any phishing activities.  We would appreciate if you could remove the Metamask phishing warning for our website at your earliest convenience.

https://opensky.blue/

OpenSkyBlue director
Taketo Nakanishi

Best regards,

**Comment by devenblake** [comment] 2021-11-13 03:51
Duplicate of #5906.

**Closed** 2021-11-16 01:58 UTC
