### ISSUE TITLE
[Legitimate Site Blocked] officialnft.xyz

### ISSUE THREAD

**Issue by dcxbutcher615** [MetaMask/eth-phishing-detect#7005] opened 2022-03-30 08:18 UTC
it's legit website what going on?

https://officialnft.xyz/

**Comment by jasonmaggio** [comment] 2022-03-30 20:22
@dcxbutcher615 we appreciate your effort to reach out to MM. We've created a ticket as well. We're hoping somebody gets back to us quickly and we get this whitelisted so our users aren't getting this message.

@mcmire @409H

**Comment by devenblake** [comment] 2022-04-05 04:27
Duplicate of #6938.

**Closed by devenblake** 2022-04-05 04:27 UTC
Labels: duplicate, allowlist request
