### ISSUE TITLE
[Legitimate Site Blocked] form.jotform.com

### ISSUE THREAD

**Issue by totalhack** [MetaMask/eth-phishing-detect#8151] opened 2022-08-11 13:47 UTC
Please fix this ASAP, this is breaking a ton of websites for anyone that has metamask installed.

**Comment by 409H** [comment] 2022-11-07 22:12
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8142

**Closed by 409H** 2022-11-07 22:12 UTC
Labels: duplicate, allowlist request
