### ISSUE TITLE
[Legitimate Site Blocked] bakedbeans.io

### ISSUE THREAD

**Issue by Websurfman1** [MetaMask/eth-phishing-detect#8853] opened 2022-10-15 05:13 UTC
https://bakedbeans.io/

This is not a Phishing website been using it for longer already.

Kind regards,

Marc

**Comment by 409H** [comment] 2022-11-07 23:19
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/9062

**Closed by 409H** 2022-11-07 23:19 UTC
Labels: duplicate, allowlist request
