### ISSUE TITLE
Legitimate Site Blocked] binances.club

### ISSUE THREAD

**Issue by raomohsin39** [MetaMask/eth-phishing-detect#7531] opened 2022-05-28 16:46 UTC
Hello dear devenblake, Please unblock the site of our community. We will be very grateful

**Comment by devenblake** [comment] 2022-05-31 04:18
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/6696.

**Closed by devenblake** 2022-05-31 04:18 UTC
Labels: duplicate, allowlist request
