### ISSUE TITLE
[Legitimate Site Blocked] ltcminer.com

### ISSUE THREAD

**Issue by zakkri** [MetaMask/eth-phishing-detect#6024] opened 2021-11-27 10:44 UTC
https://ltcminer.com/?__cf_chl_rt_tk=URSklzOO1XmuvuwzF0YHzxossmpfSyquCh.sJd8G4X8-1638009812-0-gaNycGzNBv0

**Comment by devenblake** [comment] 2021-12-14 02:17
Duplicate of #4472.

**Closed** 2022-01-13 01:35 UTC
Labels: duplicate
