### ISSUE TITLE
MetaMask not letting me access DaliyDivs web site

### ISSUE THREAD

**Issue by Tim5555** [MetaMask/eth-phishing-detect#2419] opened 2018-09-14 15:33 UTC
MetaMask not letting me access DaliyDivs web site. The site is safe please stop blocking daliy divs website

**Comment by 409H** [comment] 2018-09-15 17:50
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2427

**Closed by 409H** 2018-09-15 17:50 UTC
