### ISSUE TITLE
[Legitimate Site Blocked] zksync.crew3.xyz created by zkSync Community Manager

### ISSUE THREAD

**Issue by bxpana** [MetaMask/eth-phishing-detect#9172] opened 2022-10-31 16:59 UTC
https://zksync.crew3.xyz/ I am one of the community managers for zkSync and was the one who created the account with the Crew3 Platform. Please feel free to reach out with any questions

**Comment by 409H** [comment] 2022-11-07 21:23
Closing. Duplicate of in https://github.com/MetaMask/eth-phishing-detect/pull/9265

**Closed by 409H** 2022-11-07 21:23 UTC
Labels: duplicate, allowlist request
