### ISSUE TITLE
[Legitimate Site Blocked] mint.adrunner.io

### ISSUE THREAD

**Issue by omesy92** [MetaMask/eth-phishing-detect#6950] opened 2022-03-28 21:04 UTC
https://mint.adrunner.io/

This is not a scam.

Please remove the ban you have placed on this account as you are hindering a project we want to be a part of thanks to accusations from a sacked ex employee of the team who's out for revenge.

**Comment by devenblake** [comment] 2022-03-29 01:32
Duplicate of #6944.

**Closed by devenblake** 2022-03-29 01:32 UTC
Labels: duplicate, allowlist request
