### ISSUE TITLE
[Legitimate Site Blocked] form.jotform.com

### ISSUE THREAD

**Issue by GiorgioCC2021** [MetaMask/eth-phishing-detect#8150] opened 2022-08-11 13:16 UTC
https://form.jotform.com/220456030167649?preview=true&orientation=portrait&branding21=1

**Comment by 409H** [comment] 2022-11-07 22:15
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8142

**Closed by 409H** 2022-11-07 22:15 UTC
Labels: duplicate, allowlist request
