### ISSUE TITLE
about ethonline.io

### ISSUE THREAD

**Issue by blaup** [MetaMask/eth-phishing-detect#3309] opened 2019-09-08 16:06 UTC
There has been alot of people saying that ethonline.io and the sister site bthonline.io is scam is this true what are the users pay for and can any explain this to me ??? I has to know

**Comment by 409H** [comment] 2019-09-25 00:45
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/3326

**Closed by 409H** 2019-09-25 00:45 UTC
Labels: duplicate
