### ISSUE TITLE
What the hell is going on? How do I log out of MetaMask?

### ISSUE THREAD

**Issue by renelmiller0120** [MetaMask/eth-phishing-detect#2662] opened 2018-11-27 00:01 UTC
Empowr.com is not a malicious site and MetaMask has now blocked me from working in it? I need to get back into that site immediately. What the hell are they doing? From what I can tell, MetaMask has been having issues since the new updates? There is nothing wrong with Empowr.com and we all use Ethereum as a base to purchase tokens from Empowr.com

This needs to be fixed immediately please? How do I log out of MetaMask until you get it fixed? If I cannot use MetaMask to utilize my ethereum the way that I see fit than I don't want to use it at all.

There is nothing wrong with my password either.

**Comment by 409H** [comment] 2018-11-27 00:05
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2660

@renelmiller0120 you can bypass the MetaMask block by clicking the bypass link (underlined in black) 
![image](https://user-images.githubusercontent.com/2313704/49049737-2d4c3880-f1d8-11e8-875a-08bea1263bcd.png)

**Closed by 409H** 2018-11-27 00:05 UTC

**Comment by PERTHEKAT** [comment] 2019-01-21 22:18
YOU CAN GET YOUR ETH STOLEN BY EMPOOR ONLY. STAY AWAY FROM OR QUIT AS ME.
