### ISSUE TITLE
DailyDivs is NOT a phishing scam

### ISSUE THREAD

**Issue by Nereian** [MetaMask/eth-phishing-detect#2416] opened 2018-09-14 12:58 UTC
DailyDivs is not a phishing scam site. SHAME on you to make it so easy for any hater to incorrectly flag a site and ruin someone else's hard work. Get your act together.

**Comment by 409H** [comment] 2018-09-15 17:50
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2427

**Closed by 409H** 2018-09-15 17:50 UTC
