### ISSUE TITLE
[Legitimate Site Blocked] beacons.ai

### ISSUE THREAD

**Issue by ghost** [MetaMask/eth-phishing-detect#8921] opened 2022-10-17 11:42 UTC
https://beacons.ai/resistslavery is not a scam website, don't know why this was blocked/reported.

**Comment by 409H** [comment] 2022-11-07 21:35
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8894

**Closed by 409H** 2022-11-07 21:35 UTC
Labels: duplicate, allowlist request
