### ISSUE TITLE
[Legitimate Site Blocked] metabase.studio

### ISSUE THREAD

**Issue by genrebase** [MetaMask/eth-phishing-detect#6039] opened 2021-11-29 13:24 UTC
https://metabase.studio/ still not resolved, more money lost and none of it is our or any other domain name owners fault I see complaining on here. Shameful. This should be closed down and run by MetaMask and they should pay people rather than expect volunteers to do it and it should not be for anyone on this list being produced to do anything to have their domain name removed. 

This problem is created by this project and not the other way round.

**Comment by devenblake** [comment] 2021-11-29 15:46
Duplicate of #6005.

**Comment by devenblake** [comment] 2021-11-29 21:10
That's because the PR hasn't been merged yet. When it is, and after the caches clear, the site won't be flagged as potential phishing anymore.

**Comment by genrebase** [comment] 2021-11-30 08:51
so when is that going to be? Can you give us all an estimation on how long it takes to get any domain clear of this imposed warning that is nothing to do with the domain owners, is it 3 days, 5 days?

**Comment by devenblake** [comment] 2021-11-30 15:11
> Can you give us all an estimation on how long it takes to get any domain clear of this imposed warning that is nothing to do with the domain owners

No. I'm not a maintainer of this repository.

**Closed** 2021-11-30 17:37 UTC

**Comment by genrebase** [comment] 2021-11-30 19:20
Why has this been closed? The site is still blocked

**Comment by davidwgrossman** [comment] 2021-11-30 19:23
We have added the site to our allowlist internally. The changes will take 24 hours to propagate. If there are still issues then, feel free to follow up with us!!

Thanks :)
