### ISSUE TITLE
Metamask is falsely accusing genuine businesses and ignoring pull requests for months...

### ISSUE THREAD

**Issue by muthunagarajan1** [MetaMask/eth-phishing-detect#4381] opened 2020-11-06 03:51 UTC
Metamask is falsely accusing Genuine & Legitimate Businesses. It also fails to take corrective actions and is sitting for months on concerns raised.

The following are the links to issues & Pull requests raised to whitelist ducatus.com . These are open since 14th of August 2020.

https://github.com/MetaMask/eth-phishing-detect/pull/4276

https://github.com/MetaMask/eth-phishing-detect/issues/4244

https://github.com/MetaMask/eth-phishing-detect/issues/4105

Pull Requests after his have been checked and merged. 
Take responsible corrective actions.

**Comment by danfinlay** [comment] 2020-11-06 17:34
We're allocating extra effort to this backlog. We are not accusing anyone of anything, we are doing our best to detect things that might be malicious. Closing this issue since it's a duplicate of its linked issues.

**Closed by danfinlay** 2020-11-06 17:34 UTC
