### ISSUE TITLE
https://mint.adrunner.io/

### ISSUE THREAD

**Issue by Kivolov** [MetaMask/eth-phishing-detect#6985] opened 2022-03-29 08:29 UTC
https://mint.adrunner.io/

This website is legit for NFT. Kindly remove from the list. thank you.

**Comment by devenblake** [comment] 2022-03-29 19:27
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/6944.

**Closed by devenblake** 2022-03-29 19:27 UTC
Labels: duplicate, allowlist request
