### ISSUE TITLE
[Legitimate Site Blocked] mint.adrunner.io

### ISSUE THREAD

**Issue by jesusrulz24** [MetaMask/eth-phishing-detect#6968] opened 2022-03-28 22:40 UTC
https://mint.adrunner.io/ is a completely legitimate mint site that is being harassed by an ex-member of the team who seems to have a grudge and wants to destroy the project because they were kicked out for not doing their job. This site should not be blocked.

**Comment by devenblake** [comment] 2022-03-29 01:35
Duplicate of #6944.

**Closed by devenblake** 2022-03-29 01:35 UTC
Labels: duplicate, allowlist request
