### ISSUE TITLE
[Legitimate Site Blocked] shido.market

### ISSUE THREAD

**Issue by jasontuinstra90** [MetaMask/eth-phishing-detect#8943] opened 2022-10-17 20:02 UTC
https://shido.market/
There is no phishing on this site 
can the red flag please be removed
One of the best projects in the defi space that I have seen Dev always delivers promises
Cross chain wallet is on playstore and on ios test flight
Ignore the fud from the other projects that cant deliver anything and try to bring someone else down
Shido has some amazing partners and revolutionary utilities that havent been done on any dex
dex will be released by the end of november

**Comment by 409H** [comment] 2022-11-07 21:43
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8906

**Closed by 409H** 2022-11-07 21:43 UTC
Labels: duplicate, allowlist request
