### ISSUE TITLE
oqenseas.com

### ISSUE THREAD

**Issue by ryder23** [MetaMask/eth-phishing-detect#6073] opened 2021-12-03 03:09 UTC
Me and a friend are just trying to make a page for memes and NFT content. 

We aren't sure why it's block and would appreciate it if it could get unblocked. #6045

**Comment by devenblake** [comment] 2021-12-03 04:16
![Looks like this domain has not been registered yet: oqensea.com](https://user-images.githubusercontent.com/26193059/144544060-2bdc27d4-2436-4c6e-92e6-2bcdb23985e5.png)

In the original filed issue you mentioned \#6052 which is a duplicate of #6043, an issue filed by another user *prior* to its registration, so you should know that unregistered domains aren't allowlisted.

**Comment by ryder23** [comment] 2021-12-03 04:27
I’m sorry I misspelled the domain. It’s oqenseas.com

>

**Comment by devenblake** [comment] 2021-12-03 05:37
This is an obvious phishing domain.

**Closed** 2021-12-03 06:11 UTC
Labels: duplicate
