### ISSUE TITLE
[Legitimate Site Blocked] murakamiflowers.kaikaikiki.com

### ISSUE THREAD

**Issue by cryptogauge** [MetaMask/eth-phishing-detect#7294] opened 2022-05-02 10:40 UTC
https://murakamiflowers.kaikaikiki.com/

This is the genuine website for Takashi Murakami flower seeds
His social media links as follows: 
twitter: @takashipom
Instagram: https://www.instagram.com/takashipom/
Website: https://murakamiflowers.kaikaikiki.com/
NFT collection on Opensea: https://opensea.io/collection/murakami-flowers-seed

When you open the collection you can click on the website icon next to the watchlist and instagram icons.

**Comment by devenblake** [comment] 2022-05-05 22:52
Duplicate of #7260.

**Closed by devenblake** 2022-05-05 22:52 UTC
Labels: duplicate, allowlist request
