### ISSUE TITLE
[Legitimate Site Blocked] metamash.co

### ISSUE THREAD

**Issue by teamguhan** [MetaMask/eth-phishing-detect#6616] opened 2022-02-11 08:39 UTC
https://metamash.co/ Can someone tell me how I can resolve this. We are a private limited company and this issue is going far too long!! Deeply unsatisfied

**Comment by devenblake** [comment] 2022-03-01 04:20
Duplicate of #6487.

**Closed by devenblake** 2022-03-01 04:20 UTC
Labels: duplicate, allowlist request
