### ISSUE TITLE
[Legitimate Site Blocked] form.jotform.com

### ISSUE THREAD

**Issue by dgupright** [MetaMask/eth-phishing-detect#8153] opened 2022-08-11 14:17 UTC
Hi there -- 

We are a DAO, launching on August 24th. We are legitimate and the furthest from a phishing attempt. We are using jotform to collect information from interested individuals. 
All jotforms that we own are being affected by this error: https://metamask.github.io/phishing-warning/v1.1.0/#hostname=form.jotform.com&href=https%3A%2F%2Fform.jotform.com%2F221875788698179%3FisIframeEmbed%3D1

See:
https://cap3collective.io/apply-as-capital-provider/

https://form.jotform.com/221293603191147

**Comment by 409H** [comment] 2022-11-07 22:15
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8142

**Closed by 409H** 2022-11-07 22:15 UTC
Labels: duplicate, allowlist request
