### ISSUE TITLE
[Legitimate Site Blocked] www.pinksale.finance

### ISSUE THREAD

**Issue by oumghar1010** [MetaMask/eth-phishing-detect#6130] opened 2021-12-09 01:23 UTC
https://www.pinksale.finance/#/launchpads?chain=BSC this doesnt look like a scam million of dollars have been deposit and withdrawed from it for months if they would be scam people they could do it months ago

**Comment by devenblake** [comment] 2021-12-09 03:55
Duplicate of #6115.

**Closed** 2021-12-14 01:16 UTC
Labels: duplicate
