### ISSUE TITLE
[Legitimate Site Blocked] ltcminer.com

### ISSUE THREAD

**Issue by NamrataB9** [MetaMask/eth-phishing-detect#6564] opened 2022-02-03 10:42 UTC
![Ethereum phishing Detection](https://user-images.githubusercontent.com/98950493/152327343-7cc32793-87a7-4abc-a4e0-007f152de6b2.png)
https://ltcminer.com/

**Comment by devenblake** [comment] 2022-02-03 16:09
Duplicate of #4472.

**Closed by devenblake** 2022-02-03 16:09 UTC
Labels: duplicate, allowlist request
