### ISSUE TITLE
[Legitimate Site Blocked] foundation.app

### ISSUE THREAD

**Issue by chazzgold1** [MetaMask/eth-phishing-detect#8599] opened 2022-09-29 09:18 UTC
https://foundation.app/collection/100NFTs100days?sortOrder=DEFAULT

I think this is a glitch this is not a fishing site it's foundation of all places I really wish you guys would fix this cause it's screwing things up if anybody goes to my link tree and I missed in sales because they're scared to click on anything

**Comment by 409H** [comment] 2022-11-07 22:01
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8588

**Closed by 409H** 2022-11-07 22:01 UTC
Labels: duplicate, allowlist request
