### ISSUE TITLE
[Legitimate Site Blocked] app.forestry.io

### ISSUE THREAD

**Issue by orvn** [MetaMask/eth-phishing-detect#8817] opened 2022-10-12 17:42 UTC
The following domain is being flagged https://app.forestry.io, however it's legitimate and doesn't appear in [other trust and safety databases](https://transparencyreport.google.com/safe-browsing/search?url=app.forestry.io)?

Forestry is a popular CMS layer for static websites on Github or Bitbucket.

<img width="750" alt="metamast" src="https://user-images.githubusercontent.com/3689720/195411638-88708b0a-31d4-441b-a255-06ee4683f177.png">

<img width="750" alt="google" src="https://user-images.githubusercontent.com/3689720/195411668-f7b52593-e448-4e0d-94cb-a32980f66db7.png">

**Comment by 409H** [comment] 2022-11-07 21:52
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/9011

**Closed by 409H** 2022-11-07 21:52 UTC
Labels: duplicate, allowlist request

**Comment by orvn** [comment] 2022-11-07 23:59
This one is much more descriptive and older, so I'd say #9011 is actually the _duplicate of_ #8817, but sure.
