### ISSUE TITLE
[Legitimate Site Blocked] bakedbeans.io

### ISSUE THREAD

**Issue by mdixon888** [MetaMask/eth-phishing-detect#9083] opened 2022-10-26 06:14 UTC
https://bakedbeans.io/?ref=0xa9FfaBA9Cc51b7344BeF7d7abc394D516cCc4e86

This is a legitimate site. I've been using it for 6 months! As it's been blocked I cannot access my coins, which is very annoying. Please unblock!

**Comment by 409H** [comment] 2022-11-07 23:18
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/9062

**Closed by 409H** 2022-11-07 23:18 UTC
Labels: duplicate, allowlist request
