### ISSUE TITLE
[Legitimate Site Blocked] metadesk.run

### ISSUE THREAD

**Issue by EpicTestUser** [MetaMask/eth-phishing-detect#6608] opened 2022-02-10 04:48 UTC
https://metadesk.run/

I'm using this website to do my course on Unreal Engine. It is a legitimate site providing the Unreal directly to browser. Please unblock this website,

**Comment by devenblake** [comment] 2022-02-22 04:34
Duplicate of #6606.

**Closed by devenblake** 2022-02-22 04:34 UTC
Labels: duplicate, allowlist request
