### ISSUE TITLE
https://cryptoknitties.io

### ISSUE THREAD

**Issue by wdmason** [MetaMask/eth-phishing-detect#5322] opened 2021-08-25 11:50 UTC
Cryptoknitties.io is a project based on the Cardano blockchain. It has no connection whatsoever to Metamask, Ethereum, or the Cryptokitties project.

**Comment by davidwgrossman** [comment] 2021-08-30 19:40
duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/5339

**Closed by davidwgrossman** 2021-08-30 19:40 UTC
