### ISSUE TITLE
[Legitimate Site Blocked] www.ruckus.studio

### ISSUE THREAD

**Issue by Rickster411** [MetaMask/eth-phishing-detect#6523] opened 2022-01-30 23:11 UTC
https://www.ruckus.studio/

**Comment by Rickster411** [comment] 2022-01-30 23:12
![unnamed](https://user-images.githubusercontent.com/97869481/151721901-d49c176b-e8f8-40a5-b37f-16048579de34.png)

**Comment by devenblake** [comment] 2022-01-31 01:19
Duplicate of #6425.

**Closed by devenblake** 2022-01-31 01:19 UTC
Labels: duplicate, allowlist request

**Comment by Rickster411** [comment] 2022-01-31 01:22
This still is yet to be rectified.
