### ISSUE TITLE
New Pyramid scheme

### ISSUE THREAD

**Issue by romkapomka** [MetaMask/eth-phishing-detect#2340] opened 2018-09-06 06:44 UTC
Website https://333eth.io . Please add to blacklist

**Comment by EtherBomb** [comment] 2018-09-11 19:50
NOT SCAM!!!
The project 333eth.io is not a Scam it is a mistake!!! Thank U
It's competitors trying to do badly!!

**Comment by sashok76rus** [comment] 2018-09-11 19:50
Сайт отличный. Все стабильно выплачивает! !!!!!!!
Закрывать его не за что.

**Comment by colorist71** [comment] 2018-09-11 19:52
Competitors site deliberately slander .Understand and restore justice

**Comment by koka73** [comment] 2018-09-11 19:53
333ETH.IO - IS NOT A SCAM AND NOT A FISHING SITE.
This is the machinations of competitors. Unlock this site, please

**Comment by Konstantin48** [comment] 2018-09-11 19:55
333eth.io is not scam!!! This is a crypto game and people participate in it only on their own initiative!

**Comment by SergeyTit** [comment] 2018-09-11 19:55
The project regularly pays all the promised payments. It's a shame when a complaint of one offended person can spoil the mood of a large community. Please remove the site 333eth.io from the blacklist. Thx.

**Comment by GooddayAlex** [comment] 2018-09-11 20:03
Good site ! No scam... Хороший сайт и проект ! Все работает !

**Comment by igor51rus** [comment] 2018-09-11 20:37
I ask you to remove the site 333eth.io from the blacklist. The site 333eth.io is entered by mistake in the black list MetaMask. Dear support, I am an investor of this site. Unblock the site 333eth.io and put everything back in place. The site 333eth.io is on the blacklist erroneously due to competitors.

**Comment by Barloch77** [comment] 2018-09-11 20:44
Immediately unlock the site https: //www.333eth.io! You interfere with the work of a good project.

**Comment by TeamXXI** [comment] 2018-09-11 20:46
This is not a scam! The contract regularly pays all its investors, please remove the restriction metamask on the site 333eth.io
It was added by mistake because of the competitive environment.
Thank you!

**Comment by 409H** [comment] 2018-09-12 01:03
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2374

**Closed by 409H** 2018-09-12 01:03 UTC
