### ISSUE TITLE
Resolved DNS hack

### ISSUE THREAD

**Issue by parlex** [MetaMask/eth-phishing-detect#4822] opened 2021-03-16 14:13 UTC
Seems like pancakeswap was added to the phising list after the DNS attack was resolved and not when it was happening, a bit late and suspicious to add them after the hack was resolved.

**Comment by 409H** [comment] 2022-11-07 22:40
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/4803

**Closed by 409H** 2022-11-07 22:40 UTC
Labels: duplicate, allowlist request
