### ISSUE TITLE
wrong Ethereum Phishing Detection

### ISSUE THREAD

**Issue by sccrypto** [MetaMask/eth-phishing-detect#3009] opened 2019-04-08 00:12 UTC
hello,

i recently bought this domain, and i have nothing to do with eth phishing.
i ask for you to take this my domain from your warning list.
im building the website and its going to be for crypto education.

will wait for a reply, thank you

**Comment by 409H** [comment] 2019-04-08 11:59
What domain?

**Comment by sccrypto** [comment] 2019-04-08 12:02
hello,

 the domain sccrypto.net its marked as phishing, and i have nothing with
that, i bought this new domain some days ago.

thank you

Best regards
SC

**Comment by 409H** [comment] 2019-04-14 22:34
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/3002

**Closed by 409H** 2019-04-14 22:34 UTC
Labels: needs-more-information, whitelist request
