### ISSUE TITLE
I need daily DIvs

### ISSUE THREAD

**Issue by jakelespo** [MetaMask/eth-phishing-detect#2458] opened 2018-09-18 22:09 UTC
Why is it listed as a threat?

**Comment by Mavrmich** [comment] 2018-09-19 03:58
Becouse his smartcontract untested and has holes!

**Comment by jakelespo** [comment] 2018-09-19 14:48
So you’ve locked me out of my account? My amount is only growing.....I at
least want to cash out now I’ve only made profits on this site. Check the
numbers....it was 22 cents when I joined it’s now doubled that almost at 50
cents per.

**Comment by 409H** [comment] 2018-09-19 20:43
@jakelespo please see my comment here: https://github.com/MetaMask/eth-phishing-detect/issues/2427#issuecomment-422948400

Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2427

**Closed by 409H** 2018-09-19 20:43 UTC
