### ISSUE TITLE
wrong flagging

### ISSUE THREAD

**Issue by Morcrypto** [MetaMask/eth-phishing-detect#3312] opened 2019-09-10 03:37 UTC
Our website, morcrypto.net has been illegitimately flagged. This can affect our project, no instruction or warning was given.

**Comment by 409H** [comment] 2019-09-25 00:21
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/3314

**Closed by 409H** 2019-09-25 00:21 UTC
