### ISSUE TITLE
metamask domain issue  /https:// empowr.com

### ISSUE THREAD

**Issue by phey1975** [MetaMask/eth-phishing-detect#2861] opened 2019-02-01 11:49 UTC
hello team 

have a great day..

hello everyone  ive got issue on my empowr.com website got phishing scam o my metamask warning list.either its my fault regarding of connecting my metamask with wrong wallet adress.
please fix it.

thank you

**Comment by xrn** [comment] 2020-11-16 09:34
Closing. Duplicate of #2663

**Closed by xrn** 2020-11-16 09:34 UTC
