### ISSUE TITLE
[Legitimate Site Blocked] gaiaworld.com

### ISSUE THREAD

**Issue by Junaid1240651** [MetaMask/eth-phishing-detect#5822] opened 2021-11-03 17:52 UTC
https://gaiaworld.com/ this domain has been flagged incorrectly.

**Comment by Junaid1240651** [comment] 2021-11-03 17:53
https://gaiaworld.com/ this domain has been flagged incorrectly.

**Comment by devenblake** [comment] 2021-11-03 21:49
Duplicate of #5768.

**Closed** 2021-12-03 06:16 UTC
Labels: duplicate
