### ISSUE TITLE
[Legitimate Site Blocked] darkmeta.xyz

### ISSUE THREAD

**Issue by joelwp4** [MetaMask/eth-phishing-detect#7052] opened 2022-04-04 08:51 UTC
https://darkmeta.xyz/ 

This site is meant to introduce users to our NFT studio, there is no selling or phishing for user's information. 

Please have a look at this issue, thank you.

**Comment by devenblake** [comment] 2022-04-08 02:29
Duplicate of #6941.

**Closed by devenblake** 2022-04-08 02:29 UTC
Labels: duplicate, allowlist request
