### ISSUE TITLE
[Legitimate Site Blocked] www.metaosk.com

### ISSUE THREAD

**Issue by Hickshu** [MetaMask/eth-phishing-detect#7171] opened 2022-04-20 06:33 UTC
https://www.metaosk.com/

Devenblake Hello.
Metaosk.com is a healthy and legally certified official website, please help us so that our domain can be unblocked.

Our official website is legal and has SSL certification, but now whenever you start Metaosk.com from your computer, you will be warned that it is a phishing website, which causes many users to distrust us, so we hope that our domain can be officially whitelisted
![1649823757949](https://user-images.githubusercontent.com/103487348/164165227-d6cd9c27-297e-4347-b80c-ecf02040239f.jpg)
.

**Comment by devenblake** [comment] 2022-05-10 00:30
Duplicate of #7122.

**Closed by devenblake** 2022-05-10 00:30 UTC
Labels: duplicate, allowlist request
