### ISSUE TITLE
gocrypto.com 

### ISSUE THREAD

**Issue by nlandeker** [MetaMask/eth-phishing-detect#3196] opened 2019-07-29 14:03 UTC
Dear Sir/Madam,

this website is still marked as flagged. Could you please remove the flag or explain why you cannot do this.

Url scan: https://urlscan.io/result/7d613fa2-126d-46bb-a357-09b2626b5a10

Thank you very much.

Regards

**Comment by 409H** [comment] 2019-10-31 22:50
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/3162 - has been whitelisted

**Closed by 409H** 2019-10-31 22:50 UTC
Labels: duplicate, whitelist request

**Comment by AntonGEM** [comment] 2021-01-07 14:16
Helo. Gocrypto.com is again false listed I think. Could you please delist it? Thanks

https://urlscan.io/result/7d613fa2-126d-46bb-a357-09b2626b5a10
