### ISSUE TITLE
[Legitimate Site Blocked] infinity.xyz

### ISSUE THREAD

**Issue by SvenRoberts** [MetaMask/eth-phishing-detect#5734] opened 2021-10-29 17:22 UTC
https://infinity.xyz/

I can access it with another browser.
It seems a really big token.

Kind regards,

**Comment by devenblake** [comment] 2021-10-30 05:32
Looks like this was allowlisted in #5563 (and this issue is a duplicate of #5562). Can you confirm everything with regard to the extension is up to date on your system?

**Closed** 2021-12-03 06:15 UTC
Labels: duplicate
