### ISSUE TITLE
[Legitimate Site Blocked] form.jotform.com

### ISSUE THREAD

**Issue by NFTAnnouncers** [MetaMask/eth-phishing-detect#8157] opened 2022-08-11 15:34 UTC
https://form.jotform.com/222146738472156

It looks like you've blocked JotForm. JotForm is a legitimate website used by hundreds of thousands of businesses to create fillable forms. To my knowledge, the site does not connect to MetaMask in any way, it's just a fillable form that allows users to input their information (name, email, response to questions, etc.).

**Comment by 409H** [comment] 2022-11-07 22:15
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8142

**Closed by 409H** 2022-11-07 22:15 UTC
Labels: duplicate, allowlist request
