### ISSUE TITLE
The site is not phishing is a mistake

### ISSUE THREAD

**Issue by colorist71** [MetaMask/eth-phishing-detect#2372] opened 2018-09-11 17:47 UTC
The website 333eth.io is not a Scam it is a mistake thank you

**Comment by net968** [comment] 2018-09-11 19:41
333ETH.IO - IS NOT A SCAM AND NOT A FISHING SITE.
This is the machinations of competitors. Unlock this site, please

**Comment by 409H** [comment] 2018-09-12 01:02
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2374

**Closed by 409H** 2018-09-12 01:02 UTC
