### ISSUE TITLE
[Legitimate Site Blocked] adfinity.pro

### ISSUE THREAD

**Issue by Oleg408** [MetaMask/eth-phishing-detect#7329] opened 2022-05-05 10:57 UTC
Hello.

Domain [adfinity.pro](https://adfinity.pro/) is on the warning list. This domain is incorrectly flagged.

Adfinity monetizes websites and has nothing to do with cryptocurrency. How can this error be corrected?

If you need more information, please write to the admin@adfinity.pro or support@adfinity.pro

**Comment by devenblake** [comment] 2022-05-06 00:53
Duplicate of #5483.

**Closed by devenblake** 2022-05-06 00:53 UTC
Labels: duplicate, allowlist request
