### ISSUE TITLE
Allow empowr.com, is safe

### ISSUE THREAD

**Issue by pples** [MetaMask/eth-phishing-detect#3364] opened 2019-09-26 13:30 UTC
Hello Team,

Kindly allow empowr.com to freely browse on my device.  The site is secure and safe for me.

Thank you.

Daniel.

**Comment by KryptoKrat** [comment] 2019-12-31 05:15
Daniel is correct. I've been with Empowr for 7years even back when it was Fanbox. And they are the first to have a patent for cyrpto. They are legit.

**Comment by xrn** [comment] 2020-11-16 09:34
Closing. Duplicate of #2663

**Closed by xrn** 2020-11-16 09:34 UTC
