### ISSUE TITLE
[Legitimate Site Blocked] faucet.v2.testnet.pulsechain.com

### ISSUE THREAD

**Issue by CoZaFrenzy** [MetaMask/eth-phishing-detect#6804] opened 2022-03-04 06:44 UTC
https://faucet.v2.testnet.pulsechain.com/

Yo, what is going on? Open it back. Open now. Please

**Comment by devenblake** [comment] 2022-03-05 01:45
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/6771.

**Closed by devenblake** 2022-03-05 01:45 UTC
Labels: duplicate, allowlist request
