### ISSUE TITLE
[Legitimate Site Blocked] metamarc.io

### ISSUE THREAD

**Issue by stevesaw** [MetaMask/eth-phishing-detect#5969] opened 2021-11-20 08:48 UTC
https://metamarc.io/
This is a NFT platform project, please remove it from the warning list. Thank you.

**Comment by stevesaw** [comment] 2021-11-20 08:57
#5970

**Comment by devenblake** [comment] 2021-11-23 13:57
Duplicate of solved issue.

**Closed** 2021-12-03 06:11 UTC
Labels: duplicate
