### ISSUE TITLE
[Legitimate Site Blocked] murakamiflowers.kaikaikiki.com

### ISSUE THREAD

**Issue by Mizonal** [MetaMask/eth-phishing-detect#7275] opened 2022-04-30 05:35 UTC
https://murakamiflowers.kaikaikiki.com/

This site is true site of Murakami.Flowers.
please check Takashi's twitter or instagram.
https://www.instagram.com/takashipom/
https://twitter.com/takashipom

**Comment by nsfx84** [comment] 2022-05-01 22:01
Yes this is a legit site. Not sure why it's been blacklisted all of a sudden.

**Comment by Tasarvo** [comment] 2022-05-01 22:03
Please please unblock this, this is the OFFICIAL site, you can see its official from the official Opensea account, the reveal is happening soon i think, Takashi Murakami has his exhibition happening on the 11th, please expediate this!  The reason there are tons of fake sites is because of the HUG following Takashi Murakami has internationally, the largest artist launching his own priject, the previous being the deisgn of CLone X that Nike purchased!

**Comment by TheF604** [comment] 2022-05-02 05:31
Chiming in my +1
This is the legit site and needs to be unblocked.

**Comment by devenblake** [comment] 2022-05-05 22:52
Duplicate of #7260.

**Closed by devenblake** 2022-05-05 22:52 UTC
Labels: duplicate, allowlist request
