### ISSUE TITLE
[Legitimate Site Blocked] beacons.ai

### ISSUE THREAD

**Issue by MiChaelinzo** [MetaMask/eth-phishing-detect#8935] opened 2022-10-17 16:21 UTC
https://beacons.ai/

This website legitimate a link and website builder tool. It is similar to linktr.ee except it got more feature and an internal AI for pro/paid users etc. got alot more benefits.

**Comment by 409H** [comment] 2022-11-07 21:35
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8894

**Closed by 409H** 2022-11-07 21:35 UTC
Labels: duplicate, allowlist request
