### ISSUE TITLE
[Legitimate Site Blocked] www.pinksale.finance

### ISSUE THREAD

**Issue by russiancryptomillionaire** [MetaMask/eth-phishing-detect#6123] opened 2021-12-08 23:09 UTC
You made a mistake and blocked a legitimate DeFi launchpad, please fix it ASAP! 

https://www.pinksale.finance/#/launchpad/0xC153c17F75122628E5F629edaA9B1D30f6b98793?chain=BSC

**Comment by devenblake** [comment] 2021-12-09 03:55
Duplicate of #6115.

**Closed** 2021-12-14 01:17 UTC
Labels: duplicate
