### ISSUE TITLE
[Legitimate Site Blocked] www.empowr.com

### ISSUE THREAD

**Issue by sksaha61** [MetaMask/eth-phishing-detect#6278] opened 2021-12-27 10:27 UTC
http://www.empowr.com/socnet/EmailStat.aspx?lit=5&me=otUh9vs.UpO4Fqj8rQcy8MUvC.M6npeK3GYqi41Q5Z3jDTk5S4B0ZKcnNhIdVe13CH3WdD.czACokAx4BmQUWssyky.GxY9Fm3mJKde1j7tQL2k4xh9h6WBaCUQrgxLw.d0bklUsSCe2XWV8f4bDV9kbcz1Qx8X-I4nxoF1nsbqup9IMSF567W5pxJk5iK4P&fan=Y8Ca43P1qAMdoWNxwn%2fBbA%3d%3d&opg=http%3a%2f%2fprofile.empowr.com%2fProfile%2fNewCustomProfile.aspx%3fu%3d323b3eedda094afc94bd7518cadbd6b8&vet=684&dt=060119&mlid=764734200&tmpID=3212&linkname=ActorProfile&emailNum=1&eaid=yM9KXk6njAlsh2TqFPu%2b7w%3d%3d&rt=12

**Comment by devenblake** [comment] 2021-12-27 22:13
Duplicate of #2663.

**Closed** 2022-01-12 23:09 UTC
