### ISSUE TITLE
[Legitimate Site Blocked] mint.adrunner.io

### ISSUE THREAD

**Issue by MaegaBerry23** [MetaMask/eth-phishing-detect#6947] opened 2022-03-28 21:01 UTC
https://mint.adrunner.io/
the owner is Doxxed and been in the crypto space community for years and wants a successful crypto project

**Comment by devenblake** [comment] 2022-03-29 01:32
Duplicate of #6944.

**Closed by devenblake** 2022-03-29 01:32 UTC
Labels: duplicate, allowlist request
