### ISSUE TITLE
[Legitimate Site Blocked] metabase.studio

### ISSUE THREAD

**Issue by genrebase** [MetaMask/eth-phishing-detect#6017] opened 2021-11-26 08:41 UTC
https://metabase.studio/ is legitimate

**Comment by devenblake** [comment] 2021-11-26 22:17
Duplicate of #6005.

**Comment by genrebase** [comment] 2021-11-27 08:19
This is not a duplicate, issues has still not been resolved.

**Closed** 2021-11-30 17:37 UTC
