### ISSUE TITLE
[Legitimate Site Blocked] metamash.co

### ISSUE THREAD

**Issue by teamguhan** [MetaMask/eth-phishing-detect#6599] opened 2022-02-08 14:51 UTC
**https://metamash.co/

Hi. We are a digital agency. This is happening too often. PLEASE, the plugin is impacting our brand name. I hope we can resolve this. 

Please contact us at partner@metamash.co to solve this or if you need any further licenses or documents to verify.

Thanks a ton,
Guhan**

**Comment by devenblake** [comment] 2022-03-01 04:21
Duplicate of #6487.

**Closed by devenblake** 2022-03-01 04:21 UTC
Labels: duplicate, allowlist request
