### ISSUE TITLE
[Legitimate Site Blocked] www.pinksale.finance

### ISSUE THREAD

**Issue by shingonoide** [MetaMask/eth-phishing-detect#6118] opened 2021-12-08 22:17 UTC
https://www.pinksale.finance/#/launchpad/0x07C013515a221C217974804A5D6ef19176486c0a?chain=BSC

**Comment by devenblake** [comment] 2021-12-09 03:54
Duplicate of #6115.

**Closed** 2021-12-14 01:17 UTC
Labels: duplicate
