### ISSUE TITLE
[Legitimate Site Blocked] murakamiflowers.kaikaikiki.com

### ISSUE THREAD

**Issue by on1879** [MetaMask/eth-phishing-detect#7288] opened 2022-05-02 02:15 UTC
https://murakamiflowers.kaikaikiki.com/

This is the offical site for Takashi Murakami's NFT launch.

**Comment by devenblake** [comment] 2022-05-05 22:52
Duplicate of #7260.

**Closed by devenblake** 2022-05-05 22:52 UTC
Labels: duplicate, allowlist request
