### ISSUE TITLE
Matamask blocking empowr

### ISSUE THREAD

**Issue by nitishkmr9** [MetaMask/eth-phishing-detect#2671] opened 2018-11-28 20:46 UTC
The software under maintenance due to some of diagonal overlapping of files like information got to be shared together meta mask and empower. the software may be get conjugating to each other .i m using empowr since nine months or it is trust worthy.there is some kind of update going on. software taking time for update soon we are able to work on empowr as we work before.I m request the restrictions lifted or we can work on our platform thank you

**Comment by 409H** [comment] 2018-11-28 23:17
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2663

**Closed by 409H** 2018-11-28 23:17 UTC

**Comment by sajawal882** [comment] 2018-11-30 09:00
hi i`ve been on empowr plateform and i never saw them doing any phishing activity

**Comment by valentinadie** [comment] 2018-12-04 21:13
Hi, hi I've been on empowr platform and I never saw them doing any phishing activity

**Comment by doug9694** [comment] 2019-01-10 01:03
I want to see the proof of the accusation. People say a phishing attempt was put out by empowr.  I saw one but it was not  an empowr site.  It ain't "phishing because empowr isn't pretending to be itself! Even if they asked for private key is it illegal? Being stupid is not illegal . Too bad it isn't ! Then y could definitely press charges on their adnin. then!

**Comment by doug9694** [comment] 2019-01-21 17:10
Here are a couple other issues y can block them on. 
1, Washing: The act of driving up volume for their benefit.
2. Pump: drive up the price via inside trading and/or hype
3. Getting empowr citizens to pay $1 fee on top of blockchain fees to have EMPR's sent to their scam 
  site then converted to new EMPRO's. Then back to wally and back to DDEX. What about those that have the coins and not in empowr? Isn't it required empowr to convert the coins where ever they are for free?  ref:  their empowr hour live 032 https://www.youtube.com/watch?v=49vFIJPuY34
