### ISSUE TITLE
URGENT [Legitimate Site Blocked] altus.digital 

### ISSUE THREAD

**Issue by bradsapkota** [MetaMask/eth-phishing-detect#6324] opened 2022-01-03 23:14 UTC
This site [http://altus.digital/] doesn't offer any crypto services and has been flagged as a malicious site. Please whitelist ASAP

**Comment by devenblake** [comment] 2022-01-03 23:16
Duplicate of #6256.

**Closed** 2022-01-13 05:31 UTC
