### ISSUE TITLE
[Legitimate Site Blocked] zksync.crew3.xyz

### ISSUE THREAD

**Issue by VitasTran** [MetaMask/eth-phishing-detect#9160] opened 2022-10-31 13:02 UTC
https://zksync.crew3.xyz/questboard/2d076d89-dea7-4507-9439-d1f8da575439

Dear Metamask,
pls check this website. why it became scame alert?

**Comment by 409H** [comment] 2022-11-07 21:24
Closing. Duplicate of in https://github.com/MetaMask/eth-phishing-detect/pull/9265

**Closed by 409H** 2022-11-07 21:24 UTC
Labels: duplicate, allowlist request
