### ISSUE TITLE
[Legitimate Site Blocked] foundation.app

### ISSUE THREAD

**Issue by solarbroccoli** [MetaMask/eth-phishing-detect#8619] opened 2022-09-29 17:15 UTC
https://foundation.app/0xC91b4fC395BeD97Ab058288466b1FD29eD77A703

**Comment by 409H** [comment] 2022-11-07 21:59
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8588

**Closed by 409H** 2022-11-07 21:59 UTC
Labels: allowlist request
