### ISSUE TITLE
[Legitimate Site Blocked] metamars.digital

### ISSUE THREAD

**Issue by Itneverensz** [MetaMask/eth-phishing-detect#5867] opened 2021-11-08 03:03 UTC
https://metamars.digital/

**Comment by Itneverensz** [comment] 2021-11-08 03:08
Hey this account is for our legitimate project Meta Mars where we are building a Metaverse on Mars. I'm hoping we can fix this as fast as possible. We are a Solana based NFT project. Thank you! We are launching very soon here

**Comment by davidwgrossman** [comment] 2021-11-08 15:24
Could you put up a PR in [this format](https://github.com/MetaMask/eth-phishing-detect/pull/5860)? Ping me in the PR and I'll approve it.

**Comment by devenblake** [comment] 2021-11-08 19:44
Duplicate of #5864.

**Comment by Itneverensz** [comment] 2021-11-08 20:02
What is a PR?

T. Austin Ensz
Sales Manager
Vivint Smart Home
***@***.***
1-817-366-6826
Vivint.com
________________________________

**Comment by devenblake** [comment] 2021-11-08 22:01
A PR is a pull request - it's GitHub's method of requesting code be contributed into a git repository from a modified branch. Generally you would fork the code on GitHub, clone the repository to your workstation, branch `master`, commit the change, and then open a PR like that, but what I usually go is:
- click [config.json](https://github.com/MetaMask/eth-phishing-detect/blob/master/src/config.json)
- click the pencil icon in the top right corner of the file
- scroll down to `"allowlist": [` within the file
- add a new entry like `"metamars.digital",`
- title your commit and then press the green commit button
- follow through the interface to file a PR

**Closed** 2021-12-03 06:11 UTC
Labels: duplicate
