### ISSUE TITLE
Empowr

### ISSUE THREAD

**Issue by bigian1234** [MetaMask/eth-phishing-detect#2975] opened 2019-03-20 01:47 UTC
I've been using Empowr for 8 months now and have no problems with it yet Metamask has listed it as an endangered phishing site!

Regards,

Ian

**Comment by 409H** [comment] 2019-04-14 22:32
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2663

**Closed by 409H** 2019-04-14 22:32 UTC
