### ISSUE TITLE
[Legitimate Site Blocked] mint.adrunner.io

### ISSUE THREAD

**Issue by AdrianRene17** [MetaMask/eth-phishing-detect#6977] opened 2022-03-29 03:52 UTC
https://mint.adrunner.io/
This is a ticket to remove this page from the blacklist

**Comment by devenblake** [comment] 2022-03-29 04:12
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/6944.

**Closed by devenblake** 2022-03-29 04:12 UTC
Labels: duplicate, allowlist request
