### ISSUE TITLE
Masknet.net is still blocked after weeks of waiting

### ISSUE THREAD

**Issue by alla0242** [MetaMask/eth-phishing-detect#6302] opened 2021-12-31 12:19 UTC
Hi, I posted a ticket a few weeks ago now and I haven't gotten a response back. My URL for my NFT project is still blocked so I'm hoping that I might be able to get a response back this time.

**Comment by devenblake** [comment] 2022-01-04 15:06
Duplicate of #6164.

**Closed** 2022-01-13 05:31 UTC
