### ISSUE TITLE
[Legitimate Site Blocked] www.avatrade.com

### ISSUE THREAD

**Issue by sheldonbrand** [MetaMask/eth-phishing-detect#8282] opened 2022-08-24 11:09 UTC
Dear GitHub team,

The website www.avatrade.com is a legitimate trading website of a known trading company - AvaTrade Ltd.
I would like to understand why this was marked as a phishing website while it is **NOT** on the [CryptoScamDB](https://cryptoscamdb.org/search).
The block page I get when trying to browse to avatrade.com indicates that this site is marked there as a phishing site, however, when looking it up there, it can't be found (see screenshot) 

please remove this site from your Scam DB - it is not fraudulent!
https://www.avatrade.com/

thank you.
![MetaMask avatrade com blocked](https://user-images.githubusercontent.com/111975680/186398119-68feb654-c5fe-4e2b-85aa-4de09d2c27aa.png)

**Comment by 409H** [comment] 2022-10-03 10:30
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8654

**Closed by 409H** 2022-10-03 10:30 UTC
Labels: duplicate, allowlist request
