### ISSUE TITLE
[Legitimate Site Blocked] app.cryptoblades.io

### ISSUE THREAD

**Issue by emerzonlouie** [MetaMask/eth-phishing-detect#7018] opened 2022-03-31 06:55 UTC
https://app.cryptoblades.io/#/ 

link is not compromised please allow metamask

**Comment by devenblake** [comment] 2022-04-08 02:42
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/7010.

**Closed by devenblake** 2022-04-08 02:42 UTC
Labels: duplicate, allowlist request
