### ISSUE TITLE
pancake swap

### ISSUE THREAD

**Issue by Sadevi** [MetaMask/eth-phishing-detect#4855] opened 2021-03-17 02:33 UTC
The phishing is already solved

**Comment by DarrenAlex** [comment] 2021-03-17 02:35
The code has been changed. Please wait for your extension to be updated.

**Comment by 409H** [comment] 2022-11-07 22:36
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/4803

**Closed by 409H** 2022-11-07 22:36 UTC
Labels: duplicate, allowlist request
