### ISSUE TITLE
[Legitimate Site Blocked] http://www.cosmosdataservices.com/

### ISSUE THREAD

**Issue by danial-amin** [MetaMask/eth-phishing-detect#6823] opened 2022-03-08 16:29 UTC
http://www.im-creator.com/free/cosmosdata/cosmos

**Comment by devenblake** [comment] 2022-04-08 00:50
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/6295.

**Closed by devenblake** 2022-04-08 00:50 UTC
Labels: duplicate, allowlist request
