### ISSUE TITLE
[Legitimate Site Blocked] nfinite.live

### ISSUE THREAD

**Issue by jonatag2** [MetaMask/eth-phishing-detect#6671] opened 2022-02-17 03:43 UTC
https://nfinite.live/?__cf_chl_rt_tk=SKp8Nhps8vRCPE8yFzm0QxxEvBtCZGVLhF88Zjf0VPA-1645069382-0-gaNycGzNBv0

**Comment by devenblake** [comment] 2022-02-22 04:32
Duplicate of #6670.

**Closed by devenblake** 2022-02-22 04:32 UTC
Labels: duplicate, allowlist request
