### ISSUE TITLE
[Legitimate Site Blocked] pulsechain.com

### ISSUE THREAD

**Issue by bizzyman7** [MetaMask/eth-phishing-detect#6811] opened 2022-03-04 16:37 UTC
https://pulsechain.com/

This is a legitimate site not sure why it's blocked...

**Comment by devenblake** [comment] 2022-03-05 01:46
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/6771.

**Closed by devenblake** 2022-03-05 01:46 UTC
Labels: duplicate, allowlist request
