### ISSUE TITLE
[Legitimate Site Blocked] wallet.elrond.com

### ISSUE THREAD

**Issue by EdwardTarantulo** [MetaMask/eth-phishing-detect#8885] opened 2022-10-16 21:12 UTC
https://wallet.elrond.com/

Is a legitimate Elrond blockchain official wallet https://elrond.com/.

This should not be blocked.

**Comment by 409H** [comment] 2022-10-17 14:27
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8899

**Closed by 409H** 2022-10-17 14:27 UTC
Labels: duplicate, allowlist request
