### ISSUE TITLE
[Legitimate Site Blocked] opensea.institute

### ISSUE THREAD

**Issue by ljoseph1987** [MetaMask/eth-phishing-detect#5901] opened 2021-11-11 13:53 UTC
https://opensea.institute/about/

I own this website. I am a Psychiatrist and this is the site for my practice. Can you please remove from the MetaMask Domain warning list? I can provide information to verify my identity and authenticity of my practice. Can someone please help?

**Comment by devenblake** [comment] 2021-11-12 00:48
Duplicate of #5898.

**Closed** 2021-11-13 01:58 UTC
