### ISSUE TITLE
[Legitimate Site Blocked] officialnft.xyz

### ISSUE THREAD

**Issue by CynthiaStnkmp** [MetaMask/eth-phishing-detect#7053] opened 2022-04-04 10:49 UTC
https://officialnft.xyz/

Has a really ugly warning and I'm hoping there's a way for them to get help to resolve this as it's a great platform.

Sincerely
Cynthia Steenkamp

**Comment by pushbetacraft** [comment] 2022-04-04 18:56
@AlexHerman1 @409H Any chance you can assist us with this?

**Comment by devenblake** [comment] 2022-04-05 04:27
Duplicate of #6938.

**Closed by devenblake** 2022-04-05 04:27 UTC
Labels: duplicate, allowlist request
