### ISSUE TITLE
My domain is currently blocked and marked as Phishing when Metamask is running...

### ISSUE THREAD

**Issue by adheretoself** [MetaMask/eth-phishing-detect#4601] opened 2021-01-13 10:15 UTC
My website is https://dfinity.cool
This is a forum. You can open my website, there is no fraud information! 
https://metamask.github.io/eth-phishing-detect/ returned "This domain was blocked for its similarity to dfinity.org, a historical
phishing target."

**Comment by devenblake** [comment] 2022-01-11 15:40
Duplicate of #4570.

**Closed** 2022-01-13 01:38 UTC
Labels: duplicate
