### ISSUE TITLE
[Legitimate Site Blocked] www.pinksale.finance

### ISSUE THREAD

**Issue by Diablox99** [MetaMask/eth-phishing-detect#6129] opened 2021-12-09 01:16 UTC
https://www.pinksale.finance/#/launchpad/0xA34f646310D7202E76E2035a2b2c7BBf5DD7eA67?chain=BSC I think this is a big mistake. because this project is good and has the potential to be big. there is no element of fraud. I hope you return it soon.

**Comment by devenblake** [comment] 2021-12-09 03:55
Duplicate of #6115.

**Closed** 2021-12-14 01:17 UTC
Labels: duplicate
