### ISSUE TITLE
I believe pancakeswap.finance has been fixed, but it is still displaying a warning in the chrome metamask extension

### ISSUE THREAD

**Issue by LtSnakePlissken** [MetaMask/eth-phishing-detect#4824] opened 2021-03-16 14:47 UTC

**Comment by ashtonbannister** [comment] 2021-03-16 16:06
Pancakeswap DNS Hijack was fixed more than 24 hours ago. The warning is unnecessary and was far too late.

**Comment by 409H** [comment] 2022-11-07 22:42
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/4803

**Closed by 409H** 2022-11-07 22:42 UTC
Labels: duplicate, allowlist request
