### ISSUE TITLE
[Legitimate Site Blocked] form.jotform.com

### ISSUE THREAD

**Issue by mstudersandiego** [MetaMask/eth-phishing-detect#8171] opened 2022-08-11 19:07 UTC
https://form.jotform.com/201165193762050?isIframeEmbed=1

Hi there, we're having legitimate jotforms on our website being blocked for some reason...we are a legitimate business and would like this to be not marked as phishing or anything else. Thanks!

**Comment by 409H** [comment] 2022-11-07 22:13
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8142

**Closed by 409H** 2022-11-07 22:13 UTC
Labels: duplicate, allowlist request
