### ISSUE TITLE
This site is legitimate : https://mint.adrunner.io/

### ISSUE THREAD

**Issue by Kivolov** [MetaMask/eth-phishing-detect#6987] opened 2022-03-29 08:31 UTC
Hello,

This site is legitimate : https://mint.adrunner.io/

Please remove the block.

Thank you

Leave a comment

**Comment by devenblake** [comment] 2022-03-29 19:27
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/6944.

**Closed by devenblake** 2022-03-29 19:27 UTC
Labels: duplicate, allowlist request
