### ISSUE TITLE
[Legitimate Site Blocked] my.forms.app

### ISSUE THREAD

**Issue by sharkset** [MetaMask/eth-phishing-detect#9233] opened 2022-11-01 15:46 UTC
https://my.forms.app/form/61bcdbdc0dcc8e38c7b8801d 

This is a legitimate site that was blocked improperly.

**Comment by 409H** [comment] 2022-11-07 22:53
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/9131

**Closed by 409H** 2022-11-07 22:53 UTC
Labels: duplicate, allowlist request
