### ISSUE TITLE
[Legitimate Site Blocked] mint.adrunner.io

### ISSUE THREAD

**Issue by UberMahk** [MetaMask/eth-phishing-detect#6974] opened 2022-03-29 00:39 UTC
https://mint.adrunner.io/

Minted two perfectly fine and the project has been spot on since I joined their discord. There were several people not affiliated with the project creating fear and trying to spread lies and destroy the project, they did manage to grind it to a halt. Most of the people I saw doing this were not whitelisted and trying to drive the floor price down to then flip on what they said and purchase the NFTs below fair market value. I believe some were banned and lashed out here. I have never received any indication that this was a scam. I have hefty network security, both in the router and on my computer, that would have alerted me if there was malicious content on the site. Metamask also alerts when there is an issue sometimes, though not as effective. All in all, it is haters trying to kill a project and being decently effective at it. If you can remove them from the blacklist, unless you have solid evidence, that would allow the project to grow for those that ACTUALLY invested in it.

This is even your response from the phishing detector

Why Was This Site Blocked?
https://adrunner.io/
 Check

This domain is not blocked! No problem here.

**Comment by devenblake** [comment] 2022-03-29 01:36
Duplicate of #6944.

**Closed by devenblake** 2022-03-29 01:36 UTC
Labels: duplicate, allowlist request
