### ISSUE TITLE
Please whitelist my domain: "Crypto.Market"

### ISSUE THREAD

**Issue by namerapid** [MetaMask/eth-phishing-detect#4238] opened 2020-10-01 09:57 UTC
Hello,

Would you please whitelist my  domain: "Crypto.Market" ?

It is a clean domain for sale now, your code is detecting it as a phishing site. Seems to be it's wrong, or you're using an outdated database. I've asked for many times, but there is no response from you, so pleaseeeeeeee.

Thank you,
Crypto.Market

**Comment by Gudahtt** [comment] 2020-11-09 23:14
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/4143

**Closed by Gudahtt** 2020-11-09 23:14 UTC
