### ISSUE TITLE
[Legitimate Site Blocked] form.jotform.com

### ISSUE THREAD

**Issue by dmeursing** [MetaMask/eth-phishing-detect#8173] opened 2022-08-11 20:48 UTC
https://form.jotform.com/211825094041145?isIframeEmbed=1

Jotform is used as a plugin for websites. I use it on my company domain to gather client info that has nothing to do with blockchain and this "block" prevent my clients from seeing my form. 

Please remove my jotform block. 

Thank you

**Comment by 409H** [comment] 2022-11-07 22:13
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8142

**Closed by 409H** 2022-11-07 22:13 UTC
Labels: duplicate, allowlist request
