### ISSUE TITLE
[Legitimate Site Blocked] beacons.ai

### ISSUE THREAD

**Issue by yin-dra** [MetaMask/eth-phishing-detect#8907] opened 2022-10-17 08:04 UTC
https://beacons.ai/criptowilly

**Comment by yin-dra** [comment] 2022-10-17 08:05
Hi, 
This site is completely friendly and with no intention of scam or be illegitimate. Please review or otherwise flag the problem with more detail.

I would appreciate a fast response.
Regards

**Comment by 409H** [comment] 2022-11-07 21:35
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8894

**Closed by 409H** 2022-11-07 21:35 UTC
Labels: duplicate, allowlist request
