### ISSUE TITLE
PHISHING

### ISSUE THREAD

**Issue by EdsaMETA** [MetaMask/eth-phishing-detect#4846] opened 2021-03-16 21:55 UTC
I tried to sign onto PanCakeSwap, when connecting with wallet it says it has picked up phishing with my MetaMask and it wont allow to transact. What is this problem, please help.

**Comment by 409H** [comment] 2022-11-07 22:42
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/4803

**Closed by 409H** 2022-11-07 22:42 UTC
Labels: duplicate, allowlist request
