### ISSUE TITLE
[Legitimate Site Blocked] moneyzg.academy

### ISSUE THREAD

**Issue by MadDogDean** [MetaMask/eth-phishing-detect#7539] opened 2022-05-29 17:12 UTC
https://moneyzg.academy/

This is a crypto learning site. No phishing, no buying, no selling, no signals, just crypto trading learning videos

**Comment by devenblake** [comment] 2022-06-04 08:19
Duplicate of #7533.

**Closed by devenblake** 2022-06-04 08:19 UTC
Labels: duplicate, allowlist request
