### ISSUE TITLE
[Legitimate Site Blocked] www.metaosk.com

### ISSUE THREAD

**Issue by Hickshu** [MetaMask/eth-phishing-detect#7311] opened 2022-05-04 06:55 UTC
https://www.metaosk.com/

Hello, I am Metaosk.com website builder

Our website is legitimate and mainly introduces MetaOSK NFT related content without any risk.

I hope you can help whitelist our website so that our website can be opened directly.

--------------
We screenshot the website content for you to see.
![1](https://user-images.githubusercontent.com/103487348/166634984-caba14da-02cb-4b97-9c31-47f676d3e1b5.jpg)
![2](https://user-images.githubusercontent.com/103487348/166634989-37778e4f-af27-4eb5-b4bd-18e64d6e1550.jpg)
![3](https://user-images.githubusercontent.com/103487348/166635000-42e7c617-7790-4865-9bd9-7392a0c80a72.jpg)
![4](https://user-images.githubusercontent.com/103487348/166635005-9afb51b1-e90b-46de-9288-1a0a7faa8276.jpg)
![5](https://user-images.githubusercontent.com/103487348/166635013-2b33612a-2eeb-4574-afac-3f890144e756.jpg)

**Comment by devenblake** [comment] 2022-05-10 00:31
Duplicate of #7122.

**Closed by devenblake** 2022-05-10 00:31 UTC
Labels: duplicate, allowlist request
