### ISSUE TITLE
[Legitimate Site Blocked] www.btcminer.website

### ISSUE THREAD

**Issue by taweesakpintakam** [MetaMask/eth-phishing-detect#7249] opened 2022-04-27 10:38 UTC
https://www.btcminer.website/?reffid=qqOuq5qcqQ%3D%3D&fbclid=IwAR3sp26O96hH668z9jp5COvRQnbd9oKXvQjNqjktlmacuOQRSymli1VfMhw

**Comment by devenblake** [comment] 2022-05-11 07:47
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/5599.

**Closed by devenblake** 2022-05-11 07:47 UTC
Labels: duplicate, allowlist request
