### ISSUE TITLE
MetaMask / eth-phishing-detect

### ISSUE THREAD

**Issue by EdsaMETA** [MetaMask/eth-phishing-detect#4847] opened 2021-03-16 22:01 UTC
I tried to connect PancakeSwap, it then indicated this phishing message. What is the problem?

**Comment by 409H** [comment] 2022-11-07 22:42
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/4803

**Closed by 409H** 2022-11-07 22:42 UTC
Labels: duplicate, allowlist request
