### ISSUE TITLE
My site is flagged as etherum phishing website in meta mask !

### ISSUE THREAD

**Issue by s0heyl** [MetaMask/eth-phishing-detect#3626] opened 2020-01-29 20:28 UTC
why my site is flagged as etherum phishing website  ???
i just created it !
the domain is parsis.agency

**Comment by 409H** [comment] 2020-02-11 22:27
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/3637

**Closed by 409H** 2020-02-11 22:27 UTC
Labels: duplicate, whitelist request
