### ISSUE TITLE
meta mask phising detection on empowr

### ISSUE THREAD

**Issue by louiemagooee** [MetaMask/eth-phishing-detect#3386] opened 2019-10-13 22:21 UTC
I have an Empowr account, my name is Martyn William England my email is m.e.painters@gmail.com. Metamask continues to put up a phising warning on my Empowr account, I want to make changes to my coins. Please remove the phising detection notice 
on my account. My phone number is 64221869114 in New Zealand you can contact me if you need by either phone or email.

**Comment by xrn** [comment] 2020-11-16 09:33
Closing. Duplicate of #2663

**Closed by xrn** 2020-11-16 09:33 UTC
