### ISSUE TITLE
[Legitimate Site Blocked] krr.usermd.net

### ISSUE THREAD

**Issue by pawelantczak** [MetaMask/eth-phishing-detect#6053] opened 2021-11-30 12:53 UTC
https://krr.usermd.net/

**Comment by devenblake** [comment] 2021-12-02 02:10
It looks like the directory is a mirror of [tinyfilemanager](https://github.com/prasathmani/tinyfilemanager). Why not use the original repository, hosted here on GitHub, instead?

**Comment by devenblake** [comment] 2022-01-09 20:58
Duplicate of #3520.

**Closed** 2022-01-13 00:27 UTC
Labels: duplicate
