### ISSUE TITLE
[Legitimate Site Blocked] zksync.crew3.xyz

### ISSUE THREAD

**Issue by Dtoanss** [MetaMask/eth-phishing-detect#9174] opened 2022-10-31 17:16 UTC
https://zksync.crew3.xyz/
dear sir
Why am I locked out of my account? I participated in the process from the first beta, I was on duty, testing your site and I was locked?
Please explain why I am locked ! I promise to fix it and never do it again.
Thank!

**Comment by Dtoanss** [comment] 2022-10-31 17:17
If it's not a fatal error please give me a chance! It's my work and my process

**Comment by Dtoanss** [comment] 2022-10-31 17:19
my wallet address: 0x3E5734ba8166DfC38b1ff271b0903cBb7Efafe7C
discord id : pPikachu#4266

**Comment by 409H** [comment] 2022-11-07 21:22
Closing. Duplicate of in https://github.com/MetaMask/eth-phishing-detect/pull/9265

**Closed by 409H** 2022-11-07 21:22 UTC
Labels: duplicate, allowlist request
