### ISSUE TITLE
[Legitimate Site Blocked] mint.adrunner.io

### ISSUE THREAD

**Issue by Shafs297** [MetaMask/eth-phishing-detect#6980] opened 2022-03-29 06:15 UTC
https://mint.adrunner.io/

This website is legit for NFT. Kindly remove from the list. thank you.

**Comment by devenblake** [comment] 2022-03-29 19:26
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/6944.

**Closed by devenblake** 2022-03-29 19:26 UTC
Labels: duplicate, allowlist request
