### ISSUE TITLE
[Legitimate Site Blocked] my.forms.app

### ISSUE THREAD

**Issue by AlineBarrosMoraes** [MetaMask/eth-phishing-detect#9106] opened 2022-10-27 15:21 UTC
https://my.forms.app/form/635156dfe0dc33518733dfd3

**Comment by 409H** [comment] 2022-11-07 22:52
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/9131

**Closed by 409H** 2022-11-07 22:52 UTC
Labels: duplicate, allowlist request
