### ISSUE TITLE
[Legitimate Site Blocked] www.pinksale.finance

### ISSUE THREAD

**Issue by Santoad1** [MetaMask/eth-phishing-detect#6147] opened 2021-12-09 08:21 UTC
https://www.pinksale.finance/#/launchpad/0x3f40e355D02ad84E5535B1AdA5254F572eDdac89?chain=BSC

**Comment by devenblake** [comment] 2021-12-09 13:42
Duplicate of #6115.

**Closed** 2021-12-14 01:16 UTC
Labels: duplicate
