### ISSUE TITLE
[Legitimate Site Blocked] mint.adrunner.io

### ISSUE THREAD

**Issue by CryptoForager** [MetaMask/eth-phishing-detect#6962] opened 2022-03-28 21:38 UTC
https://mint.adrunner.io/

This is a legit project. I have been a part of the community since day 1. The CMO was fired and out of revenge filed a ticket with MetaMask to have them blacklisted. This is a revenge move by a former employee of the project and nothing more. This is one of the most trustworthy teams in the NFT space. They are all fully doxxed and are in no way shape or form a rugpull nor go against any violations.

**Comment by devenblake** [comment] 2022-03-29 01:34
Duplicate of #6944.

**Closed by devenblake** 2022-03-29 01:34 UTC
Labels: duplicate, allowlist request
