### ISSUE TITLE
Pishing warning for aucxis.gr domain 

### ISSUE THREAD

**Issue by GFCauctions** [MetaMask/eth-phishing-detect#1391] opened 2018-04-15 09:08 UTC
Hello, we have recently received a pishing warning for one of our domains, www.aucxis.gr . What actions are required in order to resolve this issue, and get off the metamask blacklist warning?
Thank you in advance
The aucxis Greece team
Dimitri Haritos// CEO     Biolife Ltd.
GFC-Greek Food Corridors
oxylife@otenet.gr 
operation@greekfoodcorridors.com  
T. 0030 210 6718745

![e0ecd26c-6804-4d58-85c7-129cc57a860f](https://user-images.githubusercontent.com/37484701/38776781-61261e26-40a5-11e8-9463-930012d2ecef.jpg)

**Comment by 409H** [comment] 2018-04-17 20:44
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/1372

Will whitelist today in https://github.com/MetaMask/eth-phishing-detect/pull/1412

**Closed by 409H** 2018-04-17 20:44 UTC
Labels: whitelist request
