### ISSUE TITLE
empowr.com

### ISSUE THREAD

**Issue by Nechiw** [MetaMask/eth-phishing-detect#2660] opened 2018-11-26 23:38 UTC
I write you to report this domain is incorrectly flagged.
www.empowr.com

Regards,
Nechiw

**Comment by 409H** [comment] 2018-11-26 23:42
Hi Nechiw, this domain was blacklisted by myself as they are sending private keys to their backend server. Private keys should stay ***private*** and not shared with anyone.

![image](https://user-images.githubusercontent.com/2313704/49048972-e577e200-f1d4-11e8-8278-ef8651d5b757.png)

**Comment by renelmiller0120** [comment] 2018-11-27 00:06
we never give this site any private keys so that has to be a mistake. they get only the keys that we give them and everyone is told never to give or use their personal keys

**Comment by 409H** [comment] 2018-11-27 01:33
Closing (in favour of an issue started by empowr). Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2663

**Closed by 409H** 2018-11-27 01:33 UTC
Labels: needs-more-information, whitelist request

**Comment by vighanraj** [comment] 2018-11-27 08:17
Incorrect Marking of  phishing  :- site empowr.com

please get it out phishing mode. Site is absolute safe to use

**Comment by doug9694** [comment] 2019-01-21 14:54
While it can't be phishing because it is the official,site asking it is still unethical and not right. It should be called unethical or similar unless y can show me where it is illegal. Scam in this case is not the right word either because they do credit coins and do put into youi wally the coins y buy from them. They are hypocrites because several times they stated NEVER send your priv. key to anyone. Then they ask for them. It just shows how inept and devious they are. Barely stayinging on this side of legal and sometimes it appears going to the illegal side
