### ISSUE TITLE
[Legitimate Site Blocked] form.jotform.com

### ISSUE THREAD

**Issue by morsh97** [MetaMask/eth-phishing-detect#8161] opened 2022-08-11 16:11 UTC
https://form.jotform.com/221645039860154 is a legitimate website link. It is the application to become a speaker at the upcoming Fintech Nexus Merge conference in October. 

Fintech Nexus is a media and events company, previously known as LendIt Fintech. We work with fintech companies, banks and are venturing into the Web3 space now with our upcoming Merge event.

Our Jotform is how our team accepts and reviews speaker applications.
Here is the link to our confirmed speakers on the website - https://www.fintechnexus.com/merge/2022/speakers/

Would love this resolved, feel free to reach out with any questions. 
(917) 900-5037
mor@fintechnexus.com

**Comment by 409H** [comment] 2022-11-07 22:14
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8142

**Closed by 409H** 2022-11-07 22:14 UTC
Labels: duplicate, allowlist request
