### ISSUE TITLE
[Legitimate Site Blocked] my.forms.app

### ISSUE THREAD

**Issue by mertozeren** [MetaMask/eth-phishing-detect#9123] opened 2022-10-28 07:34 UTC
Hello,

I am writing you on behalf of forms.app which is a platform for creating online forms & surveys. 

We have recently received a couple of reports from our users saying that the MetaMask Phishing Detection extension blocks our domain. Could you please remove this domain https://my.forms.app/ from your blacklist, as it is obviously a false-positive? 

Also, if you receive reports of phishing forms created on forms.app in the future, please contact us directly. 

Please let me know! 

Best wishes,
Mert

**Comment by 409H** [comment] 2022-11-07 22:53
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/9131

**Closed by 409H** 2022-11-07 22:53 UTC
Labels: duplicate, allowlist request
