### ISSUE TITLE
[Legitimate Site Blocked] wallet.elrond.com

### ISSUE THREAD

**Issue by tanghel** [MetaMask/eth-phishing-detect#8889] opened 2022-10-16 22:05 UTC
https://wallet.elrond.com/

This is the official wallet of the Elrond ecosystem

**Comment by 409H** [comment] 2022-11-07 22:47
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8870

**Closed by 409H** 2022-11-07 22:47 UTC
Labels: duplicate, allowlist request
