### ISSUE TITLE
[Legitimate Site Blocked] gaiaworld.com

### ISSUE THREAD

**Issue by iakashrai** [MetaMask/eth-phishing-detect#5775] opened 2021-11-03 14:05 UTC
https://gaiaworld.com/
This is a legitimate site, people have reported it under some misunderstanding or hatred.
Look into this matter.

**Comment by devenblake** [comment] 2021-11-03 20:06
Duplicate of #5768.

**Closed** 2021-12-03 06:15 UTC
Labels: duplicate
