### ISSUE TITLE
333eth.io

### ISSUE THREAD

**Issue by Kuansyh** [MetaMask/eth-phishing-detect#2479] opened 2018-09-22 15:54 UTC

**Comment by Mavrmich** [comment] 2018-09-23 05:28
> No description provided.

Hello everybody! If you have any things about blocking 333eth.io, please open your mind, and write more completely, with qwestions and solvage our problems ! Thk you!
P.s. we also waiting for moving 333eth.io to whitelist!

**Comment by 409H** [comment] 2018-10-02 20:19
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2374

**Closed by 409H** 2018-10-02 20:19 UTC
Labels: duplicate, whitelist request
