### ISSUE TITLE
[Legitimate Site Blocked] openteam.community

### ISSUE THREAD

**Issue by TiberiusB** [MetaMask/eth-phishing-detect#5827] opened 2021-11-03 18:46 UTC
https://openteam.community/environmental-claims-clearinghouse-works-on-statement-of-need/

I believe that this was unreasonably blocked.

**Comment by devenblake** [comment] 2021-11-03 22:29
Duplicate of #5756.

**Closed** 2021-11-16 16:12 UTC
