### ISSUE TITLE
[Legitimate Site Blocked] www.pinksale.finance

### ISSUE THREAD

**Issue by elpuji** [MetaMask/eth-phishing-detect#6146] opened 2021-12-09 08:16 UTC
https://www.pinksale.finance/#/launchpad/0x42eD48379Ed980D894E4A1fBD929AFD390574d26?chain=BSC

**Comment by devenblake** [comment] 2021-12-09 13:41
Duplicate of #6115.

**Closed** 2021-12-14 01:16 UTC
Labels: duplicate
