### ISSUE TITLE
free-ethereum.io 

### ISSUE THREAD

**Issue by PatriciaGant** [MetaMask/eth-phishing-detect#5323] opened 2021-08-25 13:37 UTC
unblock the site it is working fine and your stupid extention blocks site and dont let me acces this site i use for YEARS now so no scam....

**Comment by davidwgrossman** [comment] 2021-08-30 19:40
apologies! This is a duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/5342

**Closed by davidwgrossman** 2021-08-30 19:40 UTC
