### ISSUE TITLE
https://pancakeswap.finance/

### ISSUE THREAD

**Issue by Painicdrina** [MetaMask/eth-phishing-detect#4844] opened 2021-03-16 21:22 UTC
https://pancakeswap.finance/

It's not a scam, it's one of the **most important portals** within its sector, blocking it is a superior outrage.

Thanks

**Comment by 409H** [comment] 2022-11-07 22:40
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/4803

**Closed by 409H** 2022-11-07 22:40 UTC
Labels: duplicate, allowlist request
