### ISSUE TITLE
[Legitimate Site Blocked] www.pinksale.finance

### ISSUE THREAD

**Issue by kivuking** [MetaMask/eth-phishing-detect#6140] opened 2021-12-09 06:04 UTC
https://www.pinksale.finance/#/launchpad/0xE6EA2597e0bf28e565E2c0a4127f8b9271374568?chain=BSC

**Comment by devenblake** [comment] 2021-12-09 07:23
Duplicate of #6115.

**Closed** 2021-12-14 01:16 UTC
Labels: duplicate
