### ISSUE TITLE
[Legitimate Site Blocked] shido.market

### ISSUE THREAD

**Issue by Kalemba1978** [MetaMask/eth-phishing-detect#9042] opened 2022-10-22 19:52 UTC
https://shido.market/ is a legit website but is being blocked for some reason. Please fix.

**Comment by 409H** [comment] 2022-11-07 21:41
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/9037

**Closed by 409H** 2022-11-07 21:41 UTC
Labels: duplicate, allowlist request
