### ISSUE TITLE
[Legitimate Site Blocked] binances.club

### ISSUE THREAD

**Issue by faramsokol** [MetaMask/eth-phishing-detect#7870] opened 2022-07-01 11:01 UTC
Hi. In thread https://github.com/MetaMask/eth-phishing-detect/issues/6696, no one answered me on the issue !!

**Comment by raomohsin39** [comment] 2022-07-01 11:08
Admin, Hello! Please unblock this site

**Comment by devenblake** [comment] 2022-07-01 23:01
Duplicate of #6696.

**Closed by devenblake** 2022-07-01 23:01 UTC
Labels: duplicate, allowlist request
