### ISSUE TITLE
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/phishing.html#hostname=www.free-ethereum.io&href=https%3A%2F%2Fwww.free-ethereum.io%2F

### ISSUE THREAD

**Issue by mamzel666** [MetaMask/eth-phishing-detect#5341] opened 2021-08-30 08:44 UTC
its not works  chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/phishing.html#hostname=www.free-ethereum.io&href=https%3A%2F%2Fwww.free-ethereum.io%2F

**Comment by davidwgrossman** [comment] 2021-08-30 19:23
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/5342

**Closed by davidwgrossman** 2021-08-30 19:23 UTC
