### ISSUE TITLE
[Legitimate Site Blocked] www.empowr.com

### ISSUE THREAD

**Issue by sksaha61** [MetaMask/eth-phishing-detect#6282] opened 2021-12-27 10:29 UTC
http://www.empowr.com/socnet/EmailStat.aspx?lit=5&me=otUh9vs.UpO4Fqj8rQcy8MUvC.M6npeK3GYqi41Q5Z3jDTk5S4B0ZKcnNhIdVe13IDI-elFaNT9MjshdTf1XqHX1VFqA9A23xihhyJUYqSjq1PjKc1MGaEjefMD5qhjduWvaYY3zjFFROrq9umtP5wOjeigU7T-PDJl-wdgq1v8NFMDrS2lb9XT9U2zYJzhn&fan=Y8Ca43P1qAMdoWNxwn%2fBbA%3d%3d&opg=http%3a%2f%2fprofile.empowr.com%2fProfile%2fNewCustomProfile.aspx%3fu%3da963141e855e491dbd2373488da77d7c&vet=684&dt=060119&mlid=764734200&tmpID=3212&linkname=PostLink&emailNum=1&eaid=yM9KXk6njAlsh2TqFPu%2b7w%3d%3d&rt=12

**Comment by devenblake** [comment] 2021-12-27 22:13
Duplicate of #2663.

**Closed** 2022-01-12 23:10 UTC
