### ISSUE TITLE
Reader's digest legitimate site is marked as phishing

### ISSUE THREAD

**Issue by kapilbajaj1** [MetaMask/eth-phishing-detect#2509] opened 2018-09-28 16:44 UTC
Please remove Reader's digest rd.com from phishing list

**Comment by 409H** [comment] 2018-09-30 15:11
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2346

@kapilbajaj1 please see comments: https://github.com/MetaMask/eth-phishing-detect/issues/2346#issuecomment-421176174

**Closed by 409H** 2018-09-30 15:11 UTC
