### ISSUE TITLE
[Legitimate Site Blocked] www.openrpa.dk

### ISSUE THREAD

**Issue by bobpeers** [MetaMask/eth-phishing-detect#6296] opened 2021-12-30 07:13 UTC
https://www.openrpa.dk/ This site is not even listed at https://cryptoscamdb.org/scams so it's not clear why it would be flagged.

**Comment by devenblake** [comment] 2022-01-10 02:40
Duplicate of #5733.

**Closed** 2022-01-13 00:15 UTC
