### ISSUE TITLE
[Legitimate Site Blocked] officialnft.xyz

### ISSUE THREAD

**Issue by smilleeymilleey** [MetaMask/eth-phishing-detect#7067] opened 2022-04-04 22:19 UTC
https://officialnft.xyz/

official nft is a legitimate project and has an erroneous "phishing-detect" warning when connecting your M3etamask wallet

**Comment by devenblake** [comment] 2022-04-05 04:28
Duplicate of #6938.

**Closed by devenblake** 2022-04-05 04:28 UTC
Labels: duplicate, allowlist request
