### ISSUE TITLE
[Legitimate Site Blocked] www.pxinity.com

### ISSUE THREAD

**Issue by Inkyydesign** [MetaMask/eth-phishing-detect#6402] opened 2022-01-14 13:44 UTC
https://www.pxinity.com/

Hello , I need to write 100 messages and wait 10 years for you to resolve this?

PLEASE REMOVE MY WEBSITE FROM YOUR CRAP LIST IT DOENST HAVE ANYTHING WITH FCKING CRYPTO

**Comment by devenblake** [comment] 2022-01-16 14:04
Duplicate of #5143.

**Closed by devenblake** 2022-01-16 14:04 UTC
Labels: duplicate, allowlist request
