### ISSUE TITLE
[Legitimate Site Blocked] gaiaworld.com

### ISSUE THREAD

**Issue by Sage089** [MetaMask/eth-phishing-detect#5799] opened 2021-11-03 14:57 UTC
Hey.

GAIA's web page (https://gaiaworld.com/) was added to phishing list by mistake or some miss information. The project and web page is legit, as well as the team.

**Comment by devenblake** [comment] 2021-11-03 20:09
Duplicate of #5768.

**Closed** 2021-12-03 06:16 UTC
Labels: duplicate
