### ISSUE TITLE
Unlock empowr.com please

### ISSUE THREAD

**Issue by ulianagoronkova** [MetaMask/eth-phishing-detect#2669] opened 2018-11-27 18:55 UTC
http://prntscr.com/lnqico

**Comment by 409H** [comment] 2018-11-27 19:06
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2663

**Closed by 409H** 2018-11-27 19:06 UTC
Labels: duplicate

**Comment by mongatane** [comment] 2018-11-28 14:43
Guys what is wrong now with Empowr? 
I have been using it since last year without any problem and now you saying Phishing? 
I don't understand.

**Comment by Joby143** [comment] 2018-12-09 21:59
empowr isn't a phishing site. I think metamask is though. empowr doesn't ask for a private key they give you one.
