### ISSUE TITLE
Mr

### ISSUE THREAD

**Issue by Arid-1** [MetaMask/eth-phishing-detect#3381] opened 2019-10-09 16:08 UTC
For many months now, metamask which is recommended as the surest protection for empowr citizens to safely perform their daily tasks has suddenly begun to prevent me from opening my empowr page except I disable it on my PC setting. Why is that so?

**Comment by 409H** [comment] 2019-10-31 22:48
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2663

**Closed by 409H** 2019-10-31 22:48 UTC
Labels: duplicate, whitelist request
