### ISSUE TITLE
[Legitimate Site Blocked] unilayer.app

### ISSUE THREAD

**Issue by Smeilz** [MetaMask/eth-phishing-detect#5806] opened 2021-11-03 15:33 UTC
https://unilayer.app/ is really normal project! Vote for legitimate!

**Comment by devenblake** [comment] 2021-11-03 21:54
Duplicate of #5801.

**Comment by Chacoin** [comment] 2021-11-04 00:20
Yes, legitimate unilayer.app

**Closed** 2021-12-03 06:16 UTC
Labels: duplicate
