### ISSUE TITLE
[Legitimate Site Blocked] form.jotform.com

### ISSUE THREAD

**Issue by adolfogrego** [MetaMask/eth-phishing-detect#8174] opened 2022-08-11 22:53 UTC
Metamask is blocking sites from 
https://form.jotform.com

Jotform is a legal and reliable form builder. I don't believe Metamask should be flagging it

**Comment by 409H** [comment] 2022-11-07 22:13
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8142

**Closed by 409H** 2022-11-07 22:13 UTC
Labels: duplicate, allowlist request
