### ISSUE TITLE
[Legitimate Site Blocked] foundation.app

### ISSUE THREAD

**Issue by jacklynlaryea** [MetaMask/eth-phishing-detect#8617] opened 2022-09-29 15:56 UTC
https://foundation.app/@meowgress/starseed/5

foundation is a legitimate NFT art website. not sure why they are being blocked by metamask...

**Comment by 409H** [comment] 2022-11-07 22:00
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8588

**Closed by 409H** 2022-11-07 22:00 UTC
Labels: duplicate, allowlist request
