### ISSUE TITLE
Please whitelist  "Crypto.market" domain

### ISSUE THREAD

**Issue by namerapid** [MetaMask/eth-phishing-detect#4405] opened 2020-11-09 16:27 UTC
Hi,

Something is wrong here, my domain is for sale and only points to Dan.com - a domain aftermarket. Please whitelist it.

Thank you,

**Comment by Gudahtt** [comment] 2020-11-09 23:14
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/4143

**Closed by Gudahtt** 2020-11-09 23:14 UTC
