### ISSUE TITLE
Please remove false alarm for the website asics.com 

### ISSUE THREAD

**Issue by nicoSix** [MetaMask/eth-phishing-detect#3638] opened 2020-02-02 19:32 UTC
I just got an alert for the site asics.com, which is just a reputed shoe seller unlinked with cryptocurrencies.

Is it possible to remove it? Thank you!

**Comment by 409H** [comment] 2020-02-11 22:10
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/3645

**Closed by 409H** 2020-02-11 22:11 UTC
Labels: duplicate, whitelist request
