### ISSUE TITLE
[Legitimate Site Blocked] ltcminer.com

### ISSUE THREAD

**Issue by salimovich10** [MetaMask/eth-phishing-detect#5968] opened 2021-11-19 19:52 UTC
https://ltcminer.com/?__cf_chl_rt_tk=WvRQ4U4ngsUj9ygPCE_MagTVNsQvYuAdO7hEdOJXW5s-1637351410-0-gaNycGzNBv0

**Comment by devenblake** [comment] 2021-11-23 13:58
[Duplicate](https://github.com/MetaMask/eth-phishing-detect/issues?q=ltcminer).

**Comment by devenblake** [comment] 2022-01-13 01:35
Duplicate of #4472.

**Closed by devenblake** 2022-01-13 01:35 UTC
Labels: duplicate
