### ISSUE TITLE
[Legitimate Site Blocked] nfiniti.io

### ISSUE THREAD

**Issue by qubit3tech** [MetaMask/eth-phishing-detect#6058] opened 2021-12-01 13:12 UTC
https://nfiniti.io/ is not a scam site we are the owners of the domain and are a design studio. :(
It would be greatly appreciated if we can have this removed from the scam list.  Thank you!

**Comment by devenblake** [comment] 2021-12-01 13:33
Duplicate of #6058.

**Closed** 2021-12-03 06:05 UTC
Labels: duplicate
