### ISSUE TITLE
[Legitimate Site Blocked] wallet.elrond.com

### ISSUE THREAD

**Issue by yuriivishnevskii** [MetaMask/eth-phishing-detect#8938] opened 2022-10-17 17:25 UTC
https://wallet.elrond.com/hook/login?token=198b220e1873bf914e5b64b88da3c263&callbackUrl=https%3A%2F%2Fmaiarlaunchpad.com%2Fashswap%2Fhow-to-guide

**Comment by 409H** [comment] 2022-11-07 22:48
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8870

**Closed by 409H** 2022-11-07 22:48 UTC
Labels: duplicate, allowlist request
