### ISSUE TITLE
[Legitimate Site Blocked] mint.adrunner.io

### ISSUE THREAD

**Issue by qadams85** [MetaMask/eth-phishing-detect#6971] opened 2022-03-28 23:36 UTC
https://mint.adrunner.io/
this sit is not a scam, ive used it to mint on march 23 and many others have as well. I tried to mint one last AdRunner today before the mint closed and much to my surprise the website was blocked. Im unsure why because it was working perfectly fine for a legitimate project run by a DOXED team. Due to this site is blocked, the creators as well as investors are now put in financial danger because the mint must be stopped and is scaring away other potential investors. Please return the site to its function so the AdRunner community can continue to grow!

**Comment by devenblake** [comment] 2022-03-29 01:35
Duplicate of #6944.

**Closed by devenblake** 2022-03-29 01:35 UTC
Labels: duplicate, allowlist request
