### ISSUE TITLE
empowr is not a phishing site

### ISSUE THREAD

**Issue by talina2401** [MetaMask/eth-phishing-detect#2709] opened 2018-12-08 20:21 UTC
It is completely safe website and I have never been fished had any money stolen from me.
I have been on the website for over a 9 years.
Please remove fast empowr.com from your phishing site categories.

**Comment by 409H** [comment] 2018-12-08 20:52
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2663

**Closed by 409H** 2018-12-08 20:52 UTC
