### ISSUE TITLE
[Legitimate Site Blocked] ltcminer.com

### ISSUE THREAD

**Issue by Wisants** [MetaMask/eth-phishing-detect#7324] opened 2022-05-05 00:27 UTC
https://ltcminer.com/36?__cf_chl_rt_tk=s2YxismJ5EQyhesag_38KQQE5oCWstJIoQ9ugz1VGs4-1651710440-0-gaNycGzNCSU

**Comment by devenblake** [comment] 2022-05-06 01:21
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/4472.

**Closed by devenblake** 2022-05-06 01:21 UTC
Labels: duplicate, allowlist request
