### ISSUE TITLE
https://morcrypto.net is wrongly flagged

### ISSUE THREAD

**Issue by Morcrypto** [MetaMask/eth-phishing-detect#3332] opened 2019-09-17 19:06 UTC
Thank you for responding to us, we have been on this for a while and everyone seemed not be aware of what was wrong. We had to close the issue, but it reopened here: https://github.com/MetaMask/eth-phishing-detect/issues/3314#event-2640917310

Please see how you can assist, thank you!

Best regards.

**Comment by 409H** [comment] 2019-09-17 19:18
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/3314 (reopened old ticket)

**Closed by 409H** 2019-09-17 19:18 UTC
