### ISSUE TITLE
[Legitimate Site Blocked] mint.adrunner.io

### ISSUE THREAD

**Issue by Nevkiller13** [MetaMask/eth-phishing-detect#6981] opened 2022-03-29 07:10 UTC
Hello,

This site is legitimate : https://mint.adrunner.io/

Please remove the block.

Thank you

**Comment by devenblake** [comment] 2022-03-29 19:26
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/6944.

**Closed by devenblake** 2022-03-29 19:26 UTC
Labels: duplicate, allowlist request
