### ISSUE TITLE
[Legitimate Site Blocked] bakedbeans.io

### ISSUE THREAD

**Issue by patrickewater** [MetaMask/eth-phishing-detect#8858] opened 2022-10-15 15:21 UTC
https://bakedbeans.io/  This is not a phishing site.  This is a legitimate site.

**Comment by 409H** [comment] 2022-11-07 23:18
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/9062

**Closed by 409H** 2022-11-07 23:18 UTC
Labels: duplicate, allowlist request
