### ISSUE TITLE
[Legitimate Site Blocked] agent1.xyz

### ISSUE THREAD

**Issue by badjoerichards** [MetaMask/eth-phishing-detect#8969] opened 2022-10-18 16:45 UTC
URGENT: This is a legitimate and working NFT project:
https://agent1.xyz/mint

It is a partner with HTC, iCandy.io and JericVerse.com

Twitter: https://twitter.com/agent1xyz
Opensea sell out: http://opensea.io/collection/agent1

False positive MetaMask Phishing Detection.

**Comment by 409H** [comment] 2022-11-07 23:13
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8990

**Closed by 409H** 2022-11-07 23:13 UTC
Labels: duplicate, allowlist request
