### ISSUE TITLE
Stop Blocking empowr.com this is ridiculous 

### ISSUE THREAD

**Issue by Joby143** [MetaMask/eth-phishing-detect#3130] opened 2019-06-21 22:17 UTC
It is ridiculous. Stop blocking a site that doesn't ask for a private key as your app does. You should block yourself.

**Comment by 409H** [comment] 2019-07-06 02:11
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/3078

**Closed by 409H** 2019-07-06 02:11 UTC
