### ISSUE TITLE
[Legitimate Site Blocked] gaiaworld.com

### ISSUE THREAD

**Issue by baolongt** [MetaMask/eth-phishing-detect#5768] opened 2021-11-03 09:27 UTC
I think this website is not scam
https://gaiaworld.com/

**Comment by Aurom22** [comment] 2021-11-03 20:46
it is scam:
![tempsnip](https://user-images.githubusercontent.com/93665387/140190077-000583c9-7c59-44d4-aa4a-c4a4e12c5116.png)

**Comment by Aurom22** [comment] 2021-11-03 20:46
they give the adress and pair scam

**Comment by devenblake** [comment] 2021-11-03 21:50
Obviously `gaiaworld.com`'s block affects many users. However, please be mindful to not submit duplicates of issues - this will not expedite a fix.

**Comment by devenblake** [comment] 2021-11-03 21:53
It seems all of these issues may have been fixed by #5817.

**Comment by devenblake** [comment] 2021-11-03 22:09
#5771 seems to be filed by a co-founder of the site.

**Comment by Sage089** [comment] 2021-11-03 22:35
> it is scam: ![tempsnip](https://user-images.githubusercontent.com/93665387/140190077-000583c9-7c59-44d4-aa4a-c4a4e12c5116.png)

It is not:
https://polygonscan.com/token/0x723b17718289a91af252d616de2c77944962d122

**Comment by Aurom22** [comment] 2021-11-03 22:58
![image](https://user-images.githubusercontent.com/93665387/140226455-f56b20b2-de3f-416c-a16b-799ca8829ad1.png)

**Comment by Aurom22** [comment] 2021-11-03 22:58
it is

**Comment by Aurom22** [comment] 2021-11-03 22:59
tell me how yo have a token with one pair that was rugpull, and 7 min later you lit another pair with same contract?

**Comment by Aurom22** [comment] 2021-11-03 23:00
almost 2 million dollars stoled

**Comment by btcgeo** [comment] 2021-11-04 00:56
Aurom22 it seems you have a personal vendetta and just simply don't know how an AMM works, the problem is very simple, someone had GAIA tokens and they created a liquidity pool on QuickSwap DEX minutes before the team did for the USDC/GAIA pair, so that's why the token contract remains the same, because the person that created the LP on QS somehow got his tokens before he was supposed to. This has nothing to do with GAIA being a scam but rather the actions of single person with bad intentions.

**Comment by Aurom22** [comment] 2021-11-04 01:31
no i dont give any cent for this proyect, its just, that you think for you have an nft game you are up of the law, well if you dont have any, i am worried for all who was stoled take your part of the rugpull and pay all those who was stoled

**Comment by Aurom22** [comment] 2021-11-04 01:37
and one simply question why do you erased in your social media the message of the contract an pair that was used for the fraud?

**Comment by btcgeo** [comment] 2021-11-04 01:41
> and one simply question why do you erased in your social media the message of the contract an pair that was used for the fraud?

Because the team had plans to start the liquidity pool for GAIA/USDC pair on QS,  and once we found out that someone setup the liquidity before the team we changed it to GAIA/DAI, again the blockchain doesn't lie, you can literally go to polygonscan and check what wallet address started the liquidity pool for GAIA/USDC on QS and I guarantee you that wallet is not connected to the GAIA team at all.

**Closed** 2021-12-03 06:15 UTC
Labels: duplicate
