### ISSUE TITLE
[Legitimate Site Blocked] metamasak.com

### ISSUE THREAD

**Issue by choff2001** [MetaMask/eth-phishing-detect#6595] opened 2022-02-08 03:32 UTC
https://metamasak.com/?walletid=16442909451103b14d0f14ac5bb809aff0ea5ae9a473b97a8b

I deposited that eth from my crypto.com wallet why would my transaction be at risk i followed all the procedures can you help not make this happen again or get the security i need

**Comment by devenblake** [comment] 2022-02-26 05:03
Duplicate of #6380.

**Closed by devenblake** 2022-02-26 05:03 UTC
Labels: duplicate, allowlist request
