### ISSUE TITLE
[Legitimate Site Blocked] www.metaosk.com It is a legitimate URL, I hope to help give whitelist

### ISSUE THREAD

**Issue by Hickshu** [MetaMask/eth-phishing-detect#7238] opened 2022-04-26 09:28 UTC
https://www.metaosk.com/ 

It is a legitimate URL, I hope to help give whitelist

**Comment by Hickshu** [comment] 2022-04-26 09:30
https://www.metaosk.com/

It is a legitimate URL, I hope to help give whitelist

**Comment by devenblake** [comment] 2022-05-10 00:31
Duplicate of #7122.

**Closed by devenblake** 2022-05-10 00:31 UTC
Labels: duplicate, allowlist request
