### ISSUE TITLE
My Empowr Account

### ISSUE THREAD

**Issue by kahunanya** [MetaMask/eth-phishing-detect#2716] opened 2018-12-10 12:24 UTC
Hello,
Please what is happening each time i want to open my empowr account through google chrome but i cannot open it. The site will always appear like this https://prnt.sc/lt1rzl instead of my empowr account to open. Please,empowr is genuine and allow me to login to the site.

kelechi

**Comment by 409H** [comment] 2018-12-11 00:23
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2663

**Closed by 409H** 2018-12-11 00:23 UTC
