### ISSUE TITLE
[Legitimate Site Blocked] gaiaworld.com

### ISSUE THREAD

**Issue by JoshBGaia** [MetaMask/eth-phishing-detect#5771] opened 2021-11-03 13:45 UTC
https://gaiaworld.com/

Hello, 

I am one of the co-founders to Gaia Everworld. It appears our website has been wrongly reported to yourselves. We experienced some technical difficulties yesterday with our token launch and as a result some people lost their investments. The project team announced an issue as soon as we were aware and rectified it right away. Please could you remove the warning from our website Gaiaworld.com. I will be happy to provide any information that is required. My colleague will also be contacting you regarding this matter. We hope this can be resolved with haste. Thank you Josh B

**Comment by devenblake** [comment] 2021-11-03 20:06
Duplicate of #5768.

**Comment by Aurom22** [comment] 2021-11-03 22:17
give back all the money stole

**Closed** 2021-12-03 06:15 UTC
Labels: duplicate
