### ISSUE TITLE
[Legitimate Site Blocked] junoswap.com

### ISSUE THREAD

**Issue by Paolito78** [MetaMask/eth-phishing-detect#7825] opened 2022-06-29 14:04 UTC
https://junoswap.com/ ??

**Comment by Paolito78** [comment] 2022-06-29 14:04
this is good site

**Comment by Paolito78** [comment] 2022-06-29 14:04
i use this for a swaping assets on juno

**Comment by devenblake** [comment] 2022-07-01 23:05
Duplicate of #7817.

**Closed by devenblake** 2022-07-01 23:05 UTC
Labels: duplicate, allowlist request
