### ISSUE TITLE
[Legitimate Site Blocked] beacons.ai

### ISSUE THREAD

**Issue by KhalidWar** [MetaMask/eth-phishing-detect#8884] opened 2022-10-16 21:12 UTC
https://beacons.ai/

Not sure why this website is added.

Please review and update.

**Comment by 409H** [comment] 2022-11-07 21:34
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8894

**Closed by 409H** 2022-11-07 21:34 UTC
Labels: duplicate, allowlist request
