### ISSUE TITLE
ltcminer phishing flagged wrong

### ISSUE THREAD

**Issue by AndrewKropp** [MetaMask/eth-phishing-detect#5515] opened 2021-09-25 16:17 UTC
They paid out. 
![2021-09-25 (1)](https://user-images.githubusercontent.com/91384771/134778377-247e0664-72e0-4f8e-bb7a-4e100da697a1.png)

**Comment by devenblake** [comment] 2021-12-14 02:17
Duplicate of #4472.

**Closed** 2022-01-13 01:41 UTC
Labels: duplicate
