### ISSUE TITLE
Domain incorrectly flagged

### ISSUE THREAD

**Issue by mgnmnn** [MetaMask/eth-phishing-detect#6168] opened 2021-12-10 18:31 UTC
Metamap.com is a legitimate website, unrelated to Ethereum or Metamask, and has been incorrectly flagged. Can you please help us resolve this issue urgently?

**Comment by devenblake** [comment] 2022-01-09 14:56
Duplicate of #6166.

**Closed** 2022-01-13 01:44 UTC
Labels: duplicate
