### ISSUE TITLE
[Legitimate Site Blocked] murakamiflowers.kaikaikiki.com

### ISSUE THREAD

**Issue by avakianesq** [MetaMask/eth-phishing-detect#7301] opened 2022-05-02 23:03 UTC
Good afternoon,

I hope this message finds you well.

It saddens me to see that the LEGITIMATE website for Takashi Murakami's murakami.flowers NFT project has been flagged. The following website is the ONLY LEGITIMATE website for that project: **https://murakamiflowers.kaikaikiki.com/**

Please take down the eth-phishing-detect function on this website. I was one of the lucky winners of the public lottery and minted one of the murakami.flowers seeds with no problem using that website. 

If I can be of any more assistance, feel free to reach out to me.

Very truly yours,
Edward Avakian, Esq.

**Comment by devenblake** [comment] 2022-05-05 22:53
Duplicate of #7260.

**Closed by devenblake** 2022-05-05 22:53 UTC
Labels: duplicate, allowlist request
