### ISSUE TITLE
Site paris.cl incorrectly reported as phishing site

### ISSUE THREAD

**Issue by ejosefernandez** [MetaMask/eth-phishing-detect#3623] opened 2020-01-29 12:01 UTC
Web site paris.cl incorrectly reported as a possible phishing site.

**Comment by 409H** [comment] 2020-02-11 22:31
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/3640

**Closed by 409H** 2020-02-11 22:31 UTC
Labels: duplicate, whitelist request
