### ISSUE TITLE
Metamask phising warning of www.empowr.com

### ISSUE THREAD

**Issue by songiso137** [MetaMask/eth-phishing-detect#2854] opened 2019-01-30 14:13 UTC
Kindly remove the warning on my page of www.empowr.com, because it is causing my browser to run very slow. I dont want this red page on my profile of EMPOWR.

**Comment by 409H** [comment] 2019-01-30 16:57
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2663

**Closed by 409H** 2019-01-30 16:57 UTC
