### ISSUE TITLE
[Legitimate Site Blocked] unilayer.app

### ISSUE THREAD

**Issue by dehavenmi** [MetaMask/eth-phishing-detect#5828] opened 2021-11-03 18:58 UTC
https://unilayer.app/

Please continue to flag this crypto site as it is a scam IDO and Airdrop.  Many of us have lost $1000s and were promised airdrops and never happened.  Their IDO was another lie and misrepresented and another loss of huge amount of money.  

Contact form on website doesnt work.  Owner/Developers/Admins deleted Telegram Channels and have refused to discuss any issues via Twitter with any Layer owners.  Many people are super angry and their website and offerings cant be trusted anymore!

SCAM and please never unblock them as others will get hurt!

Many Thanks!

**Comment by devenblake** [comment] 2021-11-03 21:55
Duplicate of #5801.

**Comment by btcgeo** [comment] 2021-11-04 01:02
This is not true, our social media channels are still LIVE, you can verify it here:

https://t.me/Unilayer
https://twitter.com/Unilayer_

**Closed** 2021-12-03 06:16 UTC
Labels: duplicate

**Comment by dehavenmi** [comment] 2021-12-03 15:18
Fuck off and die scamming piece of shit!  U don't deserve to even live or breath the same air.  Scammer!
________________________________
