### ISSUE TITLE
This is a good website - it's incorrectly marked as phishing

### ISSUE THREAD

**Issue by jeevanator** [MetaMask/eth-phishing-detect#840] opened 2018-02-11 03:16 UTC
This is a news website.. Please rectify this and add it to your whitelist. (https://ambcrypto.com)

**Comment by 409H** [comment] 2018-02-11 12:19
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/839

**Closed by 409H** 2018-02-11 12:19 UTC
Labels: whitelist request
