### ISSUE TITLE
 Ethereum Phishing Detection 

### ISSUE THREAD

**Issue by brisco1967** [MetaMask/eth-phishing-detect#3393] opened 2019-10-17 05:21 UTC
why is this always blocking me from login on to my empowr account,  this is happening due to your intervening into my email, STOP STOP STOP with this, iam filing a law suit against your company if you continual to block me,  I never gave you my permission to do this, this is your finial warring.

**Comment by xrn** [comment] 2020-11-16 09:33
Closing. Duplicate of #2663

**Closed by xrn** 2020-11-16 09:33 UTC
