### ISSUE TITLE
[Legitimate Site Blocked] www.arceus.gg

### ISSUE THREAD

**Issue by FraWolf** [MetaMask/eth-phishing-detect#6567] opened 2022-02-03 14:59 UTC
https://www.arceus.gg/ This website is targeted as phishing but its a wiki for Pokémon Legends Arceus game.

**Comment by devenblake** [comment] 2022-02-26 04:55
Fixed by #6546. Duplicate of #6556.

**Closed by devenblake** 2022-02-26 04:55 UTC
Labels: duplicate, allowlist request
