### ISSUE TITLE
URGENT and ASAP [Legitimate Site Blocked] altus.digital

### ISSUE THREAD

**Issue by bradsapkota** [MetaMask/eth-phishing-detect#6348] opened 2022-01-08 00:52 UTC
this site doesn't offer any crypto content or services - please whitelist asap https://altus.digital/

CC @alexneav

**Comment by devenblake** [comment] 2022-01-08 02:12
Duplicate of #6256.

**Comment by bradsapkota** [comment] 2022-01-08 02:27
> Duplicate of #6256.

Do you have an ETA of the fix?

**Comment by devenblake** [comment] 2022-01-08 02:36
> Do you have an ETA of the fix?

No. Please stop filing duplicates - they won't get it fixed any faster. Leaving comments on your initial issue will fill inboxes of watchers of this repository just the same. If you don't want to wait for someone to get around to this issue you can check out pull requests such as [this one](https://github.com/MetaMask/eth-phishing-detect/pull/6075) to get an idea of what a fix looks like.

**Comment by bradsapkota** [comment] 2022-01-08 03:32
> > Do you have an ETA of the fix?
> 
> No. Please stop filing duplicates - they won't get it fixed any faster. Leaving comments on your initial issue will fill inboxes of watchers of this repository just the same. If you don't want to wait for someone to get around to this issue you can check out pull requests such as [this one](https://github.com/MetaMask/eth-phishing-detect/pull/6075) to get an idea of what a fix looks like.

thanks and appreciate your response - there is no other fundamental reason behind chasing for a fix other than our domain has been flagged without any relevancy. 

We have been following up on this issue longer than this [issue](https://github.com/MetaMask/eth-phishing-detect/issues/6060) which seems like it has been resolved.

Could you please explain why a non-crypto offering site has been flagged? This severely affects our operations.

**Comment by devenblake** [comment] 2022-01-08 04:23
>We have been following up on this issue longer than this issue which seems like it has been resolved.

There are hundreds of issues and personally I tend to pick at random ones that look easily actionable (**I'm a hobbyist and not representative of this repository or MetaMask**).

>Could you please explain why a non-crypto offering site has been flagged? This severely affects our operations.

See [the potential src/fuzzylist.md](https://github.com/devenblake/eth-phishing-detect/blob/alphabetize-fuzzylist/src/fuzzylist.md) which explains how the fuzzy-matching works. This isn't an explicit block, just a proactive one (and one that is wrong). Yes, *many* people have complained about this.

I'm going to try to run through a lot of December's issues for my 2021-12 PR but it might take a while because of the sheer volume of filed issues.

**Closed** 2022-01-13 05:31 UTC
