### ISSUE TITLE
[Legitimate Site Blocked] stake.testnet.pulsechain.com

### ISSUE THREAD

**Issue by thadeousofeq** [MetaMask/eth-phishing-detect#6795] opened 2022-03-04 04:50 UTC
https://stake.testnet.pulsechain.com/

This site should not be blocked.  Especially a testnet site.

**Comment by devenblake** [comment] 2022-03-04 05:39
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/6771.

**Closed by devenblake** 2022-03-04 05:39 UTC
Labels: duplicate, allowlist request
