### ISSUE TITLE
STop blocking the Empowr.com

### ISSUE THREAD

**Issue by vighanraj** [MetaMask/eth-phishing-detect#2726] opened 2018-12-14 07:45 UTC
I have no problem with the site ever & don't think anyone should. Using Empowr.com since past couple of years & make good money from it and would advised everyone to ignore metamask warning & use another browser to keep posting & earning as you're doing earlier

Aman ArorA

**Comment by 409H** [comment] 2018-12-14 17:32
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2663

**Closed by 409H** 2018-12-14 17:32 UTC

**Comment by doug9694** [comment] 2019-01-10 03:09
vighanraj: How y making good money? Market place or SC or employee?
