### ISSUE TITLE
[Legitimate Site Blocked] officialnft.xyz

### ISSUE THREAD

**Issue by ldgsxcook** [MetaMask/eth-phishing-detect#7090] opened 2022-04-07 07:20 UTC
https://officialnft.xyz/  OK, what is going on? Why is this taking so long to get resolved? You guys are now costing me money. Nobody wants to go look at my stuff. Because of the block. It's been almost 2 1/2 weeks. Resolved. Is there a reason why? It's not resolved.

**Comment by devenblake** [comment] 2022-04-07 23:39
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/6938.

**Closed by devenblake** 2022-04-07 23:39 UTC
Labels: duplicate, allowlist request
