### ISSUE TITLE
Empowr

### ISSUE THREAD

**Issue by teesider61** [MetaMask/eth-phishing-detect#2721] opened 2018-12-12 01:32 UTC
Please remove the scam alert from this site, you are seriously affecting my time on here.   There is nothing wrong with this site.  Personally I am more concerned with the activities of metamask than I am with the running of Empowr

**Comment by 409H** [comment] 2018-12-12 20:42
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2663

**Closed by 409H** 2018-12-12 20:42 UTC
Labels: duplicate

**Comment by Vhgv2019** [comment] 2019-05-22 19:35
Please remove the scam alert from this site, you are seriously affecting my time on here.
