### ISSUE TITLE
[Legitimate Site Blocked] www.openmeta.foundation

### ISSUE THREAD

**Issue by larry-beck** [MetaMask/eth-phishing-detect#6340] opened 2022-01-06 18:05 UTC
https://www.openmeta.foundation
https://openmeta.foundation

Remove these blocks ASAP, this is our legitimate company/foundation.

**Comment by devenblake** [comment] 2022-01-07 21:32
Duplicate of #6339.

**Closed** 2022-01-13 05:33 UTC
