### ISSUE TITLE
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/phishing.html#hostname=docs.pinksale.finance&href=https%3A%2F%2Fdocs.pinksale.finance%2F

### ISSUE THREAD

**Issue by xOzux** [MetaMask/eth-phishing-detect#6144] opened 2021-12-09 07:47 UTC
https://www.pinksale.finance/

**Comment by devenblake** [comment] 2021-12-09 13:40
Duplicate of #6115.

**Closed** 2021-12-14 01:16 UTC
Labels: duplicate
