### ISSUE TITLE
[Legitimate Site Blocked] metamart.space

### ISSUE THREAD

**Issue by 717natsuki** [MetaMask/eth-phishing-detect#5949] opened 2021-11-17 06:27 UTC
Hi, when I access the website, it still says there is "Ethereum Phishing Detection". 
Could you please check it out?

Thank you,
Natsuki

**Comment by devenblake** [comment] 2021-11-18 07:00
Duplicate of #5922.

**Closed** 2021-11-24 07:27 UTC
