### ISSUE TITLE
[Legitimate Site Blocked] faucet.v2.testnet.pulsechain.com

### ISSUE THREAD

**Issue by LostNCrypto** [MetaMask/eth-phishing-detect#6792] opened 2022-03-04 04:26 UTC
https://faucet.v2.testnet.pulsechain.com/  I have no idea why you believe this is not legit; do you research.

**Comment by devenblake** [comment] 2022-03-04 05:38
Duplicate of #6771.

**Closed by devenblake** 2022-03-04 05:38 UTC
Labels: duplicate, allowlist request
