### ISSUE TITLE
Fake Phishing Confirmed 

### ISSUE THREAD

**Issue by jj3311** [MetaMask/eth-phishing-detect#1432] opened 2018-04-19 17:39 UTC
Hi , 

if we notice is fake , but why the EOS token still appear inside Token transfer & the symbol of token is there ?

How to protect back , if i m using myetherwallet & lock with metamask ???

Thanks for guideline & advice please ......

**Comment by 409H** [comment] 2018-04-19 22:59
Please can you give some screenshots?

**Comment by jj3311** [comment] 2018-04-19 23:33
![image](https://user-images.githubusercontent.com/37726425/39023430-2855256c-446d-11e8-9928-8ec3824e770b.png)

**Comment by 409H** [comment] 2018-04-19 23:44
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/1431

> It is not legitimate. It is phishing for your private keys under the guise of an airdrop - see https://github.com/MetaMask/eth-phishing-detect/commit/a0efc72162592c31b2b3ae6446182bd633091200

**Closed by 409H** 2018-04-19 23:44 UTC
Labels: needs-more-information
