### ISSUE TITLE
[Legitimate Site Blocked] shido.market

### ISSUE THREAD

**Issue by Rhodium14** [MetaMask/eth-phishing-detect#9040] opened 2022-10-22 15:35 UTC
https://shido.market/

It is a legit website , I have bought 10 NFTs from the website and I want to sell them again in this website 

Please open it up, it us very legit 
SHIDO is registered company with fully doxxed team

**Comment by 409H** [comment] 2022-11-07 21:42
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/9037

**Closed by 409H** 2022-11-07 21:42 UTC
Labels: duplicate, allowlist request
