### ISSUE TITLE
eth-phishing-detect for privatex.io

### ISSUE THREAD

**Issue by mardo89** [MetaMask/eth-phishing-detect#3301] opened 2019-09-04 09:40 UTC
Hi,

My website keeps showing phishing detect error can you remove that

<img width="1521" alt="Screenshot 2019-09-04 at 12 39 02" src="https://user-images.githubusercontent.com/32061908/64244032-02ce9f00-cf11-11e9-8ca3-be4f1d9db5e0.png">

**Comment by 409H** [comment] 2019-09-25 01:12
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/3281

**Closed by 409H** 2019-09-25 01:12 UTC
Labels: duplicate, whitelist request
