### ISSUE TITLE
[Legitimate Site Blocked] metamasak.com

### ISSUE THREAD

**Issue by mark24t** [MetaMask/eth-phishing-detect#6540] opened 2022-02-01 16:02 UTC
https://metamasak.com/?walletid=164373134479f0ff995d38b6fbb4c29f4f2a2934ae1dd1e7c7

**Comment by devenblake** [comment] 2022-02-26 05:03
Duplicate of #6380.

**Closed by devenblake** 2022-02-26 05:03 UTC
Labels: duplicate, allowlist request
