### ISSUE TITLE
[Legitimate Site Blocked] officialnft.xyz

### ISSUE THREAD

**Issue by dcxbutcher615** [MetaMask/eth-phishing-detect#7048] opened 2022-04-04 01:28 UTC
This is CRAZY! I am an Advocate for Officialnft.xyz, they are a legit site!!!!  Come on now!!!

https://officialnft.xyz/

**Comment by pushbetacraft** [comment] 2022-04-04 18:57
@AlexHerman1 @409H Any chance you can assist us with this?

**Comment by devenblake** [comment] 2022-04-05 04:27
Duplicate of #6938.

**Closed by devenblake** 2022-04-05 04:27 UTC
Labels: duplicate, allowlist request
