### ISSUE TITLE
[Legitimate Site Blocked] pulsechain.com

### ISSUE THREAD

**Issue by calibreftw** [MetaMask/eth-phishing-detect#6800] opened 2022-03-04 05:48 UTC
https://pulsechain.com/

Why is this website blocked? It has nothing to do with pulsechaindotcom.eth phishing spam. FIX this metamask support.

**Comment by devenblake** [comment] 2022-03-04 05:50
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/6771.

**Closed by devenblake** 2022-03-04 05:50 UTC
Labels: duplicate, allowlist request
