### ISSUE TITLE
[Legitimate Site Blocked] www.pinksale.finance

### ISSUE THREAD

**Issue by Santoad1** [MetaMask/eth-phishing-detect#6148] opened 2021-12-09 08:25 UTC
https://www.pinksale.finance/#/launchpad/0xe9f0Cb79f084ea6bD5A228f144A4F3e77a746758?chain=BSC

**Comment by devenblake** [comment] 2021-12-09 13:42
Duplicate of #6115.

**Closed** 2021-12-14 01:16 UTC
Labels: duplicate
