### ISSUE TITLE
Has this problem been resolved

### ISSUE THREAD

**Issue by ldgsxcook** [MetaMask/eth-phishing-detect#7086] opened 2022-04-07 00:31 UTC
Has this problem been resolved I’m reaching out again trying to figure out when we can get this issue resolved my clients are getting discouraged and I am losing business because of this I sure don’t understand what the holdup is it’s now going on weeks is this how this place operates

**Comment by devenblake** [comment] 2022-04-07 23:39
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/6938.

**Closed by devenblake** 2022-04-07 23:39 UTC
Labels: duplicate, allowlist request
