### ISSUE TITLE
Origin Protocol website being incorrectly flagged

### ISSUE THREAD

**Issue by jacobcantele** [MetaMask/eth-phishing-detect#1454] opened 2018-04-22 19:41 UTC
originprotocol.com is the official website of a reputable project. I'm confused as to why it is being flagged as a phishing site.

**Comment by micahalcorn** [comment] 2018-04-22 19:42
Thanks @jacobcantele! Duplicate of #1452.

**Comment by 409H** [comment] 2018-04-22 20:09
Committed whitelist in https://github.com/MetaMask/eth-phishing-detect/pull/1456

**Closed by 409H** 2018-04-22 20:09 UTC
