### ISSUE TITLE
[Legitimate Site Blocked] mint.adrunner.io

### ISSUE THREAD

**Issue by previoussector** [MetaMask/eth-phishing-detect#6956] opened 2022-03-28 21:12 UTC
https://mint.adrunner.io/

the organized attack on adrunner NFT is especially disgusting considering how new this space is to everyone and this ban benefits nobody. in fact it threatens to de-legitimize the entire NFT space by allowing targeted attacks on projects that have been falsely accused of being scams. look into the person orchestrating the FUD attack. do your due diligence and weed out the REAL perpetrators of false information.

**Comment by devenblake** [comment] 2022-03-29 01:34
Duplicate of #6944.

**Closed by devenblake** 2022-03-29 01:34 UTC
Labels: duplicate, allowlist request
