### ISSUE TITLE
[Legitimate Site Blocked] ww25.btc.bitcoina.us

### ISSUE THREAD

**Issue by rodrigoap22** [MetaMask/eth-phishing-detect#6284] opened 2021-12-28 00:51 UTC
http://ww25.btc.bitcoina.us/?subid1=20211228-1150-21f7-9039-d3bb4e0fa75e

**Comment by devenblake** [comment] 2021-12-28 02:21
Duplicate of #6178.

**Closed** 2022-01-13 01:46 UTC
Labels: duplicate
