### ISSUE TITLE
Pancake Swap

### ISSUE THREAD

**Issue by TheoBeckford** [MetaMask/eth-phishing-detect#4818] opened 2021-03-16 13:03 UTC
Ethereum Phishing Detection on Pancake swap

**Comment by noyseas** [comment] 2021-03-16 13:30
Hope this will be fix now

**Comment by 409H** [comment] 2022-11-07 22:38
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/4803

**Closed by 409H** 2022-11-07 22:38 UTC
Labels: duplicate, allowlist request
