### ISSUE TITLE
Immediately unlock the site https: //www.333eth.io! You interfere with the work of a good project.

### ISSUE THREAD

**Issue by Barloch77** [MetaMask/eth-phishing-detect#2385] opened 2018-09-11 20:40 UTC
Immediately unlock the site https: //www.333eth.io! You interfere with the work of a good project.

**Comment by 409H** [comment] 2018-09-12 00:58
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2374

**Closed by 409H** 2018-09-12 00:58 UTC
