### ISSUE TITLE
[Legitimate Site Blocked] www.pinksale.finance

### ISSUE THREAD

**Issue by 2879174658** [MetaMask/eth-phishing-detect#6149] opened 2021-12-09 11:29 UTC
https://www.pinksale.finance/#/launchpad/0x4c0E39f3051780f17109Ea2c09165DFFD0A48D55?chain=BSC

**Comment by devenblake** [comment] 2021-12-09 13:42
Duplicate of #6115.

**Closed** 2021-12-14 01:16 UTC
Labels: duplicate
