### ISSUE TITLE
Empowr flagged as a supicious site

### ISSUE THREAD

**Issue by AU9USTO** [MetaMask/eth-phishing-detect#2674] opened 2018-11-29 12:20 UTC
How do i turn MetaMask off to interact with this site, empowr.com

Thank you
Francisco

**Comment by 409H** [comment] 2018-11-29 17:35
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2663

On the warning screen you can click the last hyperlink to bypass the block

**Closed by 409H** 2018-11-29 17:35 UTC

**Comment by AU9USTO** [comment] 2018-11-30 10:53
And it redirects me to My Ether Wallet, and from there i have no link, no way to get back to empowr.
Take this link in to concidertion,
https://github.com/MetaMask/eth-phishing-detect/issues/2663

And please correct this ASAP...
Francisco
