### ISSUE TITLE
[Legitimate Site Blocked] my.forms.app

### ISSUE THREAD

**Issue by jiajhenbee** [MetaMask/eth-phishing-detect#9121] opened 2022-10-28 06:14 UTC
We're not able to send surveys by using the Forms.app. Our customers will be blocked if installing your plug-in based on phishing links. I serve Startbahn, and it is a legit and no scam company (
https://startbahn.io/) while using Forms.app to collect customers also not phishing as well.

https://my.forms.app/startbahn/customerfeedbacksurveyja
https://my.forms.app/startbahn/customerfeedbacksurveyen

**Comment by 409H** [comment] 2022-11-07 22:53
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/9131

**Closed by 409H** 2022-11-07 22:53 UTC
Labels: duplicate, allowlist request

**Comment by jiajhenbee** [comment] 2022-11-08 05:34
Thank you so much for helping out!
