### ISSUE TITLE
[Legitimate Site Blocked] officialnft.xyz

### ISSUE THREAD

**Issue by akashhartler** [MetaMask/eth-phishing-detect#7082] opened 2022-04-06 18:02 UTC
https://officialnft.xyz/

Phishing detection warning (invalid)

Please refer - https://github.com/MetaMask/eth-phishing-detect/issues/6938

**Comment by devenblake** [comment] 2022-04-07 23:39
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/6938.

Please don't file duplicate issues.

**Closed by devenblake** 2022-04-07 23:39 UTC
Labels: duplicate, allowlist request
