### ISSUE TITLE
[Legitimate Site Blocked] murakamiflowers.kaikaikiki.com

### ISSUE THREAD

**Issue by dmangahis** [MetaMask/eth-phishing-detect#7310] opened 2022-05-04 02:03 UTC
https://murakamiflowers.kaikaikiki.com/reveal1.html

This is the official site for Murakami's NFT release. There are many fakes out there, which I appreciate MetaMask detecting, but this one is genuite.

**Comment by devenblake** [comment] 2022-05-05 22:53
Duplicate of #7260.

**Closed by devenblake** 2022-05-05 22:53 UTC
Labels: duplicate, allowlist request
