### ISSUE TITLE
asics.com is listed as phishing site?

### ISSUE THREAD

**Issue by sjoerdmulder** [MetaMask/eth-phishing-detect#3614] opened 2020-01-28 13:06 UTC
Not sure what heuristics you are using but if 3 characters of a domain name match it doesn't mean it's a phishing target.

Looking up **asics.com** on https://metamask.github.io/eth-phishing-detect/ => This domain was blocked for its similarity to **oasis.app**, a historical phishing target.

**Comment by Zanndorin** [comment] 2020-01-28 17:09
Same for me but with sabis.se :) 

(similar to oasis)

Real weird implementation

**Comment by 409H** [comment] 2020-02-11 22:35
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/3645

**Closed by 409H** 2020-02-11 22:35 UTC
Labels: duplicate, whitelist request
