### ISSUE TITLE
paris.cl is being flagged incorrectly

### ISSUE THREAD

**Issue by rmujica** [MetaMask/eth-phishing-detect#3618] opened 2020-01-28 20:34 UTC
Paris.cl is one of the biggest department stores in Chile, and is being flagged with no reasons at all.

**Comment by 409H** [comment] 2020-02-11 22:32
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/3640

**Closed by 409H** 2020-02-11 22:32 UTC
Labels: duplicate, whitelist request
