### ISSUE TITLE
 [Legitimate Site Blocked] 

### ISSUE THREAD

**Issue by SlavaKPSS31** [MetaMask/eth-phishing-detect#7525] opened 2022-05-28 08:16 UTC
[Legitimate Site Blocked] binances.club
unblock https://binances.club/

**Comment by devenblake** [comment] 2022-05-28 08:20
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/6696.

**Closed by devenblake** 2022-05-28 08:20 UTC
Labels: duplicate, allowlist request
