### ISSUE TITLE
the new exchange DDEX⇒ http://blogs.empowr.com/p?fpc79-how-to-trade-your-empowr-coins-for-ether

### ISSUE THREAD

**Issue by KaziSiraj** [MetaMask/eth-phishing-detect#2734] opened 2018-12-15 20:02 UTC
From my Empowr account I received a mail where I was working following the instructions for withdrawal my earning money. When I work in DDEX option and MetaMask for going to MetaMask to Etherium Wallet then I have some problems and my Empowr page show me Red Alert MetaMask shown below. Here is the ``attached file'' that mail which was sent to me and I was working by clicking this url DDEX⇒ http://blogs.empowr.com/p?fpc79-how-to-trade-your-empowr-coins-for-ether .  How to escape from this problem now?  Help me regarding this matter.
![the new exchange ddex 2](https://user-images.githubusercontent.com/45091704/50046942-7821e780-00d6-11e9-8667-1a3221069ad3.jpg)

**Comment by xrn** [comment] 2020-11-16 09:35
Closing. Duplicate of #2663

**Closed by xrn** 2020-11-16 09:35 UTC
