### ISSUE TITLE
magendao.com is a legitimate site 

### ISSUE THREAD

**Issue by MagenCommunity** [MetaMask/eth-phishing-detect#6659] opened 2022-02-16 07:13 UTC
magendao.com is a legitimate site that does not gather data from users

MetaX wallet is warning about magendao.com

Please whitelist this domain. We have nothing to do with the other phishing site (makerdao.com)

This is urgent. The phishing warning is a mistake and harming our efforts to create a community DAO

Thank you in advance

**Comment by devenblake** [comment] 2022-02-26 05:17
Duplicate of #6592.

**Closed by devenblake** 2022-02-26 05:17 UTC
Labels: duplicate, allowlist request
