### ISSUE TITLE
MetaStack blocks bitballon.com

### ISSUE THREAD

**Issue by frodoe7** [MetaMask/eth-phishing-detect#1347] opened 2018-04-07 23:15 UTC
this website helps me in the development work
I use it for years and it is not related to bitcoin or crypto-coins anyway !!

**Comment by 409H** [comment] 2018-04-08 01:52
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/1081

Please see my most recent comment: https://github.com/MetaMask/eth-phishing-detect/issues/1081#issuecomment-379458679

**Closed by 409H** 2018-04-08 01:52 UTC
