### ISSUE TITLE
https://gaiaworld.com/ this domain has been flagged incorrectly.

### ISSUE THREAD

**Issue by Garaisble** [MetaMask/eth-phishing-detect#5824] opened 2021-11-03 18:09 UTC
https://gaiaworld.com/ this domain has been flagged incorrectly.

_Originally posted by @Junaid1240651 in https://github.com/MetaMask/eth-phishing-detect/issues/5822#issuecomment-959779906_

**Comment by devenblake** [comment] 2021-11-03 21:49
Duplicate of #5768.

**Closed** 2021-12-03 06:16 UTC
Labels: duplicate
