### ISSUE TITLE
http://telegramfoundation.org/ico/#!/ref#7836264

### ISSUE THREAD

**Issue by andricandra** [MetaMask/eth-phishing-detect#1058] opened 2018-03-02 01:13 UTC

**Comment by 409H** [comment] 2018-03-02 15:27
Can you give more information?

**Comment by 409H** [comment] 2018-03-02 15:49
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/1059 - closing.

**Closed by 409H** 2018-03-02 15:49 UTC
Labels: needs-more-information
