### ISSUE TITLE
[Legitimate Site Blocked] mint.adrunner.io

### ISSUE THREAD

**Issue by Arksaber** [MetaMask/eth-phishing-detect#6976] opened 2022-03-29 03:23 UTC
https://mint.adrunner.io/
This site is wrongfully blacklisted by the Ex Team who uses multiple accounts to report this site.

**Comment by devenblake** [comment] 2022-03-29 04:12
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/6944.

**Closed by devenblake** 2022-03-29 04:12 UTC
Labels: duplicate, allowlist request
