### ISSUE TITLE
[Legitimate Site Blocked] www.millionairegame.org

### ISSUE THREAD

**Issue by Darksidesfear** [MetaMask/eth-phishing-detect#12798] opened 2023-06-12 17:03 UTC
https://www.millionairegame.org/claim-discount

**Comment by millionairegamedev** [comment] 2023-06-13 03:36
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/12800

We're providing information about context for the site in #12800

**Comment by AlexHerman1** [comment] 2023-06-14 17:03
closing this as a duplicate.

**Closed by AlexHerman1** 2023-06-14 17:03 UTC
