### ISSUE TITLE
[Legitimate Site Blocked] junoswap.com

### ISSUE THREAD

**Issue by ivanchiffr** [MetaMask/eth-phishing-detect#7847] opened 2022-06-30 10:14 UTC
https://junoswap.com
The site was erroneously placed on the warning list. This is the official swap of the Juno project. Please do a manual check and remove the site from the warning list

**Comment by devenblake** [comment] 2022-07-01 23:07
Duplicate of #7817.

**Closed by devenblake** 2022-07-01 23:07 UTC
Labels: duplicate, allowlist request
