### ISSUE TITLE
Incorrect flagged empowr

### ISSUE THREAD

**Issue by Manjot13** [MetaMask/eth-phishing-detect#2714] opened 2018-12-09 20:50 UTC
empowr is not a phishing site, I have been working here since 2013, Kindly remove flag immediately. It is my humble request. we are suffering because of this.

**Comment by 409H** [comment] 2018-12-11 00:22
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2663

**Closed by 409H** 2018-12-11 00:22 UTC
Labels: duplicate
