### ISSUE TITLE
[Legitimate Site Blocked] metahak.com

### ISSUE THREAD

**Issue by dis0wned** [MetaMask/eth-phishing-detect#6342] opened 2022-01-07 13:25 UTC
http://metahak.com/

**Comment by devenblake** [comment] 2022-01-07 21:29
Duplicate of #6341.

**Closed** 2022-01-12 23:15 UTC

**Comment by dis0wned** [comment] 2022-01-12 23:43
Did you remove my site from your list?

**Comment by devenblake** [comment] 2022-01-12 23:47
This was closed because it was a duplicate of a standing issue. The previous issue, #6341, has not been closed because it has not been resolved.

**Comment by dis0wned** [comment] 2022-01-13 00:20
What’s to solve? It’s a legitimate website, it’s mine, and I’m selling Amazon affiliate shit on there. 

If you guys want to perpetuate censorship, I can just share this email thread so everyone understands that the plugin “protects” you in ways you may not want….

**Comment by dis0wned** [comment] 2022-01-13 00:22
At no point was this website EVER involved in ethereum or any other Crypto or non crypto scam. You have zero legitimate reasons to block it, if you continue, I’ll blow this up as a censorship issue. It kind of pisses me off that you’re doing this without any legitimate reason other than naming
