### ISSUE TITLE
[Legitimate Site Blocked] metamese.com

### ISSUE THREAD

**Issue by stantechie** [MetaMask/eth-phishing-detect#6531] opened 2022-02-01 06:08 UTC
https://metamese.com/
Another one of my domains for sale blocked by your extension.  Not cool.
This isn't even close to metamask.  There is nothing dangerous about selling a domain name.

**Comment by devenblake** [comment] 2022-02-01 13:26
Duplicate of #6411.

**Closed by devenblake** 2022-02-01 13:26 UTC
Labels: duplicate, allowlist request
