### ISSUE TITLE
[Legitimate Site Blocked] pulsechain.com

### ISSUE THREAD

**Issue by thadeousofeq** [MetaMask/eth-phishing-detect#6794] opened 2022-03-04 04:47 UTC
https://pulsechain.com/

There's no reason why this site should be blocked

**Comment by devenblake** [comment] 2022-03-04 05:38
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/6771.

**Closed by devenblake** 2022-03-04 05:38 UTC
Labels: duplicate, allowlist request
