### ISSUE TITLE
[Legitimate Site Blocked] themaskdao.org

### ISSUE THREAD

**Issue by rich78064** [MetaMask/eth-phishing-detect#6290] opened 2021-12-29 02:05 UTC
https://themaskdao.org/?fbclid=IwAR3Ds72JKjoCexZHB2Df7xQI2PBsqZZbU6pe5tBSEalQYvioDYVo9Vgu7wA

**Comment by devenblake** [comment] 2021-12-29 03:43
Duplicate of #6289; please discuss in #6286.

**Closed** 2022-01-13 00:21 UTC
Labels: duplicate
