### ISSUE TITLE
being blocked

### ISSUE THREAD

**Issue by brisco1967** [MetaMask/eth-phishing-detect#3344] opened 2019-09-21 08:13 UTC
why am i being blocked to log on to empowr

**Comment by 409H** [comment] 2019-09-25 00:11
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2663

**Closed by 409H** 2019-09-25 00:11 UTC

**Comment by brisco1967** [comment] 2019-10-02 07:27
why do I get pinching warnings when I try to sign to my empowr account? it wont let me sign in, stop blocking my sign in, you are not authorized to do this,
