### ISSUE TITLE
DDEX⇒ http://blogs.empowr.com/p?fpc79-how-to-trade-your-empowr-coins-for-ether 

### ISSUE THREAD

**Issue by KaziSiraj** [MetaMask/eth-phishing-detect#2732] opened 2018-12-15 19:33 UTC
From my Empowr account I received a mail where I was working following the instructions for withdrawal my earning money. When I work in DDEX option and MetaMask for going to MetaMask to Etherium Wallet then I have some problems and my Empowr page show me Red Alert MetaMask. Here is pasted below that mail which was sent to me and I was working by clicking this url DDEX⇒ http://blogs.empowr.com/p?fpc79-how-to-trade-your-empowr-coins-for-ether .  How to escape from this problem now?  Help me regarding this matter.
My E-mail Address : kazisiraj65usa@gmail.com
--------

Empowr mail :

Hi Kazi Sirajul Islam, 

You have received a message from your Success Coach. 

Subject: Monthly Customer Survey 

Dear Kazi Sirajul Islam! Thank you for filling out the empowr opinion survey and rated 10 out of 10. That means you are very pleased with how empowr is going so far! I know I really love it here, so I am happy to hear that you feel the same way! I would like to hear if there are any specific functions or ideas that you like in empowr, or any ideas that you need to make our community even better. When you have time, please come back to me and tell me your thoughts! I notice that you have have already All-Time Earnings (pre coins): $8,115,243.76 Great! I would like to inform you the great news. As you all requested, we now have a new exchange to trade our coins, thanks to our new president Carlos and the empowr team. The benefits are: Trading Bonus without the Price Range http://prntscr.com/ld9exi Hitting our Bid goal http://prntscr.com/ld9fan Having fun in trading easily Helping our coin trading volume so that our coin will be one of the dominant coins in the world. Here is how to trade on the new exchange DDEX⇒ http://blogs.empowr.com/p?fpc79-how-to-trade-your-empowr-coins-for-ether Will let me know your feedback about new exchange? Thank you. Best regards, Irina 

— Irina Mikhaylova

**Comment by xrn** [comment] 2020-11-16 09:36
Closing. Duplicate of #2663

**Closed by xrn** 2020-11-16 09:36 UTC
