### ISSUE TITLE
[Legitimate Site Blocked] wallet.elrond.com

### ISSUE THREAD

**Issue by ERAZZLE** [MetaMask/eth-phishing-detect#8919] opened 2022-10-17 10:47 UTC
https://wallet.elrond.com/hook/login?token=121c1dbb2fb2b23b142a9aac9e7ea0cb&callbackUrl=https%3A%2F%2Fmaiar.exchange%2F

unable to access.

**Comment by 409H** [comment] 2022-11-07 22:48
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8870

**Closed by 409H** 2022-11-07 22:48 UTC
Labels: duplicate, allowlist request
