### ISSUE TITLE
metamask phising

### ISSUE THREAD

**Issue by kodamaFR** [MetaMask/eth-phishing-detect#4829] opened 2021-03-16 16:56 UTC
hello,
is it possible to unlock it ?
i dont know why i cant ggo on pancake swap, maybe i did a mistake 
here my metamask adress : 0x17F8406Bea0C2BfBaf0199da4C8F8BDfE45125b7

**Comment by 409H** [comment] 2022-11-07 22:37
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/4803

**Closed by 409H** 2022-11-07 22:37 UTC
Labels: duplicate, allowlist request
