### ISSUE TITLE
WHITE LIST nuclus.io

### ISSUE THREAD

**Issue by mariusvdl01** [MetaMask/eth-phishing-detect#2594] opened 2018-10-19 05:56 UTC
Hi Guys, Please white list our site at nuclus.io or www.nuclus.io as we are about to launch our new marketplace platform. For more information please email us at info@nuclus.co to offer our white paper etc. Kind Regards, Marius

**Comment by tmashuang** [comment] 2018-10-19 18:45
Closing. Duplicate of #2591.

**Closed by tmashuang** 2018-10-19 18:45 UTC
Labels: duplicate, whitelist request
