### ISSUE TITLE
[Legitimate Site Blocked] gaiaworld.com

### ISSUE THREAD

**Issue by Goom1234** [MetaMask/eth-phishing-detect#5788] opened 2021-11-03 14:45 UTC
https://gaiaworld.com/

Gaia has been flagged incorrectly. check your sources before you flag a website. So very unprofessional of you.

**Comment by devenblake** [comment] 2021-11-03 20:08
Duplicate of #5768.

**Closed** 2021-12-03 06:16 UTC
Labels: duplicate
