### ISSUE TITLE
[Legitimate Site Blocked] officialnft.xyz

### ISSUE THREAD

**Issue by ThuRstY617** [MetaMask/eth-phishing-detect#7064] opened 2022-04-04 20:00 UTC
keep getting https://officialnft.xyz/ is not a legitimate site when logging in. Why am I getting this? when https://officialnft.xyz/ is legitim and I've been using it for months now. please fix ASAP

**Comment by devenblake** [comment] 2022-04-05 04:28
Duplicate of #6938.

**Closed by devenblake** 2022-04-05 04:28 UTC
Labels: duplicate, allowlist request
