### ISSUE TITLE
Decentral.market

### ISSUE THREAD

**Issue by soncojmk** [MetaMask/eth-phishing-detect#1327] opened 2018-04-05 17:09 UTC
Metamask has flagged Decentral.market causing any article mentioned on their website to be flagged as well when it is returned from google search results causing damage to credibility. However, there doesn't seem to be any malicious content on this domain and all articles are actually quite informative. If you could please review this and possibly take it down from the malicious list.

**Comment by 409H** [comment] 2018-04-07 15:15
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/951

**Closed by 409H** 2018-04-07 15:15 UTC
Labels: whitelist request
