### ISSUE TITLE
Official website https://murakamiflowers.kaikaikiki.com blocked? Why? 

### ISSUE THREAD

**Issue by IndianaJones007** [MetaMask/eth-phishing-detect#7269] opened 2022-04-29 13:11 UTC
Hello there. I am trying to access the original website of Takashi Murakami for Murakami Flowers.. and i am getting
<img width="1806" alt="Screenshot 2022-04-29 at 1 29 09 PM" src="https://user-images.githubusercontent.com/29165748/165950011-4ac5248d-fe8f-47b5-9f77-f71210dc3741.png">
I am getting this and i am not getting it if i try to open the same website on safari or google incognito mode, only through google chrome where my original metamask account is. I spoke with a live support from your metamask.io website who told me it was reported as a phishing website and thats why i am getting this thing. I was struck like dumbfound like how it is possible? https://twitter.com/takashipom this is the official Takashi Murakami Twitter account and this is his official instagram account: https://www.instagram.com/takashipom/ Both confirm its the official website, i already minted from there.. Also thousands of others people too and the collection is on opensea official already sold in volume of more than 30K ethereum.., also i see i am not the only one posting the same issue here.. Can you check this issue more seriously, i haven't seen anyone on twitter complaining / scammed through the official website provided on his official social media accounts.. If it was really a phishing website he already will have announced it or say he was being hacked.. What exactly is the issue here?

**Comment by devenblake** [comment] 2022-05-05 22:51
Duplicate of #7260.

**Closed by devenblake** 2022-05-05 22:51 UTC
Labels: duplicate, allowlist request
