### ISSUE TITLE
I have been using PancakeSwap and i dont have issues with that - please give me access with METAMASK wallet

### ISSUE THREAD

**Issue by josemacedogoncalves** [MetaMask/eth-phishing-detect#4812] opened 2021-03-16 11:55 UTC
I dont have any issues with PancakeSwap - please give me permission

I take responsabilities

Jose Macedo

Thank you

**Comment by 409H** [comment] 2022-11-07 22:40
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/4803

**Closed by 409H** 2022-11-07 22:40 UTC
Labels: duplicate, allowlist request
