### ISSUE TITLE
[Legitimate Site Blocked] pulsechain.com

### ISSUE THREAD

**Issue by RichardHeart** [MetaMask/eth-phishing-detect#6772] opened 2022-03-04 02:32 UTC
https://pulsechain.com/
https://scan.v2.testnet.pulsechain.com/
https://faucet.v2.testnet.pulsechain.com/

**Comment by g1bbzy** [comment] 2022-03-04 02:42
Agree. Pulsechain.com should be whitelisted. it is a legitimate site.

**Comment by EddyWi** [comment] 2022-03-04 02:43
pulsechain.com and its subdomains should be weitelisted. Not sure why MetaMask is blocking this domain

**Comment by dipwetter** [comment] 2022-03-04 03:01
It would be appreciated if you could look at ASAP.    Pulsechain and subdomains should not  be blocked.

**Comment by vitaminwaterdaisuki** [comment] 2022-03-04 03:03
Yeah. It says wrong network. mmm That's not right. I wonder why all of the sudden now.  Someone must have changed the setting inside the metamask. 

Anyone from Metamask team? Gotta help this man.  He is a very important human.

**Comment by wolfsong3000** [comment] 2022-03-04 03:24
Pulsechain.com is a legitimate project.

**Comment by devenblake** [comment] 2022-03-04 05:35
Duplicate of #6771.

**Closed by devenblake** 2022-03-04 05:35 UTC
Labels: duplicate, allowlist request

**Comment by DEVFEINE** [comment] 2023-10-01 04:16
Thank you richard
