### ISSUE TITLE
[Legitimate Site Blocked] web3nom.com

### ISSUE THREAD

**Issue by NikShev22** [MetaMask/eth-phishing-detect#8778] opened 2022-10-09 09:07 UTC
https://web3nom.com/

**Comment by NikShev22** [comment] 2022-10-10 06:19
![image](https://user-images.githubusercontent.com/115397399/194807980-ecd48258-906b-4ee7-80fb-3c9350a3503f.png)

**Comment by NikShev22** [comment] 2022-10-10 06:20
Our project is not on the phishing list

**Comment by 409H** [comment] 2022-11-07 23:33
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8947

**Closed by 409H** 2022-11-07 23:33 UTC
Labels: duplicate, allowlist request
