### ISSUE TITLE
[Legitimate Site Blocked] gaiaworld.com

### ISSUE THREAD

**Issue by Frozzzensense** [MetaMask/eth-phishing-detect#5774] opened 2021-11-03 14:02 UTC
https://gaiaworld.com/ is a legit site. I took part in investing in this crypto p2e project. There must have been some kind of mistake.

**Comment by devenblake** [comment] 2021-11-03 20:06
Duplicate of #5768.

**Closed** 2021-12-03 06:15 UTC
Labels: duplicate
