### ISSUE TITLE
False Junoswap  phishing message

### ISSUE THREAD

**Issue by Danny4Dayz** [MetaMask/eth-phishing-detect#7835] opened 2022-06-29 20:41 UTC
Hi Metamask,
Can you remove Junoswap from your list of phishing sites? Junoswap is not a phishing site and has tens of
thousands of daily users.  Your message is a slanderous portrayal of the project.
Please fix this asap!
<img width="1432" alt="Screenshot 2022-06-29 at 21 32 14" src="https://user-images.githubusercontent.com/73642327/176540018-e6dc4c52-2fe7-45c1-99bf-bfc29baf66f8.png">

**Comment by devenblake** [comment] 2022-07-01 23:06
Duplicate of #7817.

**Closed by devenblake** 2022-07-01 23:06 UTC
Labels: duplicate, allowlist request
