### ISSUE TITLE
error on flagged site

### ISSUE THREAD

**Issue by mardo89** [MetaMask/eth-phishing-detect#3281] opened 2019-08-29 16:07 UTC
Hi, 

www.privatex.io has phishing error. its flag by mistake

**Comment by 409H** [comment] 2019-09-25 01:11
The legitimate domain is privatix.io - please provide information if I am wrong.

**Comment by mardo89** [comment] 2019-09-25 07:13
Hi, yes, correct domain is www.privatex.io not with i

**Comment by mardo89** [comment] 2019-10-05 07:51
Hi, Can you remove my website from your phishing list its? www.privatex.io.

**Comment by 409H** [comment] 2019-10-31 23:00
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/3405

**Closed by 409H** 2019-10-31 23:00 UTC
Labels: duplicate, whitelist request
