### ISSUE TITLE
[Legitimate Site Blocked] metabase.studio

### ISSUE THREAD

**Issue by genrebase** [MetaMask/eth-phishing-detect#6014] opened 2021-11-25 21:23 UTC
https://metabase.studio/

Hello, please remove this domain from whatever nonsense this is. The domain metabase.studio was registered this morning 24/11/2021 via Google Domains to the company Lovell Group with is DNS set to 46.32.254.31

I checked cryptoscamdb to find no record of the domain.

**Comment by devenblake** [comment] 2021-11-26 22:17
Duplicate of #6005.

**Comment by genrebase** [comment] 2021-11-27 08:20
This is not a duplicate, issues has still not been resolved.

**Closed** 2021-11-30 17:37 UTC
