### ISSUE TITLE
Reader's Digest website reporting as dangerous

### ISSUE THREAD

**Issue by leonardovida** [MetaMask/eth-phishing-detect#2554] opened 2018-10-08 07:45 UTC
As from title, I believe the EPD is not testing correctly RD's domain (https://www.rd.com)

**Comment by 409H** [comment] 2018-10-09 21:33
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2346 (please see the comments on this issue)

**Closed by 409H** 2018-10-09 21:33 UTC
