### ISSUE TITLE
[Legitimate Site Blocked] pulsechain.com

### ISSUE THREAD

**Issue by stephanjoseph** [MetaMask/eth-phishing-detect#6808] opened 2022-03-04 07:21 UTC
https://pulsechain.com/

This site is not spam or phishing please unblock it.

**Comment by devenblake** [comment] 2022-03-05 01:46
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/6771.

**Closed by devenblake** 2022-03-05 01:46 UTC
Labels: duplicate, allowlist request
