### ISSUE TITLE
[Legitimate Site Blocked] www.pinksale.finance

### ISSUE THREAD

**Issue by vunt942** [MetaMask/eth-phishing-detect#6153] opened 2021-12-09 14:11 UTC
https://www.pinksale.finance/#/launchpad/0xb97770a8DC8a37C3289337feB7377da9B826Dea3?chain=BSC

**Comment by devenblake** [comment] 2021-12-09 15:43
Duplicate of #6115.

**Closed** 2021-12-14 01:16 UTC
Labels: duplicate
