### ISSUE TITLE
Pankcake Swap error

### ISSUE THREAD

**Issue by philochs420** [MetaMask/eth-phishing-detect#4787] opened 2021-03-16 02:57 UTC
Hi, I'm getting a warning for using pancake swap on the binance smart chain with my mm wallet, pancake swap is a safe site, it's part of the Binance Smart Chain..

**Comment by goldnutter** [comment] 2021-03-16 05:39
Not an error. They were DNS hijacked to a fake site some time yesterday

DO NOT ENTER YOUR SEED PHRASE ON A SITE 

EVER

**Comment by ethene** [comment] 2021-03-16 06:31
@goldnutter so it has been fixed now, isn't it?

**Comment by cylim** [comment] 2021-03-16 06:47
https://dnschecker.org/#NS/pancakeswap.finance
It is not fully resolved yet. Some is still pointing to problematic DNS.

**Comment by ethene** [comment] 2021-03-17 00:22
https://twitter.com/PancakeSwap/status/1371866176238718984

**Comment by 409H** [comment] 2022-11-07 22:37
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/4803

**Closed by 409H** 2022-11-07 22:37 UTC
Labels: duplicate, allowlist request
