### ISSUE TITLE
[Legitimate Site Blocked] www.lasmeta.io

### ISSUE THREAD

**Issue by lasmio** [MetaMask/eth-phishing-detect#6160] opened 2021-12-09 22:26 UTC
Hello!

Ethereum pshing detect.
![WhatsApp Image 2021-12-10 at 00 25 01](https://user-images.githubusercontent.com/95440086/145485383-99175cdc-a2b6-4198-805c-1858b9d69cfe.jpeg)

We opened an issue to solve the problem 10 days ago, but it has not been resolved yet.
We request your attention please. 

Domain was not published yet.
related domain is www.lasmeta.io

**Comment by devenblake** [comment] 2021-12-10 03:16
Duplicate of #6065.

**Closed** 2021-12-14 01:16 UTC
Labels: duplicate
