### ISSUE TITLE
[Legitimate Site Blocked] form.jotform.com

### ISSUE THREAD

**Issue by kcole16** [MetaMask/eth-phishing-detect#8175] opened 2022-08-11 23:22 UTC
Hey! Jotform is a very popular form-hosting site that is actually available globally (unlike other options). 

This is like blocking Google Forms or Typeform. Please fix!!!

**Comment by miaojiang** [comment] 2022-08-11 23:40
+1, Please fix!

**Comment by raulzklend** [comment] 2022-08-12 03:13
agreed. please fix!

**Comment by 409H** [comment] 2022-11-07 22:12
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8142

**Closed by 409H** 2022-11-07 22:12 UTC
Labels: duplicate, allowlist request
