### ISSUE TITLE
[Legitimate Site Blocked] www.dexfinity.com

### ISSUE THREAD

**Issue by StaniKub** [MetaMask/eth-phishing-detect#5664] opened 2021-10-21 06:41 UTC
I don't think this site should be blocked. It's just a local business site and I can't find it on https://cryptoscamdb.org/search/?

https://www.dexfinity.com/

**Comment by AlexHerman1** [comment] 2022-11-28 17:34
duplicate of #4903

**Closed by AlexHerman1** 2022-11-28 17:34 UTC
