### ISSUE TITLE
[Legitimate Site Blocked] www.futurum.cl

### ISSUE THREAD

**Issue by opogana** [MetaMask/eth-phishing-detect#6761] opened 2022-03-02 13:58 UTC
This site does not contains pishing and it's the official website of a digital agency located in Chile, Agrentina and Perú https://www.futurum.cl/politica-de-privacidad/

**Comment by devenblake** [comment] 2022-04-10 20:10
Duplicate of #6663.

**Closed by devenblake** 2022-04-10 20:10 UTC
Labels: duplicate, allowlist request
