### ISSUE TITLE
[Legitimate Site Blocked] pulsechain.com

### ISSUE THREAD

**Issue by metacencorship** [MetaMask/eth-phishing-detect#6799] opened 2022-03-04 05:45 UTC
https://pulsechain.com
Not a good look-gatekeeping-dissapointing.

**Comment by devenblake** [comment] 2022-03-04 05:45
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/6771.

**Closed by devenblake** 2022-03-04 05:45 UTC
Labels: duplicate, allowlist request
