### ISSUE TITLE
[Legitimate Site Blocked] binances.club

### ISSUE THREAD

**Issue by blablo123** [MetaMask/eth-phishing-detect#6849] opened 2022-03-13 11:51 UTC
Our site contains informational content.
Last year, our design was similar to the original Binance site. Maybe that's why you blocked us. Please unblock.

https://binances.club/

**Comment by devenblake** [comment] 2022-05-06 00:58
Duplicate of #6696.

**Closed by devenblake** 2022-05-06 00:58 UTC
Labels: duplicate, allowlist request
