### ISSUE TITLE
[Legitimate Site Blocked] www.empowr.com

### ISSUE THREAD

**Issue by sksaha61** [MetaMask/eth-phishing-detect#6274] opened 2021-12-27 10:26 UTC
http://www.empowr.com/socnet/EmailStat.aspx?lit=5&me=otUh9vs.UpO4Fqj8rQcy8MUvC.M6npeK3GYqi41Q5Z3jDTk5S4B0ZKcnNhIdVe13CH3WdD.czACokAx4BmQUWhdf-OiC1Pl.cQ0iDC3SPxx64mQJU055Hl3eotBbJ9whRDa.U8QHt3g7yRqP9icQondDMtFYVjh2cp1JIsFfmcuKtBd1Rjyho5WR7UXMo43v&fan=Y8Ca43P1qAMdoWNxwn%2fBbA%3d%3d&opg=http%3a%2f%2fprofile.empowr.com%2fProfile%2fNewCustomProfile.aspx%3fu%3d32c40d477d5f4335aab43f3a02b17088&vet=684&dt=060119&mlid=764734200&tmpID=3212&linkname=ActorProfile&emailNum=1&eaid=yM9KXk6njAlsh2TqFPu%2b7w%3d%3d&rt=12

**Comment by devenblake** [comment] 2021-12-27 22:12
Duplicate of #2663.

**Closed** 2022-01-12 23:08 UTC
