### ISSUE TITLE
[Legitimate Site Blocked] binances.club

### ISSUE THREAD

**Issue by faramsokol** [MetaMask/eth-phishing-detect#7609] opened 2022-06-06 09:53 UTC
Hello. Im look at this window then try to open site https://binances.club/
![1111111122222222](https://user-images.githubusercontent.com/106961398/172138552-b735795f-bca7-46b0-878d-c9b36cebfae7.jpg)

**Comment by devenblake** [comment] 2022-06-10 20:44
Duplicate of #6696.

**Closed by devenblake** 2022-06-10 20:44 UTC
