### ISSUE TITLE
wrong Ethereum Phishing Detection: DECRYPTO

### ISSUE THREAD

**Issue by FranciscoJS12** [MetaMask/eth-phishing-detect#3339] opened 2019-09-19 16:53 UTC
Metamask is blocking access to DECRYPTO exchange. This is a legit exchange that I need to use in order to buy BTC here in Argentina.
https://decrypto.com.ar/ https://decrypto.la

**Comment by 409H** [comment] 2019-09-25 00:14
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/3090

**Closed by 409H** 2019-09-25 00:14 UTC
Labels: duplicate, whitelist request
