### ISSUE TITLE
[Legitimate Site Blocked] nft-fun-game.web.app

### ISSUE THREAD

**Issue by morganchia** [MetaMask/eth-phishing-detect#8435] opened 2022-09-13 13:39 UTC
I am the developer of this site, it got warning the first time i used MetaMask browser to connect to my website. Please explain why and remove it. Thanks.

**Comment by dubstard** [comment] 2022-09-13 15:18
Unfortunately web.app is often abused.

What exactly is nft-fun-game.web.app is there a github repo for this project or some additional details around it?
Moving to a standalone domain would possibly help mitigate this until the issue is resolved.

A few examples:

```
		"accesrewards.web.app",
		"adcon-wall.web.app",
		"assisstedwebdapp.com",
		"assistedwebdapp.com",
		"awe-scan.web.app",
		"blockchain-fixnodes.web.app",
		"coinbase-86aea.web.app",
		"connectwalletv3.web.app",
		"cryptobot-ec6fd.web.app",
		"dapp2022connect.web.app",
		"dappconnectwallet.web.app",
		"dapps-walletsync.web.app",
		"dappsconnection.web.app",
		"decentralizedwebdapp.com",
		"defidapp-net.web.app",
		"defidapps-net.web.app",
		"fastauth2fa.web.app",
		"meta-mask-wallet-security.web.app",
		"metamask-wallets-protection.web.app",
		"metaxdos-wallet-security.web.app",
		"monea-scn.web.app",
		"node.webdapp.site",
		"open-defi-notifications.web.app",
		"polkaweb.app",
		"protocolapps.web.app",
		"rewardsyncdappssconnect.web.app",
		"sensdapps.web.app",
		"solanaclubsystem-net.web.app",
		"syncwldapp.web.app",
		"synslabs.web.app",
		"tofunft-home.web.app",
		"waller-a643a.web.app",
		"wallet-a643a.web.app",
		"wallet-authentication-protocol.web.app",
		"wallet-connect16.web.app",
		"walletconnecte-mobile.web.app",
		"walletlinking.web.app",
		"walletssyncs.web.app",
		"walletsync-connect.web.app",
		"walluserconnect.web.app",
		"web-d0e37.web.app",
		"web-polkadot.web.app",
```

**Comment by morganchia** [comment] 2022-09-16 10:23
> nft-fun-game.web.app

It is an app to mint NFT, meant for an internal company event... 

By the way web.app is the default url for firebase google cloud. No problem switching to another URL... but doesnt sound right to be blacklisted becos of the url suffix.

**Comment by deshvin** [comment] 2023-01-20 19:02
domain is no longer active

**Closed by deshvin** 2023-01-20 19:02 UTC
Labels: allowlist request
