### ISSUE TITLE
[Legitimate Site Blocked] mint.adrunner.io

### ISSUE THREAD

**Issue by Jabo2156** [MetaMask/eth-phishing-detect#6992] opened 2022-03-29 10:25 UTC
https://mint.adrunner.io/ AdRunner is a project with a lot of integrity that is trying to be damaged by former employee. Should not be blocked

**Comment by devenblake** [comment] 2022-04-05 04:29
Duplicate of #6944.

**Closed by devenblake** 2022-04-05 04:29 UTC
Labels: duplicate, allowlist request
