### ISSUE TITLE
Would you please whitelist "Crypto.Market" domain?

### ISSUE THREAD

**Issue by namerapid** [MetaMask/eth-phishing-detect#4188] opened 2020-09-15 05:17 UTC
Hi dev team,

Would you please whitelist the domain "**Crypto.Market**" ? It's for sale on Dan.com for now, there is no content, and for sure is wrongly detected as phishing site.

Thank you very much,

**Comment by Gudahtt** [comment] 2020-11-09 23:14
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/4143

**Closed by Gudahtt** 2020-11-09 23:14 UTC
