### ISSUE TITLE
domein incorect bloclked 

### ISSUE THREAD

**Issue by goranblaz** [MetaMask/eth-phishing-detect#4820] opened 2021-03-16 13:40 UTC
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/phishing.html#hostname=exchange.pancakeswap.finance&href=https%3A%2F%2Fexchange.pancakeswap.finance%2F%3F_gl%3D1*g6z6zl*_ga*MTA0MjY5OTIwMC4xNjEyMDQ5OTUx*_ga_334KNG3DMQ*MTYxMzY3OTUyOS40LjAuMTYxMzY3OTUyOS4w%23%2Fswap

![Capture](https://user-images.githubusercontent.com/62486599/111318640-8704f500-8665-11eb-874b-a9f7607f6984.JPG)

**Comment by 409H** [comment] 2022-11-07 22:41
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/4803

**Closed by 409H** 2022-11-07 22:41 UTC
Labels: duplicate, allowlist request
