### ISSUE TITLE
[Legitimate Site Blocked] openseax.net

### ISSUE THREAD

**Issue by bcoderBSC** [MetaMask/eth-phishing-detect#6052] opened 2021-11-30 11:23 UTC
https://openseax.net/

**Comment by devenblake** [comment] 2021-11-30 15:12
Duplicate of #6043.

**Comment by davidwgrossman** [comment] 2021-12-03 02:37
this seems phishy to me. no discord or twitter page yet?

**Comment by davidwgrossman** [comment] 2021-12-03 02:41
ah you're already on it :P https://github.com/MetaMask/eth-phishing-detect/issues/6043#issuecomment-982025184

**Closed** 2021-12-03 02:42 UTC
Labels: duplicate
