### ISSUE TITLE
Empowr flagged as a supicious site

### ISSUE THREAD

**Issue by AU9USTO** [MetaMask/eth-phishing-detect#2673] opened 2018-11-29 12:13 UTC
Good Morning,

Please restore my access to empowr.com

Thank you
Francisco

**Comment by 409H** [comment] 2018-11-29 17:36
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2663

**Closed by 409H** 2018-11-29 17:36 UTC

**Comment by AU9USTO** [comment] 2018-11-30 10:46
What do you mean by "you authored the thread" please explain what did i do to cause this.

Francisco
