### ISSUE TITLE
eth-phishing-detect

### ISSUE THREAD

**Issue by jeajam45** [MetaMask/eth-phishing-detect#2667] opened 2018-11-27 10:11 UTC
Everytime I'm clicking on my empowr.com, the warning re: phishing keeps on showing. I've downloaded the Ether-Address-Lookup. Am I doing the right way?

**Comment by jeckoz** [comment] 2018-11-27 11:40
scam. 
stay away from that site.

**Comment by 409H** [comment] 2018-11-27 14:40
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2663

**Closed by 409H** 2018-11-27 14:40 UTC

**Comment by jeajam45** [comment] 2018-11-28 09:47
Metamask says I've been scammed. Why is this so? And I've unknowingly encoded my private key when I'm starting to trade which I haven't successfully finished. Please clear out all of those mistakes I've committed if ever I've mistakenly done it. I'm so confused with this newly introduced activity to me. I'm just learning it bit by bit and up to now I haven't done it successfully. I'm already trying to access my account in empowr.com but to no avail. Please advise...
