### ISSUE TITLE
[Legitimate Site Blocked] www.openmeta.xyz

### ISSUE THREAD

**Issue by agustinmr77** [MetaMask/eth-phishing-detect#5954] opened 2021-11-17 11:48 UTC
Hi, our company www.waytoodigital.com just pointed https://www.openmeta.xyz/ to a website we developed for our client Crucible.

So this is not a phishing site! 

Ryan Gill (https://www.linkedin.com/in/ryanagill), founder of Crucible and Open Metaverse, is very active in the blockchain and metaverse community: https://medium.com/subnation/the-open-metaverse-crucible-de0fe04fdbf4 and also on telegram https://t.me/openmetaverse 

Thanks in advance for fixing this ASAP!

**Comment by devenblake** [comment] 2021-11-17 13:27
Duplicate of #5953.

**Closed** 2021-12-03 06:11 UTC
Labels: duplicate
