### ISSUE TITLE
https://pancakeswap.finance/ is fixed

### ISSUE THREAD

**Issue by conradkwu** [MetaMask/eth-phishing-detect#4861] opened 2021-03-17 11:09 UTC
I believe https://pancakeswap.finance/ is fixed its DNS hijack issue but still showing the Ethereum Phishing Detection warning page. Will you please look into it? Cheers.

**Comment by 409H** [comment] 2022-11-07 22:39
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/4803

**Closed by 409H** 2022-11-07 22:39 UTC
Labels: duplicate, allowlist request
