### ISSUE TITLE
[Legitimate Site Blocked] www.infinity.group

### ISSUE THREAD

**Issue by jens247** [MetaMask/eth-phishing-detect#7382] opened 2022-05-14 18:01 UTC
Since I can't reopen ticket #7044, I would like to know why I still get this screenshot when I want to open www.infinity.group:

<img width="1329" alt="Bildschirmfoto 2022-05-14 um 20 01 39" src="https://user-images.githubusercontent.com/76906375/168443409-54fa2400-f21b-455a-bc85-2124a48c3c31.png">

**Comment by devenblake** [comment] 2022-05-14 18:40
I can't reproduce this block - it loads fine for me and it's in the allowlist so it *should* be clear. Marking as a bug.

**Comment by devenblake** [comment] 2022-05-14 18:42
It looks like the filer of #6553 had a similar problem - maybe the caches are in your case taking a really long time to update?

**Comment by jens247** [comment] 2022-05-14 18:51
Can I do anyhting to speed up the process?
The cookies and website data are deleted in my browser.

**Comment by devenblake** [comment] 2022-05-14 20:06
The only advice I can think of is the usual check to make sure the extension is up to date but I don't know that that would help.

**Comment by jens247** [comment] 2022-05-15 08:02
I have the MetaMask extension for Firefox in version 10.12.4 installed since 13th April 2022.
I will wait a few months and check if the problem continues to exist.

**Comment by jens247** [comment] 2022-05-15 10:34
Another try:
I have deinstalled the MetaMask extension: without the MetaMask extension, everything is working fine.
After that, I have installed the MetaMask extension again. When opening www.infinity.group, the following screen appears again:

<img width="1316" alt="Bildschirmfoto 2022-05-15 um 12 34 02" src="https://user-images.githubusercontent.com/76906375/168468439-4b3fee17-c6b8-4c89-b4b1-9eaa0e214c38.png">

**Comment by JohnDoeAlph** [comment] 2022-05-15 14:29
I can confirm it's an extension bug as my web which is blocked in any browser with an extension installed reporting phishing as per above, but other browsers without extension work just fine.

P.S. Crazy to waste time to create a github account just to be able to file a bug, while having nothing to do with coding or development.

**Comment by jens247** [comment] 2022-05-31 05:35
The problem continues to exist:

<img width="1390" alt="Bildschirmfoto 2022-05-31 um 07 33 48" src="https://user-images.githubusercontent.com/76906375/171099990-f906f18b-f260-444c-bc2b-f72b0b0de7b3.png">

The only difference compared to before:
The screen background behind the message is now red.

**Closed** 2023-01-24 23:34 UTC
Labels: bug
