### ISSUE TITLE
[Legitimate Site Blocked] form.jotform.com

### ISSUE THREAD

**Issue by Rpeterson27** [MetaMask/eth-phishing-detect#8168] opened 2022-08-11 17:49 UTC
https://form.jotform.com/221988363204156?isIframeEmbed=1

**Comment by 409H** [comment] 2022-11-07 22:13
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8142

**Closed by 409H** 2022-11-07 22:13 UTC
Labels: duplicate, allowlist request
