### ISSUE TITLE
Meta Mask blocking site

### ISSUE THREAD

**Issue by dimensionless13** [MetaMask/eth-phishing-detect#2463] opened 2018-09-19 11:28 UTC
Good day, MetaMask devs! I'm use your application add chrome a long time. Yesterday tried to open the site 333eth.io in google chrome, but it's locked (blacklist) by MetaMask.

StateOfTheDapps warning, that MetaMask & Ethereum Phishing Detector believe this domain could currently compromise your security and will block you from interacting with it.

https://www.stateofthedapps.com/dapps/333-eth

But, why antivirus progs, like a Avast doesn't block this site as "fishing"?
What is reason locking 333eth.io (blacklist) by MetaMask?
Thanks!

**Comment by 409H** [comment] 2018-09-19 20:38
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2374

**Closed by 409H** 2018-09-19 20:38 UTC

**Comment by Mavrmich** [comment] 2018-09-20 04:30
Yeahhh you look my request! That’s good! Please add 333eth.io to white list! What’s are you waiting?
