### ISSUE TITLE
333eth.io Scam

### ISSUE THREAD

**Issue by ivanhi77** [MetaMask/eth-phishing-detect#2375] opened 2018-09-11 18:04 UTC
Please block 333eth.io is a financial pyramid. Pay selectively and disappear money from a common bank. The developer hid the code and lures new people

**Comment by net968** [comment] 2018-09-11 19:02
not scam!!

**Comment by net968** [comment] 2018-09-11 19:02
The website 333eth.io is not a Scam it is a mistake thank you

**Comment by koka73** [comment] 2018-09-11 19:06
not scam!!
The website 333eth.io is not a Scam it is a mistake thank you

**Comment by SergeyTit** [comment] 2018-09-11 19:07
The site 333eth.io regularly pays all that is promised. Please unlock the site 333eth.io

**Comment by Konstantin48** [comment] 2018-09-11 19:16
333eth.io  is not a scam!!!  This is a crypto game and people participate in it only on their own initiative!

**Comment by DmitryiNevmerzhitskyi** [comment] 2018-09-11 19:19
NOT SCAM!!!
they do not steal any cent!!

**Comment by human228** [comment] 2018-09-11 19:19
Not a scam

**Comment by EtherBomb** [comment] 2018-09-11 19:27
> 
> 
> Idiots, of course it's scam, the code is closed, your money will be stolen!
Idiot - its son of yourth mother! ITS NOT A SCAM!!!!

**Comment by votesher36** [comment] 2018-09-11 19:28
333ETH.IO - IS NOT A SCAM AND NOT A FISHING SITE.
This is the machinations of competitors. Unlock this site, please

**Comment by colorist71** [comment] 2018-09-11 19:33
What are the grounds to claim that the website https://333eth.io a phishing Scam.
I demand to resume work at the site .Check and take action

**Comment by dimonbiliv** [comment] 2018-09-11 19:35
The site does not cheat!!! It is not a Scam!!! With these developers are not working in the first project!!! The message about Scam - intrigues of competitors!!!

**Comment by dimonbiliv** [comment] 2018-09-11 19:36
Че там за Ваня77 бля? В уши хуями его!!!

**Comment by sashok76rus** [comment] 2018-09-11 19:48
333eth.io это не скам он всем стабильно выплачивает. Эту кляузу вам написали их конкуренты. Будьте благоразумны, не ведитесь на их провокацию!!!!!!!!!!!!

**Comment by korsik1** [comment] 2018-09-11 19:51
It is not a SCAM, real project!
I'm not professional user on crypto, but i've received ETH on my valet everyday!

**Comment by Mitoko61** [comment] 2018-09-11 19:54
NOT SCAM!!! NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!NOT SCAM!!!

**Comment by neonwolf00** [comment] 2018-09-11 19:54
Please remove the restriction from the site 333eth.io. The project is working. I'm an investor and I use the MetaMask application. I ask to withdraw the site from the blacklist. I've been working with project 333eth.io since the beginning of its discovery.

**Comment by barzelgor** [comment] 2018-09-11 19:56
Greetings . Please take steps to resume normal login to the site 333eth.io. We are more than 2000 active users and investors of this project. The team fulfills its obligations by 100%. Payments in the project occur automatically. This is not Skam project. Thank you .

**Comment by neonwolf00** [comment] 2018-09-11 19:58
Прошу снять ограничение из сайта 333eth.io. Проект работает. Я инвестор и пользуюсь приложением MetaMask. Прошу вывести сайт 333eth.io из черного списка. Я работаю с проектом 333eth.io с начала его открытия.

**Comment by GooddayAlex** [comment] 2018-09-11 20:06
Прошу тоже снять ограничения с сайта 333eth. Мы используем metamask для своих инвестиций ! Сайт и проект не фишинговые и отлично работающие ! Просьба принять обратные меры !

**Comment by neonwolf00** [comment] 2018-09-11 20:09
I ask you to remove the site 333eth.io from the blacklist. The site 333eth.io is entered by mistake in the black list MetaMask. Dear support, I am an investor of this site. Unblock the site 333eth.io and put everything back in place. The site 333eth.io is on the blacklist erroneously due to competitors.

**Comment by SenatorM** [comment] 2018-09-11 20:13
Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!Shit SCAM!!!!

**Comment by SenatorM** [comment] 2018-09-11 20:14
Fucking proprietary code, people get hurt, not enough for you?

**Comment by korsik1** [comment] 2018-09-11 20:15
web-site 333eth.io and this project not a SCAM and not a phishing site!
I ask to remove 333eth.io from blacklist!
Smart contract worked well. I'm Investor who visited 333.io within 5 days, before it blocked.
Accordingly to rules, which was showed on a web-site 333.io, I've received ETH on my wallet everyday.
I'm used Metamask for invest.

**Comment by sashok76rus** [comment] 2018-09-11 20:37
Это все пиздеж по русски 
Проект отличный 
Срочно разблокируйте сайт.

**Comment by TeamXXI** [comment] 2018-09-11 20:49
This is not a scam! The contract regularly pays all its investors, please remove the restriction metamask on the site 333eth.io
It was added by mistake because of the competitive environment.
Thank you!

**Comment by Barloch77** [comment] 2018-09-11 20:51
Immediately unlock the site https: //www.333eth.io! You interfere with the work of a good project.

**Comment by molotoks** [comment] 2018-09-11 20:51
Пожалуйста metamask разблокируй этот сайт.

**Comment by Barloch77** [comment] 2018-09-11 21:05
Freedom https: //www.333eth.io! Remove the site from the blacklist. You are violating the rights of investors! Metamask must release 333eth.io !!!

**Comment by 409H** [comment] 2018-09-12 01:00
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2374

**Closed by 409H** 2018-09-12 01:00 UTC

**Comment by volangRoss** [comment] 2018-09-12 02:06
Разблокируйте  проект выплачивает деньги вкладчиков это НЕ Скам
