### ISSUE TITLE
[Legitimate Site Blocked] form.jotform.com

### ISSUE THREAD

**Issue by raulzklend** [MetaMask/eth-phishing-detect#8147] opened 2022-08-11 09:50 UTC
Hello, this is Raul from the zkLend team. 

We launched week 3 of our ZEND University campaign earlier today and noticed that when users who have Metamask extension installed on their browser and try to access our Jotform quiz (https://form.jotform.com/222200797328455) they receive the following message:
![image](https://user-images.githubusercontent.com/111051607/184106514-5a023de8-b265-4f0e-bfce-39c4f2e5b775.png)

We are not phishing for wallet addresses. The reason we are collecting Polygon wallet addresses is to send winners their prizes. The reason we are collecting Argent X wallet addresses is to whitelist them so they can access our Testnet that was recently launched. 

You can find more information on our ZEND University campaign below:
https://medium.com/zklend/welcome-to-zend-university-cec6c47c3801

**Comment by 409H** [comment] 2022-11-07 22:16
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8142

**Closed by 409H** 2022-11-07 22:16 UTC
Labels: duplicate, allowlist request
