### ISSUE TITLE
[Legitimate Site Blocked] tezos.finance

### ISSUE THREAD

**Issue by KevinMehrabi** [MetaMask/eth-phishing-detect#9692] opened 2022-11-28 20:02 UTC
https://tezos.finance/ is a legitimate website application from reputable developers. The application is by [StableTech](https://stable.tech) and VC-backed by [Draper Goren Holm](https://drapergorenholm.com). The website application does not even facilitate Metamask wallets, nor any EVM wallet for that matter. It is strictly on the Tezos network.

Please unblock and verify this website.

Our social media is:
[https://twitter.com/tezosfinance](https://twitter.com/tezosfinance)
[https://discord.gg/tezosfinance](https://discord.gg/tezosfinance)
[https://medium.com/tezosfinance](https://medium.com/tezosfinance)
[https://telegram.com/tezosfinance](https://telegram.com/tezosfinance)

**Comment by 409H** [comment] 2022-11-30 20:13
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/9693

**Closed by 409H** 2022-11-30 20:13 UTC
Labels: duplicate, allowlist request
