### ISSUE TITLE
[Legitimate Site Blocked] foundation.app

### ISSUE THREAD

**Issue by gabycarfe17** [MetaMask/eth-phishing-detect#8609] opened 2022-09-29 14:33 UTC
Hello! I'm an legit artist with a couple projects on OpenSea as you can see here:
https://opensea.io/MGC-Star

A few days ago, I created a new project on foundation, but now metamask took it as a phishing, it's just art, please review and restore my project, I'm not a scammer.
https://foundation.app/collection/poppiespopV2?sortOrder=DEFAULT

**Comment by 409H** [comment] 2022-11-07 22:00
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8588

**Closed by 409H** 2022-11-07 22:00 UTC
Labels: duplicate, allowlist request
