### ISSUE TITLE
[Legitimate Site Blocked] metadesk.run

### ISSUE THREAD

**Issue by litestar-app** [MetaMask/eth-phishing-detect#6607] opened 2022-02-10 04:41 UTC
https://metadesk.run/

We are providing the service for running Unreal Engine/Unity in the cloud, it is definitely not sketchy! Please unblock this website asap.

Thanks

(Metadesk.io was the sketchy site!)

**Comment by devenblake** [comment] 2022-02-22 04:34
Duplicate of #6606.

**Closed by devenblake** 2022-02-22 04:34 UTC
Labels: duplicate, allowlist request
