### ISSUE TITLE
[Legitimate Site Blocked] officialnft.xyz

### ISSUE THREAD

**Issue by dcxbutcher615** [MetaMask/eth-phishing-detect#7043] opened 2022-04-02 08:05 UTC
hello this isnt a scammy site! I have bought and have sold on this site! what is up with this?
this false warning is turning away people! l Know it not a scam! 3rd time I have stood with officialnft!

https://officialnft.xyz/

**Comment by devenblake** [comment] 2022-04-05 04:27
Duplicate of #6938.

**Closed by devenblake** 2022-04-05 04:27 UTC
Labels: duplicate, allowlist request
