### ISSUE TITLE
[Legitimate Site Blocked] docs.pinksale.finance

### ISSUE THREAD

**Issue by QuintanilhaM** [MetaMask/eth-phishing-detect#6121] opened 2021-12-08 22:47 UTC
https://docs.pinksale.finance/important/contract-developers

unfortunately I'm being blocked on the pink sale without knowing why.

**Comment by devenblake** [comment] 2021-12-09 03:56
Duplicate of #6115.

**Closed** 2021-12-14 01:17 UTC
Labels: duplicate

**Comment by nshCore** [comment] 2022-02-01 16:17
> https://docs.pinksale.finance/important/contract-developers
> 
> unfortunately I'm being blocked on the pink sale without knowing why.

they were originally blocked because they knowingly allowed fake tokens to be listed on their platform, took the money and fees and didnt return them to the users bu @devenblake didnt think that was a reason enough to have them blacklisted from metamask and unblacklisted them allowing them to continue to scam their users
