### ISSUE TITLE
DNS propagated on PancakeSwap

### ISSUE THREAD

**Issue by loicgottwalles** [MetaMask/eth-phishing-detect#4835] opened 2021-03-16 18:56 UTC
The DNS is propagated, I mean back to normal on PancakeSwap (see their Twitter). You can lift the warning message, everything is safe again.

**Comment by 409H** [comment] 2022-11-07 22:40
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/4803

**Closed by 409H** 2022-11-07 22:40 UTC
Labels: duplicate, allowlist request
