### ISSUE TITLE
[Legitimate Site Blocked] web3nom.com

### ISSUE THREAD

**Issue by Admiral** [MetaMask/eth-phishing-detect#8862] opened 2022-10-15 21:05 UTC
https://web3nom.com/ru/office/profile/update?alias=insertWallet

**Comment by 409H** [comment] 2022-11-07 23:34
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8947

**Closed by 409H** 2022-11-07 23:34 UTC
Labels: duplicate, allowlist request
