### ISSUE TITLE
[Legitimate Site Blocked] www.empowr.com

### ISSUE THREAD

**Issue by sksaha61** [MetaMask/eth-phishing-detect#6281] opened 2021-12-27 10:28 UTC
http://www.empowr.com/socnet/EmailStat.aspx?lit=5&me=otUh9vs.UpO4Fqj8rQcy8MUvC.M6npeK3GYqi41Q5Z3jDTk5S4B0ZKcnNhIdVe13IDI-elFaNT9MjshdTf1XqBKWj6Sk1eOD8YNVCVPjiuyVoBFSozQw.qQjkZlJGGmdpGBlVjOOBTSZRxs2ykj0ubzdNoffD2olSnprAPQQ79s1i.wVYmO1GoKrECPLAImB&fan=Y8Ca43P1qAMdoWNxwn%2fBbA%3d%3d&opg=http%3a%2f%2fwww.empowr.com%2fProvide%2fMyListings.aspx%3fcreate%3d1%26amp%3btype%3dproduct&vet=684&dt=060119&mlid=764734200&tmpID=3212&linkname=ListLink&emailNum=1&eaid=yM9KXk6njAlsh2TqFPu%2b7w%3d%3d&rt=12

**Comment by devenblake** [comment] 2021-12-27 22:13
Duplicate of #2663.

**Closed** 2022-01-12 23:10 UTC
