### ISSUE TITLE
[Legitimate Site Blocked] www.metapass.world

### ISSUE THREAD

**Issue by alivira** [MetaMask/eth-phishing-detect#5918] opened 2021-11-13 03:33 UTC
https://www.metapass.world/

This is my friend's website, looks like it's being blocked? Curious why - legitimate afaik, just a logo & a waitlist

**Comment by devenblake** [comment] 2021-11-13 03:34
Duplicate of #5916.

I'm drafting a PR that adds this to the allowlist, don't worry. :)

**Comment by alivira** [comment] 2021-11-13 03:34
Oops, sorry for the dupe. Thanks devenblake!

**Closed** 2021-11-16 01:58 UTC
