### ISSUE TITLE
[Legitimate Site Blocked] stake.v2.testnet.pulsechain.com

### ISSUE THREAD

**Issue by CoZaFrenzy** [MetaMask/eth-phishing-detect#6807] opened 2022-03-04 06:46 UTC
https://stake.v2.testnet.pulsechain.com/connect

Yo! WTF!? what the cracks is this? Are you on crack? This has been live for months. Please reopen it.

**Comment by devenblake** [comment] 2022-03-05 01:46
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/6771.

**Closed by devenblake** 2022-03-05 01:46 UTC
Labels: duplicate, allowlist request
