### ISSUE TITLE
[Legitimate Site Blocked] www.popcorncash.io

### ISSUE THREAD

**Issue by lucacolella** [MetaMask/eth-phishing-detect#7320] opened 2022-05-04 16:26 UTC
When I request access to a platform, this message appears.
What are the reasons?
I authorize METAMASK to let me access the site https://www.popcorncash.io

**Comment by devenblake** [comment] 2022-05-05 22:47
Duplicate of #7314.

**Closed by devenblake** 2022-05-05 22:47 UTC
Labels: duplicate, allowlist request
