### ISSUE TITLE
ETH Phishing Recheck for kactus.com

### ISSUE THREAD

**Issue by Thesalmar** [MetaMask/eth-phishing-detect#3282] opened 2019-08-30 10:03 UTC
Hello,

I had a warning from the extension and i've checked the website with two databases to ensure if it was legitimate. Well, it was negative (so no signs of phishing)

Can you recheck on your side ?

Thank you very much :)

**Comment by 409H** [comment] 2019-09-25 01:08
Closing. Duplicate of https://urlscan.io/result/c915f37d-5efd-472b-b9bf-c88a0ba7848b/

**Closed by 409H** 2019-09-25 01:08 UTC
Labels: duplicate, whitelist request
