### ISSUE TITLE
[Legitimate Site Blocked] uniswap.v2.testnet.pulsechain.com

### ISSUE THREAD

**Issue by CoZaFrenzy** [MetaMask/eth-phishing-detect#6806] opened 2022-03-04 06:45 UTC
https://uniswap.v2.testnet.pulsechain.com/#/swap

Yo guys, what is going on. Open it back. Open now. We will abandon Metamask all together. Please do  it soon.

**Comment by devenblake** [comment] 2022-03-05 01:45
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/6771.

**Comment by devenblake** [comment] 2022-03-05 01:45
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/6771.

**Closed by devenblake** 2022-03-05 01:45 UTC
Labels: duplicate, allowlist request
