### ISSUE TITLE
Wrong Blacklist

### ISSUE THREAD

**Issue by Joby143** [MetaMask/eth-phishing-detect#2661] opened 2018-11-26 23:56 UTC
empowr.com should not be blacklisted. Please fix this issue at once. You are blocking from earning money.

**Comment by 409H** [comment] 2018-11-26 23:58
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2660

**Closed by 409H** 2018-11-26 23:58 UTC

**Comment by PERTHEKAT** [comment] 2019-01-21 22:15
YOUR MAKED MONEY NEVER BECOME PAID TO YOU. THATS HOW SCAMPOWER WORK.
THIS SITE AND IT PREDECESSORS FANBOX AND SMS INC ARE KNOWN THEVES. PUT EMPOWR IN WIKIPEDIA AND READ PLEASE.
![zrzut ekranu z 2019-01-12 12-38-35](https://user-images.githubusercontent.com/46899037/51501424-26a20200-1dd2-11e9-8fd4-603a4556d96a.png) 
THIS MONEY ARE IMPOSSIBLE TO PAY. NO WAY EMPOOR MADE IT!!!!!
