### ISSUE TITLE
We're not able to send surveys using Forms.app

### ISSUE THREAD

**Issue by nadim-hussain** [MetaMask/eth-phishing-detect#9119] opened 2022-10-28 05:55 UTC
We're not able to send surveys using Forms.app. How can you block the whole domain for some phishing links. This is getting annoying.

**Comment by 409H** [comment] 2022-11-07 23:23
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/9131

**Closed by 409H** 2022-11-07 23:23 UTC
Labels: duplicate, allowlist request
