### ISSUE TITLE
[Legitimate Site Blocked] ltcminer.com

### ISSUE THREAD

**Issue by The-funny-man** [MetaMask/eth-phishing-detect#7374] opened 2022-05-12 22:51 UTC
https://ltcminer.com/home

real stite been using it for a year and a half

**Comment by devenblake** [comment] 2022-05-13 02:10
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/4472.

**Closed by devenblake** 2022-05-13 02:10 UTC
Labels: duplicate, allowlist request
