### ISSUE TITLE
[Legitimate Site Blocked] www.empowr.com

### ISSUE THREAD

**Issue by sksaha61** [MetaMask/eth-phishing-detect#6273] opened 2021-12-27 10:20 UTC
http://www.empowr.com/socnet/EmailStat.aspx?lit=5&me=otUh9vs.UpO4Fqj8rQcy8MUvC.M6npeK3GYqi41Q5Z2Zdgdn4YecSYwxxiP2Jf.ulMS.uJ.KUpOvy1xQ4rrp7VD1DCD1JNuF-AEX1Dc1k6LDFZ01NKIIcefEstof-h.oFFzKOj.XwyahpclUTP87AjvKLds308k5Y1WNM44oLyam3ukMiXc3M3BNzAp5Qbyk&fan=F1Qw1zM6IEk%3d&opg=https%3a%2f%2fsecure.empowr.com%2fPremiumBlogs%2fAccountSecurityEntrance.aspx%3fFlowFlavor%3dEthereumAccountCompletion&vet=616&dt=060119&mlid=10744753772&tmpID=1&linkname=Validation&emailNum=0&eaid=yM9KXk6njAlsh2TqFPu%2b7w%3d%3d&rt=13

**Comment by devenblake** [comment] 2021-12-27 22:12
Duplicate of #2663.

**Closed** 2022-01-12 23:07 UTC
