### ISSUE TITLE
METAMASK wont allow me on PANCAKESWAP

### ISSUE THREAD

**Issue by kotnik77** [MetaMask/eth-phishing-detect#4804] opened 2021-03-16 09:37 UTC
Hi, i want to ask why won't metamask allow me on pancake swap?

**Comment by 409H** [comment] 2022-11-07 22:38
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/4803

**Closed by 409H** 2022-11-07 22:38 UTC
Labels: duplicate, allowlist request
