### ISSUE TITLE
false positive: *.usermd.net

### ISSUE THREAD

**Issue by sztvka** [MetaMask/eth-phishing-detect#4562] opened 2020-12-26 13:54 UTC
The subdomain *.usermd.net is tied to the polish hosting site www.mydevil.net
Metamask shows a warning on every site using that subdomain, even if the site is not crypto-related.

Example: https://katemedia.pl/   -- only the landing page doesn't feature a subdomain.
https://katemedia.usermd.net/baterie/363-bateria-oryginal-iphone-7-.html  -- an example product listing

This site only sells phone parts and doesn't even feature a crypto payment option.
I think that the filter should only target a selected group of subdomains, not all of them.

**Comment by devenblake** [comment] 2022-01-09 20:58
Duplicate of #3520.

**Closed** 2022-01-13 00:27 UTC
Labels: duplicate, allowlist request
