### ISSUE TITLE
[Legitimate Site Blocked] metamasak.com

### ISSUE THREAD

**Issue by jprevost8** [MetaMask/eth-phishing-detect#6416] opened 2022-01-16 14:35 UTC
https://metamasak.com/?walletid=1642343655a1afd4fb6b1cf5b4ff9a97bbd12b105a5d69e657
 hi there i was trying to buy some ETH than all of a sudden I cant go into the website

**Comment by devenblake** [comment] 2022-01-16 14:51
Duplicate of #6380.

**Closed by devenblake** 2022-01-16 14:51 UTC
Labels: duplicate, allowlist request

**Comment by jprevost8** [comment] 2022-01-16 14:59
i was trying to buy an amount of 500 ETH but it didn't let me proceed it. could you reset the issue so i could buy my ETH

**Comment by devenblake** [comment] 2022-01-18 05:55
Please use **`metamask.io`** to access MetaMask. You were accessing **`metamasak.com`**, which was trying to scam you out of your money.
