### ISSUE TITLE
[Legitimate Site Blocked] binances.club

### ISSUE THREAD

**Issue by RobertoFlorese** [MetaMask/eth-phishing-detect#7537] opened 2022-05-29 14:52 UTC
A big request to the developers of the project is to remove the blacklist from the site. 
Hope for understanding!

Best regards!

**Comment by devenblake** [comment] 2022-05-31 04:19
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/6696.

**Closed by devenblake** 2022-05-31 04:19 UTC
Labels: duplicate, allowlist request
