### ISSUE TITLE
[Legitimate Site Blocked] pieceofshit.wtf

### ISSUE THREAD

**Issue by undefined33** [MetaMask/eth-phishing-detect#7660] opened 2022-06-10 12:57 UTC
https://pieceofshit.wtf/

**Comment by undefined33** [comment] 2022-06-10 12:58
do your guys don't see opensea treading? damn,it is legitimate website,so stupid

**Comment by devenblake** [comment] 2022-06-10 22:29
Duplicate of #7653.

**Closed by devenblake** 2022-06-10 22:29 UTC
Labels: duplicate, allowlist request
