### ISSUE TITLE
[Legitimate Site Blocked] my.forms.app

### ISSUE THREAD

**Issue by nadim-hussain** [MetaMask/eth-phishing-detect#9116] opened 2022-10-28 05:51 UTC
https://my.forms.app/form/635a66f7de455f6e2c931840

**Comment by 409H** [comment] 2022-11-07 22:52
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/9131

**Closed by 409H** 2022-11-07 22:52 UTC
Labels: duplicate, allowlist request
