### ISSUE TITLE
Incorrectly blocking fass.se.

### ISSUE THREAD

**Issue by jav** [MetaMask/eth-phishing-detect#3629] opened 2020-01-30 15:51 UTC
Fass.se is a swedish medical information site.
It's wrongly blocked by eth-phising-detect.

**Comment by 409H** [comment] 2020-02-11 22:25
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/3667

**Closed by 409H** 2020-02-11 22:25 UTC
