### ISSUE TITLE
Please remove our domain from your lists. 

### ISSUE THREAD

**Issue by klitovskiy** [MetaMask/eth-phishing-detect#4670] opened 2021-02-10 02:56 UTC
Please remove our domain vcinity.io from your lists, and any other vcinity.org/.com/etc.

Thank You

**Comment by klitovskiy** [comment] 2021-02-11 18:27
Has there been any progress on this? Can we please have our domains removed from your block list?

**Comment by klitovskiy** [comment] 2021-03-05 20:17
Are these issues even being monitored? Its been almost a month. Can someone please address this?

**Comment by devenblake** [comment] 2022-01-11 16:02
Duplicate of #4642.

**Closed** 2022-01-13 01:39 UTC
Labels: duplicate
