### ISSUE TITLE
[Legitimate Site Blocked] ltcminer.com

### ISSUE THREAD

**Issue by obadadallo95** [MetaMask/eth-phishing-detect#5856] opened 2021-11-06 09:52 UTC
https://ltcminer.com/?__cf_chl_jschl_tk__=GTg5PJjbT58HP_0BdyhR0HdgX7MR.8RaTQeCvsZhCoc-1636192272-0-gaNycGzNB30

**Comment by devenblake** [comment] 2021-11-06 12:59
Site was explicitly added to the blocklist with commit [8baf01559](https://github.com/MetaMask/eth-phishing-detect/commit/8baf01559) by @409H.

**Comment by devenblake** [comment] 2022-01-13 01:35
Duplicate of #4472.

**Closed by devenblake** 2022-01-13 01:35 UTC
Labels: duplicate
