### ISSUE TITLE
Metamask detects etherzero site as phishing site

### ISSUE THREAD

**Issue by nstefi** [MetaMask/eth-phishing-detect#711] opened 2018-01-21 01:09 UTC
When I tried to access the website of etherzero, (http://etherzero.org) I got forwarded by Metamask to a page saying that the site is a phishing site, and was detected by "Ethereum Phishing Detector".
This was the message:
"ATTENTION
MetaMask believes this domain to have malicious intent and has prevented you from interacting with it.
This is because the site tested positive on the Ethereum Phishing Detector.
You can turn MetaMask off to interact with this site, but it's advised not to.
If you think this domain is incorrectly flagged, please file an issue."

Is that site really a phishing site? That means the ETZ coing that appeared from an ETH fork is a scam?

Thanks,
Steven

**Comment by ligi** [comment] 2018-01-21 12:01
duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/653

**Closed** 2018-01-21 14:06 UTC
