### ISSUE TITLE
empow'r.com

### ISSUE THREAD

**Issue by AngryJohn** [MetaMask/eth-phishing-detect#2736] opened 2018-12-16 21:06 UTC

**Comment by AngryJohn** [comment] 2018-12-16 21:08
I've been using this site for too long for you now to come and interfere

**Comment by 409H** [comment] 2018-12-17 15:18
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2663

**Closed by 409H** 2018-12-17 15:18 UTC
Labels: duplicate
