### ISSUE TITLE
[Legitimate Site Blocked] pulsechain.com

### ISSUE THREAD

**Issue by calibreftw** [MetaMask/eth-phishing-detect#6798] opened 2022-03-04 05:41 UTC
https://pulsechain.com/

pulsechain.com is not related to pulsechaindotcom.eth address.... how on earth would you mix up those two?

**Comment by devenblake** [comment] 2022-03-04 05:43
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/6771.

**Closed by devenblake** 2022-03-04 05:43 UTC
Labels: duplicate, allowlist request
