### ISSUE TITLE
[Legitimate Site Blocked] pulsechain.com

### ISSUE THREAD

**Issue by WNOTN** [MetaMask/eth-phishing-detect#6774] opened 2022-03-04 03:01 UTC
https://pulsechain.com/

There is no issue on this site. There is nothing to deem this suspicious or for it to be blocked.

https://wnotn.medium.com/the-pulsechain-a-better-fork-of-a-fork-873b3a52495b

**Comment by devenblake** [comment] 2022-03-04 05:36
Duplicate of #6771.

**Closed by devenblake** 2022-03-04 05:36 UTC
Labels: duplicate, allowlist request
