### ISSUE TITLE
[Legitimate Site Blocked] officialnft.xyz

### ISSUE THREAD

**Issue by pushbetacraft** [MetaMask/eth-phishing-detect#7035] opened 2022-04-01 15:52 UTC
https://officialnft.xyz/

We don't collect any user signing keys and we don't Impersonate other known and established sites.

The [tool](https://metamask.github.io/eth-phishing-detect/) provided to check the reason for blocking says there is no problem with our website. Please check screenshot below. We request to stop showing the phishing error on our website

![160387525-ab38a2e3-1306-462a-ac83-c99a2643facc](https://user-images.githubusercontent.com/89087401/161298681-7d39ea70-ec64-48bc-9c4a-86935afac61f.png)

**Comment by pushbetacraft** [comment] 2022-04-01 15:57
@AlexHerman1 @409H Any chance you can assist us with this?

**Comment by pushbetacraft** [comment] 2022-04-04 18:56
@AlexHerman1 @409H Any chance you can assist us with this?

**Comment by devenblake** [comment] 2022-04-05 04:27
Duplicate of #6938.

**Closed by devenblake** 2022-04-05 04:27 UTC
Labels: duplicate, allowlist request
