### ISSUE TITLE
 please wish your cooperation on how to get my account started.

### ISSUE THREAD

**Issue by Kawsarjahanshimo** [MetaMask/eth-phishing-detect#2952] opened 2019-03-11 08:46 UTC
My name is Kawsar Jahan Shimo. I am a Bangladeshi citizen My district is Feni . I have an account at  w.w.w  empowr.com. My Account's
Name is w.w.w. empowr com / kawsar jahan shimo My password is being
Kawsar00789      About fifteen days before, I can not bid ,  like, share, at my empowr account. My etheriam phising is being written Because of my mistake unknown to my mind reading my account Phising. Please wish your cooperation on how to get my account started. My Gmail account is kawsarjahan007@gmail.com

**Comment by 409H** [comment] 2019-03-12 21:53
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2663

**Closed by 409H** 2019-03-12 21:53 UTC
