### ISSUE TITLE
[Legitimate Site Blocked] metamart.space

### ISSUE THREAD

**Issue by takahiro-1123** [MetaMask/eth-phishing-detect#5928] opened 2021-11-15 03:54 UTC
https://metamart.space/

I don't think this site is a scam or anything.

**Comment by devenblake** [comment] 2021-11-15 23:48
Duplicate of #5922.

**Comment by 717natsuki** [comment] 2021-11-17 06:27
Hi, when I access the website, it still says there is "Ethereum Phishing Detection". 
Could you please check it out?

Thank you,
Natsuki

**Closed** 2021-11-24 07:27 UTC
