### ISSUE TITLE
[Legitimate Site Blocked] metamarz.io

### ISSUE THREAD

**Issue by bmohammed** [MetaMask/eth-phishing-detect#6174] opened 2021-12-11 00:57 UTC
http://metamarz.io/

Why is this still an issue, can someone please remove our website form this.  We are still working on updating our website and it will be hard to get people to our site with this phishing warning for no reason.

**Comment by devenblake** [comment] 2021-12-11 01:14
Duplicate of #6047.

**Comment by bmohammed** [comment] 2021-12-11 04:58
> Duplicate of #6047.

I understand its a duplicate but the original ticket has not been resolved yet.  Can we please get that ticket resolved?

**Comment by devenblake** [comment] 2021-12-11 14:21
If you leave a comment on the original issue it'll send an e-mail to all who are watching the repository, same as filing an issue.

**Closed** 2021-12-14 01:16 UTC
Labels: duplicate
