### ISSUE TITLE
[Legitimate Site Blocked] metabank.li

### ISSUE THREAD

**Issue by VictorMetabank** [MetaMask/eth-phishing-detect#7384] opened 2022-05-15 11:26 UTC
https://metabank.li/

This is a newly acquired domain, I cannot find it listed in this list https://cryptoscamdb.org/search?
We are trying to launch a legitimate business by the end of the month and the MetaMask warning is causing problems for some of our potential customers.

Thanks you for reviewing this case.

**Comment by devenblake** [comment] 2022-05-16 03:33
Duplicate of #7368.

**Closed by devenblake** 2022-05-16 03:33 UTC
Labels: duplicate, allowlist request
