### ISSUE TITLE
[Legitimate Site Blocked] willsmithinu.io

### ISSUE THREAD

**Issue by Apedaddyceo** [MetaMask/eth-phishing-detect#7037] opened 2022-04-01 17:36 UTC
https://willsmithinu.io/

No Wallet sign or connection. Site is fully safe. Had multiple people confirm with me. Please remove the phishing warning from the website It is incorrect and damaging the project and community. Thank you.

**Comment by devenblake** [comment] 2022-04-08 00:41
Duplicate of #7023.

**Closed by devenblake** 2022-04-08 00:41 UTC
Labels: duplicate, allowlist request
