### ISSUE TITLE
[Legitimate Site Blocked] cldinvest.io

### ISSUE THREAD

**Issue by alexmezdreagia** [MetaMask/eth-phishing-detect#7571] opened 2022-06-01 19:41 UTC
https://cldinvest.io/
Metamask doesnt allow me to connect with the site. Please help me do that as the site is to a fraud or anything else.

**Comment by devenblake** [comment] 2022-06-10 22:18
Duplicate of #7385.

**Closed by devenblake** 2022-06-10 22:18 UTC
Labels: duplicate, allowlist request
