### ISSUE TITLE
The domain hedget.com is incorrectly flagged!!

### ISSUE THREAD

**Issue by shaimo** [MetaMask/eth-phishing-detect#4383] opened 2020-11-06 14:56 UTC
Please unflag ASAP and allow access to it. Thanks

**Comment by 409H** [comment] 2020-11-06 14:59
This domain was added to the whitelist https://github.com/MetaMask/eth-phishing-detect/pull/4331 - I also cannot reproduce the warning screen.

What browser are you using?

**Comment by shaimo** [comment] 2020-11-06 15:11
Chrome on Mac

**Comment by danfinlay** [comment] 2020-11-07 01:00
Fixed by #4388

**Closed by danfinlay** 2020-11-07 01:00 UTC
Labels: needs-more-information, whitelist request
