### ISSUE TITLE
[Legitimate Site Blocked] shido.market

### ISSUE THREAD

**Issue by bjornbonnevier** [MetaMask/eth-phishing-detect#8986] opened 2022-10-19 06:52 UTC
https://shido.market/

This is as legit as it gets, Shido Finance. Marketplace powered by NFTIFY.

Could you please look into this Metamask?

Thank you.

Bjorn

**Comment by 409H** [comment] 2022-11-07 21:42
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/9037

**Closed by 409H** 2022-11-07 21:42 UTC
Labels: duplicate, allowlist request
