### ISSUE TITLE
Metamask wallet

### ISSUE THREAD

**Issue by KevorkBartekian** [MetaMask/eth-phishing-detect#4832] opened 2021-03-16 17:41 UTC
Hello so actually i have 2 pcs and i was entering my wallet from both of them and  i guess i got blocked!
so solve it please!

**Comment by KevorkBartekian** [comment] 2021-03-16 19:15
how can i open back my pancake swap? help please

**Comment by 409H** [comment] 2022-11-07 22:38
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/4803

**Closed by 409H** 2022-11-07 22:38 UTC
Labels: duplicate, allowlist request
