### ISSUE TITLE
[Legitimate Site Blocked] foundation.app

### ISSUE THREAD

**Issue by iCmyNFT** [MetaMask/eth-phishing-detect#8595] opened 2022-09-29 07:47 UTC
https://foundation.app/@icmynft

**Comment by iCmyNFT** [comment] 2022-09-29 07:49
I would like to use the site in peace!?

**Comment by 409H** [comment] 2022-11-07 22:02
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8588

**Closed by 409H** 2022-11-07 22:02 UTC
Labels: duplicate, allowlist request
