### ISSUE TITLE
[Legitimate Site Blocked] www.empowr.com

### ISSUE THREAD

**Issue by sksaha61** [MetaMask/eth-phishing-detect#6210] opened 2021-12-16 16:15 UTC
http://www.empowr.com/socnet/EmailStat.aspx?lit=5&me=otUh9vs.UpO4Fqj8rQcy8O-jVvR-AxXQ8NVAvu7cBC0Jnr-U5p7kWRI1AlPZJuIW3BW-dP79DcHPTPYPsLZvjOUn1-d15u8XlJSD0wmIjNDUDjrzqXEA.mG3so9jFk2fNFsxO1rczqJDMtkIHxHPYU-wvw3xnhBY7X7YaqzOl51Uou4.bvzBqqPmT3DcFPAv&fan=F1Qw1zM6IEk%3d&opg=https%3a%2f%2fsecure.empowr.com%2fPremiumBlogs%2fAccountSecurityEntrance.aspx%3fFlowFlavor%3dEthereumAccountCompletion&vet=616&dt=071019&mlid=10779247702&tmpID=1&linkname=Validation&emailNum=0&eaid=yM9KXk6njAlsh2TqFPu%2b7w%3d%3d&rt=12

**Comment by devenblake** [comment] 2021-12-27 22:12
Duplicate of #2663.

**Closed** 2022-01-12 23:07 UTC
