### ISSUE TITLE
[Legitimate Site Blocked] www.superstep.io

### ISSUE THREAD

**Issue by Nikolay0384** [MetaMask/eth-phishing-detect#7696] opened 2022-06-16 05:47 UTC
https://www.superstep.io/airdrop?ref=tiih19

**Comment by devenblake** [comment] 2022-06-16 09:19
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/7642.

**Closed by devenblake** 2022-06-16 09:20 UTC
Labels: duplicate, allowlist request
