### ISSUE TITLE
podcastrebels.com flagged incorrectly

### ISSUE THREAD

**Issue by JamieAtkinson92** [MetaMask/eth-phishing-detect#8165] opened 2022-08-11 17:37 UTC
Hello, 

one of my business websites domains has been flagged by Meta Mask as a phishing attempt. 

It's coming up with this URL - https://metamask.github.io/phishing-warning/v1.1.0/

**The form in question...** 

It is a simple JotForm application form we use in our business, to get podcast guests to come get featured on our website. 

Here is our podcast (to show legitimacy) - https://podcastrebels.com/podcast

And our form is embedded on this page (at the bottom) -- https://www.podcastrebels.com/interview-application

Here is the actual form directly -- https://form.jotform.com/221956495070865

**Please can you update the system to remove this from the process?**

I've attached a screenshot from one of our clients below to show the issue in real time. 

https://drive.google.com/file/d/1x_-aAvJplen1hN56V4UZdJxZ7gJAphV4/view?usp=sharing

Thank you,

Jamie Atkinson

**Comment by JamieAtkinson92** [comment] 2022-09-17 08:15
Hi! Can you please provide updates on this ticket?

**Comment by 409H** [comment] 2022-11-07 22:16
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8142

**Closed by 409H** 2022-11-07 22:16 UTC
Labels: duplicate, allowlist request
