### ISSUE TITLE
333

### ISSUE THREAD

**Issue by medwetua** [MetaMask/eth-phishing-detect#2378] opened 2018-09-11 19:22 UTC
333eth.io - are trying to falsely accuse. 333 -payments. remove the lock, please.

**Comment by net968** [comment] 2018-09-11 19:40
333ETH.IO - IS NOT A SCAM AND NOT A FISHING SITE.
This is the machinations of competitors. Unlock this site, please

**Comment by 409H** [comment] 2018-09-12 00:56
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2374

**Closed by 409H** 2018-09-12 00:56 UTC
