### ISSUE TITLE
PancakeSwap is not fishing

### ISSUE THREAD

**Issue by ScyLabs** [MetaMask/eth-phishing-detect#4815] opened 2021-03-16 12:38 UTC
pancakeswap.finance is not a fishing. They are hecked by DNS injection yesterday , but i'ts fixed

**Comment by ashtonbannister** [comment] 2021-03-16 16:07
Pancakeswap DNS Hijack was fixed more than 24 hours ago. The warning is unnecessary and was far too late. The whole problem with the cloudflare dns hijack was resolved in less than 2 hours.

**Comment by 409H** [comment] 2022-11-07 22:41
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/4803

**Closed by 409H** 2022-11-07 22:41 UTC
Labels: duplicate, allowlist request
