### ISSUE TITLE
[Legitimate Site Blocked] mint.adrunner.io

### ISSUE THREAD

**Issue by CaptainFortuna** [MetaMask/eth-phishing-detect#6954] opened 2022-03-28 21:11 UTC
https://mint.adrunner.io/

Is a legitimate NFT project that us under attack by its ex CMO by blacklisting this site you're destroying the community they're building

**Comment by devenblake** [comment] 2022-03-29 01:34
Duplicate of #6944.

**Closed by devenblake** 2022-03-29 01:34 UTC
Labels: duplicate, allowlist request
