### ISSUE TITLE
[Legitimate Site Blocked] form.jotform.com

### ISSUE THREAD

**Issue by easyeatsnz** [MetaMask/eth-phishing-detect#8143] opened 2022-08-11 02:00 UTC
https://form.jotform.com/221928646867876?isIframeEmbed=1

hello why is this site being blocked?
https://easyeatsnz.co.nz/drive-with-us/
https://easyeatsnz.co.nz/partner/

Thanks

**Comment by 409H** [comment] 2022-11-07 22:15
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/8142

**Closed by 409H** 2022-11-07 22:15 UTC
Labels: duplicate, allowlist request
