### ISSUE TITLE
[Legitimate Site Blocked] murakamiflowers.kaikaikiki.com

### ISSUE THREAD

**Issue by Mikey4413** [MetaMask/eth-phishing-detect#7296] opened 2022-05-02 12:30 UTC
This site is 100% legit!! MetaMask you need to fix this issue ASAP!! Many scam sites impersonating been blocked, but this is the actual real one and you put warning on it!! Common!

https://murakamiflowers.kaikaikiki.com/

**Comment by devenblake** [comment] 2022-05-05 22:53
Duplicate of #7260.

**Closed by devenblake** 2022-05-05 22:53 UTC
Labels: duplicate, allowlist request
