### ISSUE TITLE
[Legitimate Site Blocked] junoswap.com

### ISSUE THREAD

**Issue by lnxelnope** [MetaMask/eth-phishing-detect#7863] opened 2022-07-01 02:12 UTC
https://junoswap.com/

this site use keplr wallet. its a main dex of juno protocol. which is run on cosmos tendermint. 
it's have nothing to do with evm ... so it doesn't use metamask wallet.

**Comment by devenblake** [comment] 2022-07-01 23:07
Duplicate of #7817.

**Closed by devenblake** 2022-07-01 23:07 UTC
Labels: duplicate, allowlist request
