### ISSUE TITLE
[Legitimate Site Blocked] www.superstep.io

### ISSUE THREAD

**Issue by BinhanHN** [MetaMask/eth-phishing-detect#7664] opened 2022-06-11 16:15 UTC
https://www.superstep.io/airdrop?ref=rmrpdc

**Comment by devenblake** [comment] 2022-06-14 21:58
Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/7642.

**Closed by devenblake** 2022-06-14 21:58 UTC
Labels: duplicate, allowlist request
