### ISSUE TITLE
[Legitimate Site Blocked] impostors.gg

### ISSUE THREAD

**Issue by Barrock69** [MetaMask/eth-phishing-detect#7475] opened 2022-05-25 10:50 UTC
https://impostors.gg/claim

Hi this is a legitimate site for SuperFarm - from EllioTrades Crypto (YouTube).
https://www.youtube.com/c/FUDTV

I've included their Discord official-links page below: -
https://discord.com/channels/930107884849745930/930107885554401318/943582242939215894

Here is the CoinGecko link to SuperFarm
https://www.coingecko.com/en/coins/superfarm

Twitter: -
https://twitter.com/elliotrades
@elliotrades
@PlayImposters

I hope this provides enough information for you to be sure their site is legitimate?
Thank you.

**Comment by TimTinkers** [comment] 2022-05-25 19:20
Duplicate of #7469; thanks for trying to help us out!

**Closed** 2022-05-25 20:10 UTC
Labels: duplicate, allowlist request
