### ISSUE TITLE
Empowr and phishing

### ISSUE THREAD

**Issue by flowellness** [MetaMask/eth-phishing-detect#2664] opened 2018-11-27 04:28 UTC
Thank you for taking care of me but Empowr is not a Phishing company.

**Comment by jeckoz** [comment] 2018-11-27 11:37
yes it is scam

**Comment by 409H** [comment] 2018-11-27 14:39
Closing. Duplicate of https://github.com/MetaMask/eth-phishing-detect/issues/2663

**Closed by 409H** 2018-11-27 14:39 UTC
Labels: duplicate

**Comment by flowellness** [comment] 2018-11-27 18:37
No it is not a scam, please read Brian's information and paper work. I have been with this company for nearly a year and I know many people who have worked with them years.
    On Tuesday, November 27, 2018, 1:37:23 PM GMT+2, jeckoz <notifications@github.com> wrote:  
 
 
yes it is scam
